#!/usr/bin/env python3
"""Regenerate every downstream copy of the legal docs from docs/*.md.

The web, iOS and Android copies drifted because they were hand-synced. Run this
after editing a canonical doc; `--check` fails instead of writing, for CI.
"""
import pathlib, sys, re

ROOT = pathlib.Path(__file__).resolve().parent
PROJECTS = ROOT.parent

DOCS = {"privacy-policy": ROOT / "docs/PRIVACY_POLICY.md",
        "terms-of-service": ROOT / "docs/TERMS_OF_SERVICE.md"}


def body(raw: str) -> str:
    """Strip the reviewer preamble and the internal checklist, as the three
    renderers already do at runtime. Keeps them byte-identical to what ships."""
    out = raw.split("\n## Outstanding placeholders")[0]
    i = out.find("\n---\n")
    if i != -1:
        out = out[i + len("\n---\n"):]
    return out.rstrip().removesuffix("---").strip()


def swift(privacy: str, terms: str) -> str:
    return (
        "import Foundation\n\n"
        "// Bundled full legal text — generated by paperboxd-backend/scripts_sync_legal.py.\n"
        "// Rendered natively in the signup consent bottom sheet (LegalSheetView).\n"
        "// Canonical source: paperboxd-backend/docs/{PRIVACY_POLICY,TERMS_OF_SERVICE}.md.\n"
        "// Do not hand-edit: rerun the script instead.\n\n"
        "enum LegalText {\n"
        f'    static let privacyPolicy = #"""\n{privacy}\n"""#\n\n'
        f'    static let termsOfService = #"""\n{terms}\n"""#\n'
        "}\n"
    )


def targets(bodies):
    web = PROJECTS / "paperboxd/content/legal"
    android = PROJECTS / "paperboxd-android/app/src/main/assets/legal"
    ios = PROJECTS / "paperboxd-ios/PaperBoxd/Features/Auth/LegalText.swift"
    out = {}
    for slug, raw in bodies.items():
        # Web and Android keep the full file: their renderers strip at runtime.
        out[web / f"{slug}.md"] = raw
        out[android / f"{slug}.md"] = raw
    out[ios] = swift(body(bodies["privacy-policy"]), body(bodies["terms-of-service"]))
    return out


def main() -> int:
    bodies = {slug: p.read_text() for slug, p in DOCS.items()}
    check = "--check" in sys.argv
    drifted = []
    for path, content in targets(bodies).items():
        if path.exists() and path.read_text() == content:
            continue
        drifted.append(path)
        if not check:
            path.write_text(content)
    if check and drifted:
        print("legal copies out of sync with docs/:")
        for p in drifted:
            print(f"  {p}")
        return 1
    print(("in sync" if check else f"wrote {len(drifted)} file(s)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
