DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS bookshelf CASCADE;
ALTER TABLE books DROP COLUMN IF EXISTS categories;
ALTER TABLE books DROP COLUMN IF EXISTS cover_url;
ALTER TABLE books DROP COLUMN IF EXISTS language;
ALTER TABLE books DROP COLUMN IF EXISTS page_count;
ALTER TABLE books DROP COLUMN IF EXISTS published_date;
ALTER TABLE books DROP COLUMN IF EXISTS description;
