ALTER TABLE books DROP COLUMN IF EXISTS total_tbr_count;
ALTER TABLE books DROP COLUMN IF EXISTS total_reads_count;
ALTER TABLE books DROP COLUMN IF EXISTS preview_link;
ALTER TABLE books DROP COLUMN IF EXISTS ratings_count;
ALTER TABLE books DROP COLUMN IF EXISTS average_rating;
ALTER TABLE books DROP COLUMN IF EXISTS open_library_id;
ALTER TABLE books DROP COLUMN IF EXISTS isbndb_id;
ALTER TABLE books DROP COLUMN IF EXISTS publisher;
ALTER TABLE books DROP COLUMN IF EXISTS subtitle;

ALTER TABLE users DROP COLUMN IF EXISTS total_pages_read;
ALTER TABLE users DROP COLUMN IF EXISTS links;
ALTER TABLE users DROP COLUMN IF EXISTS gender;
ALTER TABLE users DROP COLUMN IF EXISTS birthday;
ALTER TABLE users ALTER COLUMN pronouns TYPE VARCHAR(50) USING CASE WHEN pronouns IS NULL THEN NULL WHEN array_length(pronouns, 1) > 0 THEN pronouns[1] ELSE NULL END;
