// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activityExistsRecent = `-- name: ActivityExistsRecent :one
SELECT EXISTS(
    SELECT 1 FROM activities
    WHERE user_id = $1 AND book_id = $2 AND activity_type = $3
      AND created_at > NOW() - INTERVAL '1 day'
)
`

type ActivityExistsRecentParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	BookID       pgtype.UUID `json:"book_id"`
	ActivityType string      `json:"activity_type"`
}

// Dedupe guard for shelf activities: the same (user, book, type) within a day
// is a re-save, not news.
func (q *Queries) ActivityExistsRecent(ctx context.Context, arg ActivityExistsRecentParams) (bool, error) {
	row := q.db.QueryRow(ctx, activityExistsRecent, arg.UserID, arg.BookID, arg.ActivityType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkNewActivities = `-- name: CheckNewActivities :one
SELECT EXISTS(
    SELECT 1 FROM activities a
    JOIN users u ON a.user_id = u.id
    WHERE u.deleted_at IS NULL
    AND (
        (a.user_id IN (SELECT following_id FROM follows WHERE follower_id = $1)
         AND a.activity_type <> 'fusion_joined')
        OR (a.activity_type IN ('shared_list', 'shared_book', 'granted_access', 'liked_thought', 'reposted_thought', 'fusion_joined')
            AND a.target_user_id = $1)
    )
    AND a.created_at > $2
)
`

type CheckNewActivitiesParams struct {
	FollowerID uuid.UUID        `json:"follower_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CheckNewActivities(ctx context.Context, arg CheckNewActivitiesParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNewActivities, arg.FollowerID, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUnreadActivities = `-- name: CountUnreadActivities :one
SELECT COUNT(*) FROM activities
WHERE target_user_id = $1 AND read_at IS NULL
`

// Unread badge for the notifications sheet. target_user_id is the "addressed to
// you" marker — every activity type that carries one (liked_thought, reposted_thought,
// shared_list, shared_book, granted_access, fusion_joined) is notification-worthy, so no
// activity_type filter is needed here.
func (q *Queries) CountUnreadActivities(ctx context.Context, targetUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadActivities, targetUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, activity_type, book_id, list_id, thought_id, target_user_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, activity_type, book_id, list_id, thought_id, target_user_id, metadata, created_at, read_at
`

type CreateActivityParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	ActivityType string      `json:"activity_type"`
	BookID       pgtype.UUID `json:"book_id"`
	ListID       pgtype.UUID `json:"list_id"`
	ThoughtID    pgtype.UUID `json:"thought_id"`
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.ActivityType,
		arg.BookID,
		arg.ListID,
		arg.ThoughtID,
		arg.TargetUserID,
		arg.Metadata,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityType,
		&i.BookID,
		&i.ListID,
		&i.ThoughtID,
		&i.TargetUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteUserActivities = `-- name: DeleteUserActivities :exec
DELETE FROM activities
WHERE user_id = $1 AND activity_type = $2
`

type DeleteUserActivitiesParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityType string    `json:"activity_type"`
}

func (q *Queries) DeleteUserActivities(ctx context.Context, arg DeleteUserActivitiesParams) error {
	_, err := q.db.Exec(ctx, deleteUserActivities, arg.UserID, arg.ActivityType)
	return err
}

const getActivityByID = `-- name: GetActivityByID :one
SELECT id, user_id, activity_type, book_id, list_id, thought_id, target_user_id, metadata, created_at, read_at FROM activities
WHERE id = $1
`

func (q *Queries) GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityType,
		&i.BookID,
		&i.ListID,
		&i.ThoughtID,
		&i.TargetUserID,
		&i.Metadata,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getFollowingActivities = `-- name: GetFollowingActivities :many
SELECT
    a.id,
    a.user_id,
    a.activity_type,
    a.book_id,
    a.list_id,
    a.thought_id,
    a.target_user_id,
    a.metadata,
    a.created_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title as book_title,
    b.slug as book_slug,
    l.title as list_title,
    de.title as thought_title,
    tu.username as target_username
FROM activities a
JOIN users u ON a.user_id = u.id
LEFT JOIN books b ON a.book_id = b.id
LEFT JOIN lists l ON a.list_id = l.id
LEFT JOIN thoughts de ON a.thought_id = de.id
LEFT JOIN users tu ON a.target_user_id = tu.id
WHERE u.deleted_at IS NULL
  AND (
    -- fusion_joined is addressed to the inviter only, never broadcast to the
    -- invitee's followers.
    (a.user_id IN (
        SELECT following_id FROM follows WHERE follower_id = $1
    ) AND a.activity_type <> 'fusion_joined')
    OR (a.activity_type IN ('shared_list', 'shared_book', 'granted_access', 'liked_thought', 'reposted_thought', 'fusion_joined')
        AND a.target_user_id = $1)
  )
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingActivitiesParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetFollowingActivitiesRow struct {
	ID             uuid.UUID        `json:"id"`
	UserID         uuid.UUID        `json:"user_id"`
	ActivityType   string           `json:"activity_type"`
	BookID         pgtype.UUID      `json:"book_id"`
	ListID         pgtype.UUID      `json:"list_id"`
	ThoughtID      pgtype.UUID      `json:"thought_id"`
	TargetUserID   pgtype.UUID      `json:"target_user_id"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Username       string           `json:"username"`
	Name           pgtype.Text      `json:"name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	BookTitle      pgtype.Text      `json:"book_title"`
	BookSlug       pgtype.Text      `json:"book_slug"`
	ListTitle      pgtype.Text      `json:"list_title"`
	ThoughtTitle   pgtype.Text      `json:"thought_title"`
	TargetUsername pgtype.Text      `json:"target_username"`
}

func (q *Queries) GetFollowingActivities(ctx context.Context, arg GetFollowingActivitiesParams) ([]GetFollowingActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getFollowingActivities, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingActivitiesRow{}
	for rows.Next() {
		var i GetFollowingActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.BookID,
			&i.ListID,
			&i.ThoughtID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.ListTitle,
			&i.ThoughtTitle,
			&i.TargetUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicActivities = `-- name: GetPublicActivities :many
SELECT
    a.id,
    a.user_id,
    a.activity_type,
    a.book_id,
    a.list_id,
    a.thought_id,
    a.target_user_id,
    a.metadata,
    a.created_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title as book_title,
    b.slug as book_slug,
    b.cover_url as book_cover,
    l.title as list_title,
    de.title as thought_title,
    tu.username as target_username
FROM activities a
JOIN users u ON a.user_id = u.id
LEFT JOIN books b ON a.book_id = b.id
LEFT JOIN lists l ON a.list_id = l.id
LEFT JOIN thoughts de ON a.thought_id = de.id
LEFT JOIN users tu ON a.target_user_id = tu.id
WHERE u.deleted_at IS NULL
  AND u.is_public = true
  AND a.target_user_id IS NULL
  AND (a.list_id IS NULL OR l.is_private = false)
  AND (a.thought_id IS NULL OR de.is_private = false)
ORDER BY a.created_at DESC
LIMIT $1
`

type GetPublicActivitiesRow struct {
	ID             uuid.UUID        `json:"id"`
	UserID         uuid.UUID        `json:"user_id"`
	ActivityType   string           `json:"activity_type"`
	BookID         pgtype.UUID      `json:"book_id"`
	ListID         pgtype.UUID      `json:"list_id"`
	ThoughtID      pgtype.UUID      `json:"thought_id"`
	TargetUserID   pgtype.UUID      `json:"target_user_id"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Username       string           `json:"username"`
	Name           pgtype.Text      `json:"name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	BookTitle      pgtype.Text      `json:"book_title"`
	BookSlug       pgtype.Text      `json:"book_slug"`
	BookCover      pgtype.Text      `json:"book_cover"`
	ListTitle      pgtype.Text      `json:"list_title"`
	ThoughtTitle   pgtype.Text      `json:"thought_title"`
	TargetUsername pgtype.Text      `json:"target_username"`
}

// Community feed for logged-out visitors and thin follow graphs. Only public,
// live accounts; only broadcast rows (anything addressed to a target user is a
// notification, not news); private lists and thoughts stay hidden.
// Over-fetch and collapse per user in Go so one import does not own the feed.
func (q *Queries) GetPublicActivities(ctx context.Context, limit int32) ([]GetPublicActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getPublicActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublicActivitiesRow{}
	for rows.Next() {
		var i GetPublicActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.BookID,
			&i.ListID,
			&i.ThoughtID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.BookCover,
			&i.ListTitle,
			&i.ThoughtTitle,
			&i.TargetUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivities = `-- name: GetUserActivities :many
SELECT
    a.id,
    a.user_id,
    a.activity_type,
    a.book_id,
    a.list_id,
    a.thought_id,
    a.target_user_id,
    a.metadata,
    a.created_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title as book_title,
    b.slug as book_slug,
    l.title as list_title,
    de.title as thought_title,
    tu.username as target_username
FROM activities a
JOIN users u ON a.user_id = u.id
LEFT JOIN books b ON a.book_id = b.id
LEFT JOIN lists l ON a.list_id = l.id
LEFT JOIN thoughts de ON a.thought_id = de.id
LEFT JOIN users tu ON a.target_user_id = tu.id
WHERE a.user_id = $1
  -- fusion_joined is addressed to one reader; never on a profile.
  AND a.activity_type <> 'fusion_joined'
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserActivitiesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserActivitiesRow struct {
	ID             uuid.UUID        `json:"id"`
	UserID         uuid.UUID        `json:"user_id"`
	ActivityType   string           `json:"activity_type"`
	BookID         pgtype.UUID      `json:"book_id"`
	ListID         pgtype.UUID      `json:"list_id"`
	ThoughtID      pgtype.UUID      `json:"thought_id"`
	TargetUserID   pgtype.UUID      `json:"target_user_id"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Username       string           `json:"username"`
	Name           pgtype.Text      `json:"name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	BookTitle      pgtype.Text      `json:"book_title"`
	BookSlug       pgtype.Text      `json:"book_slug"`
	ListTitle      pgtype.Text      `json:"list_title"`
	ThoughtTitle   pgtype.Text      `json:"thought_title"`
	TargetUsername pgtype.Text      `json:"target_username"`
}

func (q *Queries) GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]GetUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserActivities, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserActivitiesRow{}
	for rows.Next() {
		var i GetUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.BookID,
			&i.ListID,
			&i.ThoughtID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.ListTitle,
			&i.ThoughtTitle,
			&i.TargetUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivitiesRead = `-- name: MarkActivitiesRead :exec
UPDATE activities
SET read_at = NOW()
WHERE target_user_id = $1 AND read_at IS NULL
`

// Called when the sheet opens. Idempotent; leaves already-read rows alone so a
// reopen does not churn timestamps.
func (q *Queries) MarkActivitiesRead(ctx context.Context, targetUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markActivitiesRead, targetUserID)
	return err
}
