// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkNewActivities = `-- name: CheckNewActivities :one
SELECT EXISTS(
    SELECT 1 FROM activities a
    JOIN users u ON a.user_id = u.id
    WHERE u.deleted_at IS NULL
    AND (
        a.user_id IN (SELECT following_id FROM follows WHERE follower_id = $1)
        OR (a.activity_type IN ('shared_list', 'shared_book', 'granted_access', 'liked_diary_entry')
            AND a.target_user_id = $1)
    )
    AND a.created_at > $2
)
`

type CheckNewActivitiesParams struct {
	FollowerID uuid.UUID        `json:"follower_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CheckNewActivities(ctx context.Context, arg CheckNewActivitiesParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNewActivities, arg.FollowerID, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, activity_type, book_id, list_id, entry_id, target_user_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, activity_type, book_id, list_id, entry_id, target_user_id, metadata, created_at
`

type CreateActivityParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	ActivityType string      `json:"activity_type"`
	BookID       pgtype.UUID `json:"book_id"`
	ListID       pgtype.UUID `json:"list_id"`
	EntryID      pgtype.UUID `json:"entry_id"`
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.ActivityType,
		arg.BookID,
		arg.ListID,
		arg.EntryID,
		arg.TargetUserID,
		arg.Metadata,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityType,
		&i.BookID,
		&i.ListID,
		&i.EntryID,
		&i.TargetUserID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserActivities = `-- name: DeleteUserActivities :exec
DELETE FROM activities
WHERE user_id = $1 AND activity_type = $2
`

type DeleteUserActivitiesParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ActivityType string    `json:"activity_type"`
}

func (q *Queries) DeleteUserActivities(ctx context.Context, arg DeleteUserActivitiesParams) error {
	_, err := q.db.Exec(ctx, deleteUserActivities, arg.UserID, arg.ActivityType)
	return err
}

const getActivityByID = `-- name: GetActivityByID :one
SELECT id, user_id, activity_type, book_id, list_id, entry_id, target_user_id, metadata, created_at FROM activities
WHERE id = $1
`

func (q *Queries) GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityType,
		&i.BookID,
		&i.ListID,
		&i.EntryID,
		&i.TargetUserID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowingActivities = `-- name: GetFollowingActivities :many
SELECT
    a.id,
    a.user_id,
    a.activity_type,
    a.book_id,
    a.list_id,
    a.entry_id,
    a.target_user_id,
    a.metadata,
    a.created_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title as book_title,
    b.slug as book_slug,
    l.title as list_title,
    de.title as entry_title,
    tu.username as target_username
FROM activities a
JOIN users u ON a.user_id = u.id
LEFT JOIN books b ON a.book_id = b.id
LEFT JOIN lists l ON a.list_id = l.id
LEFT JOIN diary_entries de ON a.entry_id = de.id
LEFT JOIN users tu ON a.target_user_id = tu.id
WHERE u.deleted_at IS NULL
  AND (
    a.user_id IN (
        SELECT following_id FROM follows WHERE follower_id = $1
    )
    OR (a.activity_type IN ('shared_list', 'shared_book', 'granted_access', 'liked_diary_entry')
        AND a.target_user_id = $1)
  )
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingActivitiesParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetFollowingActivitiesRow struct {
	ID             uuid.UUID        `json:"id"`
	UserID         uuid.UUID        `json:"user_id"`
	ActivityType   string           `json:"activity_type"`
	BookID         pgtype.UUID      `json:"book_id"`
	ListID         pgtype.UUID      `json:"list_id"`
	EntryID        pgtype.UUID      `json:"entry_id"`
	TargetUserID   pgtype.UUID      `json:"target_user_id"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Username       string           `json:"username"`
	Name           pgtype.Text      `json:"name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	BookTitle      pgtype.Text      `json:"book_title"`
	BookSlug       pgtype.Text      `json:"book_slug"`
	ListTitle      pgtype.Text      `json:"list_title"`
	EntryTitle     pgtype.Text      `json:"entry_title"`
	TargetUsername pgtype.Text      `json:"target_username"`
}

func (q *Queries) GetFollowingActivities(ctx context.Context, arg GetFollowingActivitiesParams) ([]GetFollowingActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getFollowingActivities, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingActivitiesRow{}
	for rows.Next() {
		var i GetFollowingActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.BookID,
			&i.ListID,
			&i.EntryID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.ListTitle,
			&i.EntryTitle,
			&i.TargetUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivities = `-- name: GetUserActivities :many
SELECT
    a.id,
    a.user_id,
    a.activity_type,
    a.book_id,
    a.list_id,
    a.entry_id,
    a.target_user_id,
    a.metadata,
    a.created_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title as book_title,
    b.slug as book_slug,
    l.title as list_title,
    de.title as entry_title,
    tu.username as target_username
FROM activities a
JOIN users u ON a.user_id = u.id
LEFT JOIN books b ON a.book_id = b.id
LEFT JOIN lists l ON a.list_id = l.id
LEFT JOIN diary_entries de ON a.entry_id = de.id
LEFT JOIN users tu ON a.target_user_id = tu.id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserActivitiesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserActivitiesRow struct {
	ID             uuid.UUID        `json:"id"`
	UserID         uuid.UUID        `json:"user_id"`
	ActivityType   string           `json:"activity_type"`
	BookID         pgtype.UUID      `json:"book_id"`
	ListID         pgtype.UUID      `json:"list_id"`
	EntryID        pgtype.UUID      `json:"entry_id"`
	TargetUserID   pgtype.UUID      `json:"target_user_id"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	Username       string           `json:"username"`
	Name           pgtype.Text      `json:"name"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	BookTitle      pgtype.Text      `json:"book_title"`
	BookSlug       pgtype.Text      `json:"book_slug"`
	ListTitle      pgtype.Text      `json:"list_title"`
	EntryTitle     pgtype.Text      `json:"entry_title"`
	TargetUsername pgtype.Text      `json:"target_username"`
}

func (q *Queries) GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]GetUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserActivities, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserActivitiesRow{}
	for rows.Next() {
		var i GetUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityType,
			&i.BookID,
			&i.ListID,
			&i.EntryID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.ListTitle,
			&i.EntryTitle,
			&i.TargetUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
