// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupStaleBooks = `-- name: CleanupStaleBooks :execrows
DELETE FROM books
WHERE created_at < NOW() - INTERVAL '15 days'
  AND id NOT IN (
      SELECT DISTINCT book_id FROM bookshelf
      UNION
      SELECT DISTINCT book_id FROM likes
  )
`

func (q *Queries) CleanupStaleBooks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupStaleBooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, slug, authors, isbn_13, google_books_id,
    description, published_date, page_count, language, cover_url, categories,
    subtitle, publisher, isbndb_id, open_library_id, average_rating, preview_link,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (google_books_id) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    description = EXCLUDED.description,
    cover_url = EXCLUDED.cover_url,
    subtitle = EXCLUDED.subtitle,
    publisher = EXCLUDED.publisher,
    isbndb_id = EXCLUDED.isbndb_id,
    average_rating = EXCLUDED.average_rating,
    updated_at = NOW()
RETURNING id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding
`

type CreateBookParams struct {
	Title         string        `json:"title"`
	Slug          string        `json:"slug"`
	Authors       []string      `json:"authors"`
	Isbn13        pgtype.Text   `json:"isbn_13"`
	GoogleBooksID pgtype.Text   `json:"google_books_id"`
	Description   pgtype.Text   `json:"description"`
	PublishedDate pgtype.Date   `json:"published_date"`
	PageCount     pgtype.Int4   `json:"page_count"`
	Language      pgtype.Text   `json:"language"`
	CoverUrl      pgtype.Text   `json:"cover_url"`
	Categories    []string      `json:"categories"`
	Subtitle      pgtype.Text   `json:"subtitle"`
	Publisher     pgtype.Text   `json:"publisher"`
	IsbndbID      pgtype.Text   `json:"isbndb_id"`
	OpenLibraryID pgtype.Text   `json:"open_library_id"`
	AverageRating pgtype.Float8 `json:"average_rating"`
	PreviewLink   pgtype.Text   `json:"preview_link"`
	Metadata      []byte        `json:"metadata"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Slug,
		arg.Authors,
		arg.Isbn13,
		arg.GoogleBooksID,
		arg.Description,
		arg.PublishedDate,
		arg.PageCount,
		arg.Language,
		arg.CoverUrl,
		arg.Categories,
		arg.Subtitle,
		arg.Publisher,
		arg.IsbndbID,
		arg.OpenLibraryID,
		arg.AverageRating,
		arg.PreviewLink,
		arg.Metadata,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const createBookFromISBNdb = `-- name: CreateBookFromISBNdb :one
INSERT INTO books (
    title, slug, authors, isbn_13,
    description, published_date, page_count, language, cover_url, categories,
    publisher, isbndb_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (isbn_13) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    description = EXCLUDED.description,
    cover_url = EXCLUDED.cover_url,
    publisher = EXCLUDED.publisher,
    isbndb_id = EXCLUDED.isbndb_id,
    updated_at = NOW()
RETURNING id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding
`

type CreateBookFromISBNdbParams struct {
	Title         string      `json:"title"`
	Slug          string      `json:"slug"`
	Authors       []string    `json:"authors"`
	Isbn13        pgtype.Text `json:"isbn_13"`
	Description   pgtype.Text `json:"description"`
	PublishedDate pgtype.Date `json:"published_date"`
	PageCount     pgtype.Int4 `json:"page_count"`
	Language      pgtype.Text `json:"language"`
	CoverUrl      pgtype.Text `json:"cover_url"`
	Categories    []string    `json:"categories"`
	Publisher     pgtype.Text `json:"publisher"`
	IsbndbID      pgtype.Text `json:"isbndb_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateBookFromISBNdb(ctx context.Context, arg CreateBookFromISBNdbParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBookFromISBNdb,
		arg.Title,
		arg.Slug,
		arg.Authors,
		arg.Isbn13,
		arg.Description,
		arg.PublishedDate,
		arg.PageCount,
		arg.Language,
		arg.CoverUrl,
		arg.Categories,
		arg.Publisher,
		arg.IsbndbID,
		arg.Metadata,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const getBookByGoogleID = `-- name: GetBookByGoogleID :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books WHERE google_books_id = $1
`

func (q *Queries) GetBookByGoogleID(ctx context.Context, googleBooksID pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByGoogleID, googleBooksID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books WHERE isbn_13 = $1 OR isbndb_id = $1 LIMIT 1
`

func (q *Queries) GetBookByISBN(ctx context.Context, isbn13 pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByISBN, isbn13)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const getBookBySlug = `-- name: GetBookBySlug :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books WHERE slug = $1
`

func (q *Queries) GetBookBySlug(ctx context.Context, slug string) (Book, error) {
	row := q.db.QueryRow(ctx, getBookBySlug, slug)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
	)
	return i, err
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books
WHERE array_to_string(authors, '|') ILIKE '%' || $1 || '%'
ORDER BY view_count DESC
LIMIT $2 OFFSET $3
`

type GetBooksByAuthorParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetBooksByAuthor(ctx context.Context, arg GetBooksByAuthorParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooksByAuthor, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBooks = `-- name: GetLatestBooks :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLatestBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLatestBooks(ctx context.Context, arg GetLatestBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getLatestBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularBooks = `-- name: GetPopularBooks :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books
ORDER BY view_count DESC
LIMIT $1 OFFSET $2
`

type GetPopularBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPopularBooks(ctx context.Context, arg GetPopularBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getPopularBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBookViews = `-- name: IncrementBookViews :exec
UPDATE books SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBookViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementBookViews, id)
	return err
}

const searchBooksInDB = `-- name: SearchBooksInDB :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding FROM books
WHERE title ILIKE '%' || $1 || '%'
   OR $1 = ANY(authors)
ORDER BY view_count DESC
LIMIT $2 OFFSET $3
`

type SearchBooksInDBParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchBooksInDB(ctx context.Context, arg SearchBooksInDBParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooksInDB, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
