// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookshelf.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const addToBookshelf = `-- name: AddToBookshelf :one
INSERT INTO bookshelf (
    user_id, book_id, status, rating, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, book_id) DO UPDATE SET
    status = EXCLUDED.status,
    rating = EXCLUDED.rating,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at,
    updated_at = NOW()
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type AddToBookshelfParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	BookID     uuid.UUID          `json:"book_id"`
	Status     string             `json:"status"`
	Rating     pgtype.Int4        `json:"rating"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) AddToBookshelf(ctx context.Context, arg AddToBookshelfParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, addToBookshelf,
		arg.UserID,
		arg.BookID,
		arg.Status,
		arg.Rating,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const countFriendsReadingBook = `-- name: CountFriendsReadingBook :one
SELECT COUNT(*) FROM follows f
JOIN bookshelf bs ON bs.user_id = f.following_id
WHERE f.follower_id = $1
  AND bs.book_id = $2
  AND bs.status = 'reading'
`

type CountFriendsReadingBookParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	BookID     uuid.UUID `json:"book_id"`
}

// Counts friends actively reading this book right now.
func (q *Queries) CountFriendsReadingBook(ctx context.Context, arg CountFriendsReadingBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFriendsReadingBook, arg.FollowerID, arg.BookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserBooks = `-- name: CountUserBooks :one
SELECT COUNT(*) FROM bookshelf WHERE user_id = $1 AND status = $2
`

type CountUserBooksParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) CountUserBooks(ctx context.Context, arg CountUserBooksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserBooks, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookReviews = `-- name: GetBookReviews :many
SELECT
    bs.user_id,
    bs.rating,
    bs.review,
    bs.reviewed_at,
    bs.review_edited,
    u.username,
    u.avatar_url
FROM bookshelf bs
JOIN users u ON bs.user_id = u.id
WHERE bs.book_id = $1
  AND (bs.rating IS NOT NULL OR (bs.review IS NOT NULL AND bs.review != ''))
ORDER BY bs.reviewed_at DESC NULLS LAST
LIMIT 50
`

type GetBookReviewsRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	Rating       pgtype.Int4        `json:"rating"`
	Review       pgtype.Text        `json:"review"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	ReviewEdited bool               `json:"review_edited"`
	Username     string             `json:"username"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) GetBookReviews(ctx context.Context, bookID uuid.UUID) ([]GetBookReviewsRow, error) {
	rows, err := q.db.Query(ctx, getBookReviews, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookReviewsRow{}
	for rows.Next() {
		var i GetBookReviewsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Rating,
			&i.Review,
			&i.ReviewedAt,
			&i.ReviewEdited,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookReviewsByFriends = `-- name: GetBookReviewsByFriends :many
SELECT
    bs.user_id,
    bs.rating,
    bs.review,
    bs.reviewed_at,
    bs.review_edited,
    u.username,
    u.name,
    u.avatar_url
FROM bookshelf bs
JOIN users u ON bs.user_id = u.id
JOIN follows f ON f.following_id = bs.user_id
WHERE bs.book_id = $1
  AND f.follower_id = $2
  AND (bs.rating IS NOT NULL OR (bs.review IS NOT NULL AND bs.review != ''))
ORDER BY bs.reviewed_at DESC NULLS LAST
LIMIT 20
`

type GetBookReviewsByFriendsParams struct {
	BookID     uuid.UUID `json:"book_id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

type GetBookReviewsByFriendsRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	Rating       pgtype.Int4        `json:"rating"`
	Review       pgtype.Text        `json:"review"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	ReviewEdited bool               `json:"review_edited"`
	Username     string             `json:"username"`
	Name         pgtype.Text        `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
}

// Reviews on a book authored by users the current viewer follows.
// $1 = book_id, $2 = viewer's user_id (follower).
func (q *Queries) GetBookReviewsByFriends(ctx context.Context, arg GetBookReviewsByFriendsParams) ([]GetBookReviewsByFriendsRow, error) {
	rows, err := q.db.Query(ctx, getBookReviewsByFriends, arg.BookID, arg.FollowerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookReviewsByFriendsRow{}
	for rows.Next() {
		var i GetBookReviewsByFriendsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Rating,
			&i.Review,
			&i.ReviewedAt,
			&i.ReviewEdited,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookshelfEntry = `-- name: GetBookshelfEntry :one
SELECT id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited FROM bookshelf WHERE user_id = $1 AND book_id = $2
`

type GetBookshelfEntryParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) GetBookshelfEntry(ctx context.Context, arg GetBookshelfEntryParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, getBookshelfEntry, arg.UserID, arg.BookID)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const getCurrentlyReading = `-- name: GetCurrentlyReading :many
SELECT
    bs.id,
    bs.user_id,
    bs.book_id,
    bs.status,
    bs.rating,
    bs.started_at,
    bs.finished_at,
    bs.current_page,
    bs.reading_velocity,
    bs.estimated_finish_date,
    bs.created_at,
    bs.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.page_count,
    b.published_date,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = 'reading'
ORDER BY bs.updated_at DESC
`

type GetCurrentlyReadingRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	BookID              uuid.UUID          `json:"book_id"`
	Status              string             `json:"status"`
	Rating              pgtype.Int4        `json:"rating"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CurrentPage         pgtype.Int4        `json:"current_page"`
	ReadingVelocity     pgtype.Float8      `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date        `json:"estimated_finish_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Title               string             `json:"title"`
	Slug                string             `json:"slug"`
	Authors             []string           `json:"authors"`
	CoverUrl            pgtype.Text        `json:"cover_url"`
	PageCount           pgtype.Int4        `json:"page_count"`
	PublishedDate       pgtype.Date        `json:"published_date"`
	Isbn13              pgtype.Text        `json:"isbn_13"`
	Description         pgtype.Text        `json:"description"`
	Categories          []string           `json:"categories"`
	Publisher           pgtype.Text        `json:"publisher"`
	Language            pgtype.Text        `json:"language"`
	Subtitle            pgtype.Text        `json:"subtitle"`
	IsbndbID            pgtype.Text        `json:"isbndb_id"`
	GoogleBooksID       pgtype.Text        `json:"google_books_id"`
	AverageRating       pgtype.Float8      `json:"average_rating"`
	RatingsCount        pgtype.Int4        `json:"ratings_count"`
}

func (q *Queries) GetCurrentlyReading(ctx context.Context, userID uuid.UUID) ([]GetCurrentlyReadingRow, error) {
	rows, err := q.db.Query(ctx, getCurrentlyReading, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCurrentlyReadingRow{}
	for rows.Next() {
		var i GetCurrentlyReadingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.Rating,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CurrentPage,
			&i.ReadingVelocity,
			&i.EstimatedFinishDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.PublishedDate,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendsReadingBook = `-- name: GetFriendsReadingBook :many
SELECT
    u.id AS user_id,
    u.username,
    u.name,
    u.avatar_url,
    bs.current_page,
    bs.started_at,
    bs.status,
    bs.updated_at
FROM follows f
JOIN bookshelf bs ON bs.user_id = f.following_id
JOIN users u ON u.id = f.following_id
WHERE f.follower_id = $1
  AND bs.book_id = $2
  AND bs.status IN ('reading', 'to-read', 'read')
ORDER BY
    CASE bs.status
        WHEN 'reading' THEN 0
        WHEN 'read' THEN 1
        ELSE 2
    END,
    bs.updated_at DESC
LIMIT 20
`

type GetFriendsReadingBookParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	BookID     uuid.UUID `json:"book_id"`
}

type GetFriendsReadingBookRow struct {
	UserID      uuid.UUID          `json:"user_id"`
	Username    string             `json:"username"`
	Name        pgtype.Text        `json:"name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CurrentPage pgtype.Int4        `json:"current_page"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Friends (people the viewer follows) who have this book on their shelf
// with status 'reading' or 'to-read', prioritised by active readers first.
// $1 = viewer's user_id (follower), $2 = book_id.
func (q *Queries) GetFriendsReadingBook(ctx context.Context, arg GetFriendsReadingBookParams) ([]GetFriendsReadingBookRow, error) {
	rows, err := q.db.Query(ctx, getFriendsReadingBook, arg.FollowerID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendsReadingBookRow{}
	for rows.Next() {
		var i GetFriendsReadingBookRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.CurrentPage,
			&i.StartedAt,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT
    bs.current_page,
    bs.reading_velocity,
    bs.estimated_finish_date,
    bs.started_at,
    bs.finished_at,
    bs.status,
    bs.updated_at,
    b.page_count AS total_pages
FROM bookshelf bs
JOIN books b ON b.id = bs.book_id
WHERE bs.user_id = $1 AND bs.book_id = $2
`

type GetReadingProgressParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

type GetReadingProgressRow struct {
	CurrentPage         pgtype.Int4        `json:"current_page"`
	ReadingVelocity     pgtype.Float8      `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date        `json:"estimated_finish_date"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	Status              string             `json:"status"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TotalPages          pgtype.Int4        `json:"total_pages"`
}

// Reading progress snapshot for a book on a single user's shelf.
func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (GetReadingProgressRow, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.BookID)
	var i GetReadingProgressRow
	err := row.Scan(
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.UpdatedAt,
		&i.TotalPages,
	)
	return i, err
}

const getUserAuthors = `-- name: GetUserAuthors :many
SELECT
    author::TEXT AS name,
    COUNT(*)::INT AS book_count,
    COALESCE(MAX(b.cover_url), '')::TEXT AS sample_cover
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
CROSS JOIN UNNEST(b.authors) AS author
WHERE bs.user_id = $1
  AND bs.status = 'read'
GROUP BY author
ORDER BY book_count DESC, name ASC
`

type GetUserAuthorsRow struct {
	Name        string `json:"name"`
	BookCount   int32  `json:"book_count"`
	SampleCover string `json:"sample_cover"`
}

func (q *Queries) GetUserAuthors(ctx context.Context, userID uuid.UUID) ([]GetUserAuthorsRow, error) {
	rows, err := q.db.Query(ctx, getUserAuthors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAuthorsRow{}
	for rows.Next() {
		var i GetUserAuthorsRow
		if err := rows.Scan(&i.Name, &i.BookCount, &i.SampleCover); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBookshelf = `-- name: GetUserBookshelf :many
SELECT b.id, b.title, b.slug, b.authors, b.isbn_13, b.google_books_id, b.metadata, b.view_count, b.like_count, b.created_at, b.updated_at, b.description, b.published_date, b.page_count, b.language, b.cover_url, b.categories, b.subtitle, b.publisher, b.isbndb_id, b.open_library_id, b.average_rating, b.ratings_count, b.preview_link, b.total_reads_count, b.total_tbr_count, b.embedding, b.embedding_text, b.description_source, b.last_accessed_at, bs.status, bs.rating, bs.finished_at, bs.created_at as added_at
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = $2
ORDER BY bs.updated_at DESC NULLS LAST, bs.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUserBookshelfParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserBookshelfRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	Authors           []string           `json:"authors"`
	Isbn13            pgtype.Text        `json:"isbn_13"`
	GoogleBooksID     pgtype.Text        `json:"google_books_id"`
	Metadata          []byte             `json:"metadata"`
	ViewCount         pgtype.Int4        `json:"view_count"`
	LikeCount         pgtype.Int4        `json:"like_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Description       pgtype.Text        `json:"description"`
	PublishedDate     pgtype.Date        `json:"published_date"`
	PageCount         pgtype.Int4        `json:"page_count"`
	Language          pgtype.Text        `json:"language"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Categories        []string           `json:"categories"`
	Subtitle          pgtype.Text        `json:"subtitle"`
	Publisher         pgtype.Text        `json:"publisher"`
	IsbndbID          pgtype.Text        `json:"isbndb_id"`
	OpenLibraryID     pgtype.Text        `json:"open_library_id"`
	AverageRating     pgtype.Float8      `json:"average_rating"`
	RatingsCount      pgtype.Int4        `json:"ratings_count"`
	PreviewLink       pgtype.Text        `json:"preview_link"`
	TotalReadsCount   pgtype.Int4        `json:"total_reads_count"`
	TotalTbrCount     pgtype.Int4        `json:"total_tbr_count"`
	Embedding         pgvector.Vector    `json:"embedding"`
	EmbeddingText     pgtype.Text        `json:"embedding_text"`
	DescriptionSource pgtype.Text        `json:"description_source"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
	Status            string             `json:"status"`
	Rating            pgtype.Int4        `json:"rating"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	AddedAt           pgtype.Timestamptz `json:"added_at"`
}

// Most-recently-touched first: a freshly added/updated book (updated_at = NOW())
// always lands at the top of its tab.
func (q *Queries) GetUserBookshelf(ctx context.Context, arg GetUserBookshelfParams) ([]GetUserBookshelfRow, error) {
	rows, err := q.db.Query(ctx, getUserBookshelf,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserBookshelfRow{}
	for rows.Next() {
		var i GetUserBookshelfRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
			&i.Status,
			&i.Rating,
			&i.FinishedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDNF = `-- name: GetUserDNF :many
SELECT
    bs.id,
    bs.user_id,
    bs.book_id,
    bs.status,
    bs.current_page,
    bs.tbr_notes,
    bs.tbr_priority,
    bs.tbr_added_at,
    bs.created_at,
    bs.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.page_count,
    b.published_date,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1
  AND bs.status = 'to-read'
  AND bs.current_page IS NOT NULL
  AND bs.current_page > 0
ORDER BY bs.updated_at DESC
`

type GetUserDNFRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	BookID        uuid.UUID          `json:"book_id"`
	Status        string             `json:"status"`
	CurrentPage   pgtype.Int4        `json:"current_page"`
	TbrNotes      pgtype.Text        `json:"tbr_notes"`
	TbrPriority   pgtype.Text        `json:"tbr_priority"`
	TbrAddedAt    pgtype.Timestamp   `json:"tbr_added_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Authors       []string           `json:"authors"`
	CoverUrl      pgtype.Text        `json:"cover_url"`
	PageCount     pgtype.Int4        `json:"page_count"`
	PublishedDate pgtype.Date        `json:"published_date"`
	Isbn13        pgtype.Text        `json:"isbn_13"`
	Description   pgtype.Text        `json:"description"`
	Categories    []string           `json:"categories"`
	Publisher     pgtype.Text        `json:"publisher"`
	Language      pgtype.Text        `json:"language"`
	Subtitle      pgtype.Text        `json:"subtitle"`
	IsbndbID      pgtype.Text        `json:"isbndb_id"`
	GoogleBooksID pgtype.Text        `json:"google_books_id"`
	AverageRating pgtype.Float8      `json:"average_rating"`
	RatingsCount  pgtype.Int4        `json:"ratings_count"`
}

func (q *Queries) GetUserDNF(ctx context.Context, userID uuid.UUID) ([]GetUserDNFRow, error) {
	rows, err := q.db.Query(ctx, getUserDNF, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserDNFRow{}
	for rows.Next() {
		var i GetUserDNFRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.CurrentPage,
			&i.TbrNotes,
			&i.TbrPriority,
			&i.TbrAddedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.PublishedDate,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReadStats = `-- name: GetUserReadStats :one
SELECT
    COUNT(*)::INT AS books_read,
    COALESCE(SUM(b.page_count) FILTER (WHERE b.page_count IS NOT NULL), 0)::INT AS pages_read
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = 'read'
`

type GetUserReadStatsRow struct {
	BooksRead int32 `json:"books_read"`
	PagesRead int32 `json:"pages_read"`
}

// Live books-read count and total pages read, computed from the shelf so the
// profile never shows the stale cached `users.books_read_count` / `total_pages_read`.
func (q *Queries) GetUserReadStats(ctx context.Context, userID uuid.UUID) (GetUserReadStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserReadStats, userID)
	var i GetUserReadStatsRow
	err := row.Scan(&i.BooksRead, &i.PagesRead)
	return i, err
}

const getUserTBR = `-- name: GetUserTBR :many
SELECT
    bs.id,
    bs.user_id,
    bs.book_id,
    bs.status,
    bs.current_page,
    bs.tbr_notes,
    bs.tbr_priority,
    bs.tbr_added_at,
    bs.created_at,
    bs.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.page_count,
    b.published_date,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = 'to-read'
ORDER BY bs.updated_at DESC NULLS LAST, bs.created_at DESC
`

type GetUserTBRRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	BookID        uuid.UUID          `json:"book_id"`
	Status        string             `json:"status"`
	CurrentPage   pgtype.Int4        `json:"current_page"`
	TbrNotes      pgtype.Text        `json:"tbr_notes"`
	TbrPriority   pgtype.Text        `json:"tbr_priority"`
	TbrAddedAt    pgtype.Timestamp   `json:"tbr_added_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Authors       []string           `json:"authors"`
	CoverUrl      pgtype.Text        `json:"cover_url"`
	PageCount     pgtype.Int4        `json:"page_count"`
	PublishedDate pgtype.Date        `json:"published_date"`
	Isbn13        pgtype.Text        `json:"isbn_13"`
	Description   pgtype.Text        `json:"description"`
	Categories    []string           `json:"categories"`
	Publisher     pgtype.Text        `json:"publisher"`
	Language      pgtype.Text        `json:"language"`
	Subtitle      pgtype.Text        `json:"subtitle"`
	IsbndbID      pgtype.Text        `json:"isbndb_id"`
	GoogleBooksID pgtype.Text        `json:"google_books_id"`
	AverageRating pgtype.Float8      `json:"average_rating"`
	RatingsCount  pgtype.Int4        `json:"ratings_count"`
}

// Most-recently-touched first so a book just marked to-read lands on top.
func (q *Queries) GetUserTBR(ctx context.Context, userID uuid.UUID) ([]GetUserTBRRow, error) {
	rows, err := q.db.Query(ctx, getUserTBR, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTBRRow{}
	for rows.Next() {
		var i GetUserTBRRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.CurrentPage,
			&i.TbrNotes,
			&i.TbrPriority,
			&i.TbrAddedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.PublishedDate,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsFinished = `-- name: MarkAsFinished :one
UPDATE bookshelf
SET
    status = 'read',
    finished_at = NOW(),
    current_page = (SELECT b.page_count FROM books b WHERE b.id = bookshelf.book_id),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type MarkAsFinishedParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) MarkAsFinished(ctx context.Context, arg MarkAsFinishedParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, markAsFinished, arg.UserID, arg.BookID)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const markAsStarted = `-- name: MarkAsStarted :one
UPDATE bookshelf
SET
    status = 'reading',
    started_at = COALESCE(started_at, NOW()),
    current_page = COALESCE($3, 0),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type MarkAsStartedParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	BookID      uuid.UUID   `json:"book_id"`
	CurrentPage pgtype.Int4 `json:"current_page"`
}

func (q *Queries) MarkAsStarted(ctx context.Context, arg MarkAsStartedParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, markAsStarted, arg.UserID, arg.BookID, arg.CurrentPage)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const removeFromBookshelf = `-- name: RemoveFromBookshelf :exec
DELETE FROM bookshelf WHERE user_id = $1 AND book_id = $2
`

type RemoveFromBookshelfParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) RemoveFromBookshelf(ctx context.Context, arg RemoveFromBookshelfParams) error {
	_, err := q.db.Exec(ctx, removeFromBookshelf, arg.UserID, arg.BookID)
	return err
}

const updateBookshelfRating = `-- name: UpdateBookshelfRating :one
UPDATE bookshelf
SET
    rating = $3,
    review = $4,
    reviewed_at = CASE
        WHEN $3::int IS NULL AND ($4::text IS NULL OR $4::text = '')
            THEN NULL
        WHEN reviewed_at IS NULL AND ($3::int IS NOT NULL OR ($4::text IS NOT NULL AND $4::text != ''))
            THEN NOW()
        ELSE reviewed_at
    END,
    review_edited = CASE
        WHEN reviewed_at IS NOT NULL AND ($3::int IS NOT NULL OR ($4::text IS NOT NULL AND $4::text != ''))
            THEN TRUE
        WHEN $3::int IS NULL AND ($4::text IS NULL OR $4::text = '')
            THEN FALSE
        ELSE review_edited
    END,
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type UpdateBookshelfRatingParams struct {
	UserID uuid.UUID   `json:"user_id"`
	BookID uuid.UUID   `json:"book_id"`
	Rating pgtype.Int4 `json:"rating"`
	Review pgtype.Text `json:"review"`
}

func (q *Queries) UpdateBookshelfRating(ctx context.Context, arg UpdateBookshelfRatingParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateBookshelfRating,
		arg.UserID,
		arg.BookID,
		arg.Rating,
		arg.Review,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const updateBookshelfStatus = `-- name: UpdateBookshelfStatus :one
UPDATE bookshelf
SET
    status = $3,
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type UpdateBookshelfStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateBookshelfStatus(ctx context.Context, arg UpdateBookshelfStatusParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateBookshelfStatus, arg.UserID, arg.BookID, arg.Status)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :one
UPDATE bookshelf
SET
    current_page = $3,
    reading_velocity = $4,
    estimated_finish_date = $5,
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type UpdateReadingProgressParams struct {
	UserID              uuid.UUID     `json:"user_id"`
	BookID              uuid.UUID     `json:"book_id"`
	CurrentPage         pgtype.Int4   `json:"current_page"`
	ReadingVelocity     pgtype.Float8 `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date   `json:"estimated_finish_date"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateReadingProgress,
		arg.UserID,
		arg.BookID,
		arg.CurrentPage,
		arg.ReadingVelocity,
		arg.EstimatedFinishDate,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}

const updateTBRNotes = `-- name: UpdateTBRNotes :one
UPDATE bookshelf
SET
    tbr_notes = $3,
    tbr_priority = $4,
    tbr_added_at = COALESCE(tbr_added_at, NOW()),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format, review, reviewed_at, review_edited
`

type UpdateTBRNotesParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	BookID      uuid.UUID   `json:"book_id"`
	TbrNotes    pgtype.Text `json:"tbr_notes"`
	TbrPriority pgtype.Text `json:"tbr_priority"`
}

func (q *Queries) UpdateTBRNotes(ctx context.Context, arg UpdateTBRNotesParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateTBRNotes,
		arg.UserID,
		arg.BookID,
		arg.TbrNotes,
		arg.TbrPriority,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
		&i.Review,
		&i.ReviewedAt,
		&i.ReviewEdited,
	)
	return i, err
}
