// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const bumpBookAccess = `-- name: BumpBookAccess :exec
UPDATE books SET last_accessed_at = NOW() WHERE id = $1
`

func (q *Queries) BumpBookAccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpBookAccess, id)
	return err
}

const cleanupStaleBooks = `-- name: CleanupStaleBooks :execrows
DELETE FROM books
WHERE last_accessed_at < NOW() - INTERVAL '15 days'
  AND id NOT IN (
      SELECT DISTINCT book_id FROM bookshelf
      UNION
      SELECT DISTINCT book_id FROM likes
  )
`

// Sliding window: deletes books whose last_accessed_at is older than 15 days,
// excluding any book referenced by bookshelf or likes.
func (q *Queries) CleanupStaleBooks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupStaleBooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, slug, authors, isbn_13, google_books_id,
    description, published_date, page_count, language, cover_url, categories,
    subtitle, publisher, isbndb_id, open_library_id, average_rating, preview_link,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (google_books_id) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    description = EXCLUDED.description,
    cover_url = EXCLUDED.cover_url,
    subtitle = EXCLUDED.subtitle,
    publisher = EXCLUDED.publisher,
    isbndb_id = EXCLUDED.isbndb_id,
    average_rating = EXCLUDED.average_rating,
    updated_at = NOW()
RETURNING id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at
`

type CreateBookParams struct {
	Title         string        `json:"title"`
	Slug          string        `json:"slug"`
	Authors       []string      `json:"authors"`
	Isbn13        pgtype.Text   `json:"isbn_13"`
	GoogleBooksID pgtype.Text   `json:"google_books_id"`
	Description   pgtype.Text   `json:"description"`
	PublishedDate pgtype.Date   `json:"published_date"`
	PageCount     pgtype.Int4   `json:"page_count"`
	Language      pgtype.Text   `json:"language"`
	CoverUrl      pgtype.Text   `json:"cover_url"`
	Categories    []string      `json:"categories"`
	Subtitle      pgtype.Text   `json:"subtitle"`
	Publisher     pgtype.Text   `json:"publisher"`
	IsbndbID      pgtype.Text   `json:"isbndb_id"`
	OpenLibraryID pgtype.Text   `json:"open_library_id"`
	AverageRating pgtype.Float8 `json:"average_rating"`
	PreviewLink   pgtype.Text   `json:"preview_link"`
	Metadata      []byte        `json:"metadata"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Slug,
		arg.Authors,
		arg.Isbn13,
		arg.GoogleBooksID,
		arg.Description,
		arg.PublishedDate,
		arg.PageCount,
		arg.Language,
		arg.CoverUrl,
		arg.Categories,
		arg.Subtitle,
		arg.Publisher,
		arg.IsbndbID,
		arg.OpenLibraryID,
		arg.AverageRating,
		arg.PreviewLink,
		arg.Metadata,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const createBookFromISBNdb = `-- name: CreateBookFromISBNdb :one
INSERT INTO books (
    title, slug, authors, isbn_13,
    description, published_date, page_count, language, cover_url, categories,
    publisher, isbndb_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (isbn_13) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    description = EXCLUDED.description,
    cover_url = EXCLUDED.cover_url,
    publisher = EXCLUDED.publisher,
    isbndb_id = EXCLUDED.isbndb_id,
    updated_at = NOW()
RETURNING id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at
`

type CreateBookFromISBNdbParams struct {
	Title         string      `json:"title"`
	Slug          string      `json:"slug"`
	Authors       []string    `json:"authors"`
	Isbn13        pgtype.Text `json:"isbn_13"`
	Description   pgtype.Text `json:"description"`
	PublishedDate pgtype.Date `json:"published_date"`
	PageCount     pgtype.Int4 `json:"page_count"`
	Language      pgtype.Text `json:"language"`
	CoverUrl      pgtype.Text `json:"cover_url"`
	Categories    []string    `json:"categories"`
	Publisher     pgtype.Text `json:"publisher"`
	IsbndbID      pgtype.Text `json:"isbndb_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateBookFromISBNdb(ctx context.Context, arg CreateBookFromISBNdbParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBookFromISBNdb,
		arg.Title,
		arg.Slug,
		arg.Authors,
		arg.Isbn13,
		arg.Description,
		arg.PublishedDate,
		arg.PageCount,
		arg.Language,
		arg.CoverUrl,
		arg.Categories,
		arg.Publisher,
		arg.IsbndbID,
		arg.Metadata,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const getBookByGoogleID = `-- name: GetBookByGoogleID :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books WHERE google_books_id = $1
`

func (q *Queries) GetBookByGoogleID(ctx context.Context, googleBooksID pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByGoogleID, googleBooksID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books WHERE isbn_13 = $1 OR isbndb_id = $1 LIMIT 1
`

func (q *Queries) GetBookByISBN(ctx context.Context, isbn13 pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByISBN, isbn13)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const getBookBySlug = `-- name: GetBookBySlug :one
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books WHERE slug = $1
`

func (q *Queries) GetBookBySlug(ctx context.Context, slug string) (Book, error) {
	row := q.db.QueryRow(ctx, getBookBySlug, slug)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Authors,
		&i.Isbn13,
		&i.GoogleBooksID,
		&i.Metadata,
		&i.ViewCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.PublishedDate,
		&i.PageCount,
		&i.Language,
		&i.CoverUrl,
		&i.Categories,
		&i.Subtitle,
		&i.Publisher,
		&i.IsbndbID,
		&i.OpenLibraryID,
		&i.AverageRating,
		&i.RatingsCount,
		&i.PreviewLink,
		&i.TotalReadsCount,
		&i.TotalTbrCount,
		&i.Embedding,
		&i.EmbeddingText,
		&i.DescriptionSource,
		&i.LastAccessedAt,
	)
	return i, err
}

const getBookEmbeddingsByIDs = `-- name: GetBookEmbeddingsByIDs :many
SELECT id::text AS id, embedding
FROM books
WHERE id::text = ANY($1::text[])
  AND embedding IS NOT NULL
`

type GetBookEmbeddingsByIDsRow struct {
	ID        string          `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetBookEmbeddingsByIDs(ctx context.Context, dollar_1 []string) ([]GetBookEmbeddingsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getBookEmbeddingsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookEmbeddingsByIDsRow{}
	for rows.Next() {
		var i GetBookEmbeddingsByIDsRow
		if err := rows.Scan(&i.ID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books
WHERE array_to_string(authors, '|') ILIKE '%' || $1 || '%'
ORDER BY view_count DESC
LIMIT $2 OFFSET $3
`

type GetBooksByAuthorParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetBooksByAuthor(ctx context.Context, arg GetBooksByAuthorParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooksByAuthor, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBooks = `-- name: GetLatestBooks :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLatestBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLatestBooks(ctx context.Context, arg GetLatestBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getLatestBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularBooks = `-- name: GetPopularBooks :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books
ORDER BY view_count DESC
LIMIT $1 OFFSET $2
`

type GetPopularBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPopularBooks(ctx context.Context, arg GetPopularBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, getPopularBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomBooks = `-- name: GetRandomBooks :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomBooks(ctx context.Context, limit int32) ([]Book, error) {
	rows, err := q.db.Query(ctx, getRandomBooks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBookViews = `-- name: IncrementBookViews :exec
UPDATE books SET view_count = view_count + 1, last_accessed_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementBookViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementBookViews, id)
	return err
}

const searchBooksInDB = `-- name: SearchBooksInDB :many
SELECT id, title, slug, authors, isbn_13, google_books_id, metadata, view_count, like_count, created_at, updated_at, description, published_date, page_count, language, cover_url, categories, subtitle, publisher, isbndb_id, open_library_id, average_rating, ratings_count, preview_link, total_reads_count, total_tbr_count, embedding, embedding_text, description_source, last_accessed_at FROM books
WHERE title ILIKE '%' || $1 || '%'
   OR $1 ILIKE ANY(authors)
ORDER BY view_count DESC
LIMIT $2 OFFSET $3
`

type SearchBooksInDBParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchBooksInDB(ctx context.Context, arg SearchBooksInDBParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooksInDB, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Embedding,
			&i.EmbeddingText,
			&i.DescriptionSource,
			&i.LastAccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vibeSearchBooks = `-- name: VibeSearchBooks :many
SELECT
  b.id,
  b.title,
  b.slug,
  b.authors,
  b.subtitle,
  b.publisher,
  b.published_date,
  b.description,
  b.page_count,
  b.categories,
  b.language,
  b.cover_url,
  b.average_rating,
  b.ratings_count,
  b.total_reads_count,
  b.total_tbr_count,
  b.google_books_id,
  b.isbndb_id,
  b.embedding,
  (1 - (b.embedding <=> $1::vector))::float8 AS similarity_score
FROM books b
WHERE b.embedding IS NOT NULL
ORDER BY b.embedding <=> $1::vector
LIMIT $2::int
`

type VibeSearchBooksParams struct {
	QueryVec pgvector.Vector `json:"query_vec"`
	Lim      int32           `json:"lim"`
}

type VibeSearchBooksRow struct {
	ID              uuid.UUID       `json:"id"`
	Title           string          `json:"title"`
	Slug            string          `json:"slug"`
	Authors         []string        `json:"authors"`
	Subtitle        pgtype.Text     `json:"subtitle"`
	Publisher       pgtype.Text     `json:"publisher"`
	PublishedDate   pgtype.Date     `json:"published_date"`
	Description     pgtype.Text     `json:"description"`
	PageCount       pgtype.Int4     `json:"page_count"`
	Categories      []string        `json:"categories"`
	Language        pgtype.Text     `json:"language"`
	CoverUrl        pgtype.Text     `json:"cover_url"`
	AverageRating   pgtype.Float8   `json:"average_rating"`
	RatingsCount    pgtype.Int4     `json:"ratings_count"`
	TotalReadsCount pgtype.Int4     `json:"total_reads_count"`
	TotalTbrCount   pgtype.Int4     `json:"total_tbr_count"`
	GoogleBooksID   pgtype.Text     `json:"google_books_id"`
	IsbndbID        pgtype.Text     `json:"isbndb_id"`
	Embedding       pgvector.Vector `json:"embedding"`
	SimilarityScore float64         `json:"similarity_score"`
}

func (q *Queries) VibeSearchBooks(ctx context.Context, arg VibeSearchBooksParams) ([]VibeSearchBooksRow, error) {
	rows, err := q.db.Query(ctx, vibeSearchBooks, arg.QueryVec, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VibeSearchBooksRow{}
	for rows.Next() {
		var i VibeSearchBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Subtitle,
			&i.Publisher,
			&i.PublishedDate,
			&i.Description,
			&i.PageCount,
			&i.Categories,
			&i.Language,
			&i.CoverUrl,
			&i.AverageRating,
			&i.RatingsCount,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.GoogleBooksID,
			&i.IsbndbID,
			&i.Embedding,
			&i.SimilarityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
