// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookshelf.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToBookshelf = `-- name: AddToBookshelf :one
INSERT INTO bookshelf (
    user_id, book_id, status, rating, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, book_id) DO UPDATE SET
    status = EXCLUDED.status,
    rating = EXCLUDED.rating,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at,
    updated_at = NOW()
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format
`

type AddToBookshelfParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	BookID     uuid.UUID          `json:"book_id"`
	Status     string             `json:"status"`
	Rating     pgtype.Int4        `json:"rating"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) AddToBookshelf(ctx context.Context, arg AddToBookshelfParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, addToBookshelf,
		arg.UserID,
		arg.BookID,
		arg.Status,
		arg.Rating,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}

const countUserBooks = `-- name: CountUserBooks :one
SELECT COUNT(*) FROM bookshelf WHERE user_id = $1 AND status = $2
`

type CountUserBooksParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) CountUserBooks(ctx context.Context, arg CountUserBooksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserBooks, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookshelfEntry = `-- name: GetBookshelfEntry :one
SELECT id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format FROM bookshelf WHERE user_id = $1 AND book_id = $2
`

type GetBookshelfEntryParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) GetBookshelfEntry(ctx context.Context, arg GetBookshelfEntryParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, getBookshelfEntry, arg.UserID, arg.BookID)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}

const getCurrentlyReading = `-- name: GetCurrentlyReading :many
SELECT
    bs.id,
    bs.user_id,
    bs.book_id,
    bs.status,
    bs.rating,
    bs.started_at,
    bs.finished_at,
    bs.current_page,
    bs.reading_velocity,
    bs.estimated_finish_date,
    bs.created_at,
    bs.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.page_count,
    b.published_date,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = 'reading'
ORDER BY bs.started_at DESC
`

type GetCurrentlyReadingRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	BookID              uuid.UUID          `json:"book_id"`
	Status              string             `json:"status"`
	Rating              pgtype.Int4        `json:"rating"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CurrentPage         pgtype.Int4        `json:"current_page"`
	ReadingVelocity     pgtype.Float8      `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date        `json:"estimated_finish_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Title               string             `json:"title"`
	Slug                string             `json:"slug"`
	Authors             []string           `json:"authors"`
	CoverUrl            pgtype.Text        `json:"cover_url"`
	PageCount           pgtype.Int4        `json:"page_count"`
	PublishedDate       pgtype.Date        `json:"published_date"`
	Isbn13              pgtype.Text        `json:"isbn_13"`
	Description         pgtype.Text        `json:"description"`
	Categories          []string           `json:"categories"`
	Publisher           pgtype.Text        `json:"publisher"`
	Language            pgtype.Text        `json:"language"`
	Subtitle            pgtype.Text        `json:"subtitle"`
	IsbndbID            pgtype.Text        `json:"isbndb_id"`
	GoogleBooksID       pgtype.Text        `json:"google_books_id"`
	AverageRating       pgtype.Float8      `json:"average_rating"`
	RatingsCount        pgtype.Int4        `json:"ratings_count"`
}

func (q *Queries) GetCurrentlyReading(ctx context.Context, userID uuid.UUID) ([]GetCurrentlyReadingRow, error) {
	rows, err := q.db.Query(ctx, getCurrentlyReading, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCurrentlyReadingRow{}
	for rows.Next() {
		var i GetCurrentlyReadingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.Rating,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CurrentPage,
			&i.ReadingVelocity,
			&i.EstimatedFinishDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.PublishedDate,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBookshelf = `-- name: GetUserBookshelf :many
SELECT b.id, b.title, b.slug, b.authors, b.isbn_13, b.google_books_id, b.metadata, b.view_count, b.like_count, b.created_at, b.updated_at, b.description, b.published_date, b.page_count, b.language, b.cover_url, b.categories, b.subtitle, b.publisher, b.isbndb_id, b.open_library_id, b.average_rating, b.ratings_count, b.preview_link, b.total_reads_count, b.total_tbr_count, bs.status, bs.rating, bs.finished_at, bs.created_at as added_at
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = $2
ORDER BY bs.finished_at DESC NULLS LAST, bs.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUserBookshelfParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserBookshelfRow struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Authors         []string           `json:"authors"`
	Isbn13          pgtype.Text        `json:"isbn_13"`
	GoogleBooksID   pgtype.Text        `json:"google_books_id"`
	Metadata        []byte             `json:"metadata"`
	ViewCount       pgtype.Int4        `json:"view_count"`
	LikeCount       pgtype.Int4        `json:"like_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Description     pgtype.Text        `json:"description"`
	PublishedDate   pgtype.Date        `json:"published_date"`
	PageCount       pgtype.Int4        `json:"page_count"`
	Language        pgtype.Text        `json:"language"`
	CoverUrl        pgtype.Text        `json:"cover_url"`
	Categories      []string           `json:"categories"`
	Subtitle        pgtype.Text        `json:"subtitle"`
	Publisher       pgtype.Text        `json:"publisher"`
	IsbndbID        pgtype.Text        `json:"isbndb_id"`
	OpenLibraryID   pgtype.Text        `json:"open_library_id"`
	AverageRating   pgtype.Float8      `json:"average_rating"`
	RatingsCount    pgtype.Int4        `json:"ratings_count"`
	PreviewLink     pgtype.Text        `json:"preview_link"`
	TotalReadsCount pgtype.Int4        `json:"total_reads_count"`
	TotalTbrCount   pgtype.Int4        `json:"total_tbr_count"`
	Status          string             `json:"status"`
	Rating          pgtype.Int4        `json:"rating"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) GetUserBookshelf(ctx context.Context, arg GetUserBookshelfParams) ([]GetUserBookshelfRow, error) {
	rows, err := q.db.Query(ctx, getUserBookshelf,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserBookshelfRow{}
	for rows.Next() {
		var i GetUserBookshelfRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.Subtitle,
			&i.Publisher,
			&i.IsbndbID,
			&i.OpenLibraryID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
			&i.TotalReadsCount,
			&i.TotalTbrCount,
			&i.Status,
			&i.Rating,
			&i.FinishedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTBR = `-- name: GetUserTBR :many
SELECT
    bs.id,
    bs.user_id,
    bs.book_id,
    bs.status,
    bs.current_page,
    bs.tbr_notes,
    bs.tbr_priority,
    bs.tbr_added_at,
    bs.created_at,
    bs.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.page_count,
    b.published_date,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM bookshelf bs
JOIN books b ON bs.book_id = b.id
WHERE bs.user_id = $1 AND bs.status = 'to-read'
ORDER BY bs.tbr_added_at DESC NULLS LAST, bs.created_at DESC
`

type GetUserTBRRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	BookID        uuid.UUID          `json:"book_id"`
	Status        string             `json:"status"`
	CurrentPage   pgtype.Int4        `json:"current_page"`
	TbrNotes      pgtype.Text        `json:"tbr_notes"`
	TbrPriority   pgtype.Text        `json:"tbr_priority"`
	TbrAddedAt    pgtype.Timestamp   `json:"tbr_added_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Authors       []string           `json:"authors"`
	CoverUrl      pgtype.Text        `json:"cover_url"`
	PageCount     pgtype.Int4        `json:"page_count"`
	PublishedDate pgtype.Date        `json:"published_date"`
	Isbn13        pgtype.Text        `json:"isbn_13"`
	Description   pgtype.Text        `json:"description"`
	Categories    []string           `json:"categories"`
	Publisher     pgtype.Text        `json:"publisher"`
	Language      pgtype.Text        `json:"language"`
	Subtitle      pgtype.Text        `json:"subtitle"`
	IsbndbID      pgtype.Text        `json:"isbndb_id"`
	GoogleBooksID pgtype.Text        `json:"google_books_id"`
	AverageRating pgtype.Float8      `json:"average_rating"`
	RatingsCount  pgtype.Int4        `json:"ratings_count"`
}

func (q *Queries) GetUserTBR(ctx context.Context, userID uuid.UUID) ([]GetUserTBRRow, error) {
	rows, err := q.db.Query(ctx, getUserTBR, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserTBRRow{}
	for rows.Next() {
		var i GetUserTBRRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Status,
			&i.CurrentPage,
			&i.TbrNotes,
			&i.TbrPriority,
			&i.TbrAddedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.PublishedDate,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsFinished = `-- name: MarkAsFinished :one
UPDATE bookshelf
SET
    status = 'read',
    finished_at = NOW(),
    current_page = (SELECT b.page_count FROM books b WHERE b.id = bookshelf.book_id),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format
`

type MarkAsFinishedParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) MarkAsFinished(ctx context.Context, arg MarkAsFinishedParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, markAsFinished, arg.UserID, arg.BookID)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}

const markAsStarted = `-- name: MarkAsStarted :one
UPDATE bookshelf
SET
    status = 'reading',
    started_at = COALESCE(started_at, NOW()),
    current_page = COALESCE($3, 0),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format
`

type MarkAsStartedParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	BookID      uuid.UUID   `json:"book_id"`
	CurrentPage pgtype.Int4 `json:"current_page"`
}

func (q *Queries) MarkAsStarted(ctx context.Context, arg MarkAsStartedParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, markAsStarted, arg.UserID, arg.BookID, arg.CurrentPage)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}

const removeFromBookshelf = `-- name: RemoveFromBookshelf :exec
DELETE FROM bookshelf WHERE user_id = $1 AND book_id = $2
`

type RemoveFromBookshelfParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) RemoveFromBookshelf(ctx context.Context, arg RemoveFromBookshelfParams) error {
	_, err := q.db.Exec(ctx, removeFromBookshelf, arg.UserID, arg.BookID)
	return err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :one
UPDATE bookshelf
SET
    current_page = $3,
    reading_velocity = $4,
    estimated_finish_date = $5,
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format
`

type UpdateReadingProgressParams struct {
	UserID              uuid.UUID     `json:"user_id"`
	BookID              uuid.UUID     `json:"book_id"`
	CurrentPage         pgtype.Int4   `json:"current_page"`
	ReadingVelocity     pgtype.Float8 `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date   `json:"estimated_finish_date"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateReadingProgress,
		arg.UserID,
		arg.BookID,
		arg.CurrentPage,
		arg.ReadingVelocity,
		arg.EstimatedFinishDate,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}

const updateTBRNotes = `-- name: UpdateTBRNotes :one
UPDATE bookshelf
SET
    tbr_notes = $3,
    tbr_priority = $4,
    tbr_added_at = COALESCE(tbr_added_at, NOW()),
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING id, user_id, book_id, status, rating, started_at, finished_at, created_at, updated_at, tbr_notes, tbr_priority, tbr_added_at, current_page, reading_velocity, estimated_finish_date, notes, format
`

type UpdateTBRNotesParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	BookID      uuid.UUID   `json:"book_id"`
	TbrNotes    pgtype.Text `json:"tbr_notes"`
	TbrPriority pgtype.Text `json:"tbr_priority"`
}

func (q *Queries) UpdateTBRNotes(ctx context.Context, arg UpdateTBRNotesParams) (Bookshelf, error) {
	row := q.db.QueryRow(ctx, updateTBRNotes,
		arg.UserID,
		arg.BookID,
		arg.TbrNotes,
		arg.TbrPriority,
	)
	var i Bookshelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TbrNotes,
		&i.TbrPriority,
		&i.TbrAddedAt,
		&i.CurrentPage,
		&i.ReadingVelocity,
		&i.EstimatedFinishDate,
		&i.Notes,
		&i.Format,
	)
	return i, err
}
