// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE user_id = $1 AND token = $2
`

type DeleteDeviceTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

// Logout path. Scoped to the caller so one user cannot deregister another's device.
func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.UserID, arg.Token)
	return err
}

const deleteDeviceTokenByToken = `-- name: DeleteDeviceTokenByToken :exec
DELETE FROM device_tokens
WHERE token = $1
`

// Provider-rejection path (FCM UNREGISTERED, APNs 410 Unregistered). The token
// is dead regardless of who owns it, so this is intentionally unscoped.
func (q *Queries) DeleteDeviceTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenByToken, token)
	return err
}

const deleteStaleDeviceTokens = `-- name: DeleteStaleDeviceTokens :exec
DELETE FROM device_tokens
WHERE updated_at < $1
`

func (q *Queries) DeleteStaleDeviceTokens(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteStaleDeviceTokens, updatedAt)
	return err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, platform, token, created_at, updated_at FROM device_tokens
WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, platform, token)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET user_id    = EXCLUDED.user_id,
    platform   = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, platform, token, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Platform string    `json:"platform"`
	Token    string    `json:"token"`
}

// Conflict target is `token` alone: a push token belongs to a device, so when a
// different account signs in on that device the row must change hands rather
// than accumulate a second owner. See migrations/000036 for the full rationale.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Platform, arg.Token)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
