// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const checkEntryLiked = `-- name: CheckEntryLiked :one
SELECT EXISTS(
    SELECT 1 FROM diary_entry_likes
    WHERE user_id = $1 AND entry_id = $2
)
`

type CheckEntryLikedParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EntryID uuid.UUID `json:"entry_id"`
}

func (q *Queries) CheckEntryLiked(ctx context.Context, arg CheckEntryLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEntryLiked, arg.UserID, arg.EntryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEntryOwnership = `-- name: CheckEntryOwnership :one
SELECT user_id FROM diary_entries
WHERE id = $1
`

func (q *Queries) CheckEntryOwnership(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkEntryOwnership, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const countEntryLikes = `-- name: CountEntryLikes :one
SELECT COUNT(*) FROM diary_entry_likes
WHERE entry_id = $1
`

func (q *Queries) CountEntryLikes(ctx context.Context, entryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEntryLikes, entryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserDiaryEntries = `-- name: CountUserDiaryEntries :one
SELECT COUNT(*) FROM diary_entries
WHERE user_id = $1
`

func (q *Queries) CountUserDiaryEntries(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDiaryEntries, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiaryEntry = `-- name: CreateDiaryEntry :one
INSERT INTO diary_entries (user_id, book_id, title, content, is_private, rating)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text
`

type CreateDiaryEntryParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	BookID    pgtype.UUID `json:"book_id"`
	Title     pgtype.Text `json:"title"`
	Content   string      `json:"content"`
	IsPrivate bool        `json:"is_private"`
	Rating    pgtype.Int4 `json:"rating"`
}

func (q *Queries) CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, createDiaryEntry,
		arg.UserID,
		arg.BookID,
		arg.Title,
		arg.Content,
		arg.IsPrivate,
		arg.Rating,
	)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
	)
	return i, err
}

const decrementUserDiaryCount = `-- name: DecrementUserDiaryCount :exec
UPDATE users
SET diary_entries_count = GREATEST(diary_entries_count - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementUserDiaryCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementUserDiaryCount, id)
	return err
}

const deleteDiaryEntry = `-- name: DeleteDiaryEntry :exec
DELETE FROM diary_entries
WHERE id = $1
`

func (q *Queries) DeleteDiaryEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiaryEntry, id)
	return err
}

const getBookDiaryEntries = `-- name: GetBookDiaryEntries :many
SELECT
    de.id,
    de.user_id,
    de.book_id,
    de.title,
    de.content,
    de.is_private,
    de.rating,
    de.created_at,
    de.updated_at,
    u.username,
    u.name,
    u.avatar_url
FROM diary_entries de
JOIN users u ON de.user_id = u.id
WHERE de.book_id = $1 AND de.is_private = false
  AND NOT EXISTS (
      SELECT 1 FROM blocks bl
      WHERE (bl.blocker_id = $2 AND bl.blocked_id = de.user_id)
         OR (bl.blocker_id = de.user_id AND bl.blocked_id = $2)
  )
ORDER BY de.created_at DESC
LIMIT $4 OFFSET $3
`

type GetBookDiaryEntriesParams struct {
	BookID   pgtype.UUID `json:"book_id"`
	ViewerID uuid.UUID   `json:"viewer_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

type GetBookDiaryEntriesRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	BookID    pgtype.UUID      `json:"book_id"`
	Title     pgtype.Text      `json:"title"`
	Content   string           `json:"content"`
	IsPrivate bool             `json:"is_private"`
	Rating    pgtype.Int4      `json:"rating"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Username  string           `json:"username"`
	Name      pgtype.Text      `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
}

func (q *Queries) GetBookDiaryEntries(ctx context.Context, arg GetBookDiaryEntriesParams) ([]GetBookDiaryEntriesRow, error) {
	rows, err := q.db.Query(ctx, getBookDiaryEntries,
		arg.BookID,
		arg.ViewerID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookDiaryEntriesRow{}
	for rows.Next() {
		var i GetBookDiaryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Content,
			&i.IsPrivate,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryEmbeddingsForUser = `-- name: GetDiaryEmbeddingsForUser :many
SELECT id, embedding_text, embedding
FROM diary_entries
WHERE user_id = $1
  AND embedding IS NOT NULL
ORDER BY created_at DESC
LIMIT 50
`

type GetDiaryEmbeddingsForUserRow struct {
	ID            uuid.UUID       `json:"id"`
	EmbeddingText pgtype.Text     `json:"embedding_text"`
	Embedding     pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetDiaryEmbeddingsForUser(ctx context.Context, userID uuid.UUID) ([]GetDiaryEmbeddingsForUserRow, error) {
	rows, err := q.db.Query(ctx, getDiaryEmbeddingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiaryEmbeddingsForUserRow{}
	for rows.Next() {
		var i GetDiaryEmbeddingsForUserRow
		if err := rows.Scan(&i.ID, &i.EmbeddingText, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryEntriesWithoutEmbedding = `-- name: GetDiaryEntriesWithoutEmbedding :many
SELECT
    de.id,
    de.user_id,
    de.content,
    de.embedding_text,
    b.title   AS book_title,
    b.authors AS book_authors
FROM diary_entries de
LEFT JOIN books b ON de.book_id = b.id
WHERE de.embedding IS NULL
ORDER BY de.created_at DESC
`

type GetDiaryEntriesWithoutEmbeddingRow struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Content       string      `json:"content"`
	EmbeddingText pgtype.Text `json:"embedding_text"`
	BookTitle     pgtype.Text `json:"book_title"`
	BookAuthors   []string    `json:"book_authors"`
}

func (q *Queries) GetDiaryEntriesWithoutEmbedding(ctx context.Context) ([]GetDiaryEntriesWithoutEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, getDiaryEntriesWithoutEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiaryEntriesWithoutEmbeddingRow{}
	for rows.Next() {
		var i GetDiaryEntriesWithoutEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.EmbeddingText,
			&i.BookTitle,
			&i.BookAuthors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryEntryByID = `-- name: GetDiaryEntryByID :one
SELECT id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text FROM diary_entries
WHERE id = $1
`

func (q *Queries) GetDiaryEntryByID(ctx context.Context, id uuid.UUID) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, getDiaryEntryByID, id)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
	)
	return i, err
}

const getEntryLikes = `-- name: GetEntryLikes :many
SELECT
    del.id,
    del.user_id,
    del.entry_id,
    del.created_at,
    u.username,
    u.name,
    u.avatar_url
FROM diary_entry_likes del
JOIN users u ON del.user_id = u.id
WHERE del.entry_id = $1
ORDER BY del.created_at DESC
`

type GetEntryLikesRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	EntryID   uuid.UUID        `json:"entry_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Username  string           `json:"username"`
	Name      pgtype.Text      `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
}

func (q *Queries) GetEntryLikes(ctx context.Context, entryID uuid.UUID) ([]GetEntryLikesRow, error) {
	rows, err := q.db.Query(ctx, getEntryLikes, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntryLikesRow{}
	for rows.Next() {
		var i GetEntryLikesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDiaryEntries = `-- name: GetUserDiaryEntries :many
SELECT
    de.id,
    de.user_id,
    de.book_id,
    de.title,
    de.content,
    de.is_private,
    de.rating,
    de.created_at,
    de.updated_at,
    b.title as book_title,
    b.slug as book_slug,
    b.authors as book_authors,
    b.cover_url as book_cover_url
FROM diary_entries de
LEFT JOIN books b ON de.book_id = b.id
WHERE de.user_id = $1
  AND (de.is_private = false OR de.user_id = $2)
ORDER BY de.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUserDiaryEntriesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetUserDiaryEntriesRow struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       pgtype.UUID      `json:"book_id"`
	Title        pgtype.Text      `json:"title"`
	Content      string           `json:"content"`
	IsPrivate    bool             `json:"is_private"`
	Rating       pgtype.Int4      `json:"rating"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	BookTitle    pgtype.Text      `json:"book_title"`
	BookSlug     pgtype.Text      `json:"book_slug"`
	BookAuthors  []string         `json:"book_authors"`
	BookCoverUrl pgtype.Text      `json:"book_cover_url"`
}

func (q *Queries) GetUserDiaryEntries(ctx context.Context, arg GetUserDiaryEntriesParams) ([]GetUserDiaryEntriesRow, error) {
	rows, err := q.db.Query(ctx, getUserDiaryEntries,
		arg.UserID,
		arg.UserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserDiaryEntriesRow{}
	for rows.Next() {
		var i GetUserDiaryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Content,
			&i.IsPrivate,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookTitle,
			&i.BookSlug,
			&i.BookAuthors,
			&i.BookCoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserDiaryCount = `-- name: IncrementUserDiaryCount :exec
UPDATE users
SET diary_entries_count = diary_entries_count + 1
WHERE id = $1
`

func (q *Queries) IncrementUserDiaryCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserDiaryCount, id)
	return err
}

const likeDiaryEntry = `-- name: LikeDiaryEntry :one

INSERT INTO diary_entry_likes (user_id, entry_id)
VALUES ($1, $2)
RETURNING id, user_id, entry_id, created_at
`

type LikeDiaryEntryParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EntryID uuid.UUID `json:"entry_id"`
}

// Likes
func (q *Queries) LikeDiaryEntry(ctx context.Context, arg LikeDiaryEntryParams) (DiaryEntryLike, error) {
	row := q.db.QueryRow(ctx, likeDiaryEntry, arg.UserID, arg.EntryID)
	var i DiaryEntryLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.CreatedAt,
	)
	return i, err
}

const unlikeDiaryEntry = `-- name: UnlikeDiaryEntry :exec
DELETE FROM diary_entry_likes
WHERE user_id = $1 AND entry_id = $2
`

type UnlikeDiaryEntryParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EntryID uuid.UUID `json:"entry_id"`
}

func (q *Queries) UnlikeDiaryEntry(ctx context.Context, arg UnlikeDiaryEntryParams) error {
	_, err := q.db.Exec(ctx, unlikeDiaryEntry, arg.UserID, arg.EntryID)
	return err
}

const updateDiaryEntry = `-- name: UpdateDiaryEntry :one
UPDATE diary_entries
SET
    title = $2,
    content = $3,
    is_private = $4,
    rating = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text
`

type UpdateDiaryEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	Title     pgtype.Text `json:"title"`
	Content   string      `json:"content"`
	IsPrivate bool        `json:"is_private"`
	Rating    pgtype.Int4 `json:"rating"`
}

func (q *Queries) UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, updateDiaryEntry,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPrivate,
		arg.Rating,
	)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
	)
	return i, err
}

const updateDiaryEntryEmbedding = `-- name: UpdateDiaryEntryEmbedding :exec
UPDATE diary_entries
SET embedding = $2::vector, embedding_text = $3
WHERE id = $1
`

type UpdateDiaryEntryEmbeddingParams struct {
	ID            uuid.UUID       `json:"id"`
	Column2       pgvector.Vector `json:"column_2"`
	EmbeddingText pgtype.Text     `json:"embedding_text"`
}

func (q *Queries) UpdateDiaryEntryEmbedding(ctx context.Context, arg UpdateDiaryEntryEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateDiaryEntryEmbedding, arg.ID, arg.Column2, arg.EmbeddingText)
	return err
}
