// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToFavorites = `-- name: AddToFavorites :one
INSERT INTO favorites (user_id, book_id, display_order, favorite_note)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, book_id, display_order, favorite_note, created_at, updated_at
`

type AddToFavoritesParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	BookID       uuid.UUID   `json:"book_id"`
	DisplayOrder int32       `json:"display_order"`
	FavoriteNote pgtype.Text `json:"favorite_note"`
}

func (q *Queries) AddToFavorites(ctx context.Context, arg AddToFavoritesParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addToFavorites,
		arg.UserID,
		arg.BookID,
		arg.DisplayOrder,
		arg.FavoriteNote,
	)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.DisplayOrder,
		&i.FavoriteNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkFavoriteExists = `-- name: CheckFavoriteExists :one
SELECT EXISTS(
    SELECT 1 FROM favorites
    WHERE user_id = $1 AND book_id = $2
)
`

type CheckFavoriteExistsParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) CheckFavoriteExists(ctx context.Context, arg CheckFavoriteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFavoriteExists, arg.UserID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserFavorites = `-- name: CountUserFavorites :one
SELECT COUNT(*) FROM favorites
WHERE user_id = $1
`

func (q *Queries) CountUserFavorites(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserFavorites, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decrementUserFavoritesCount = `-- name: DecrementUserFavoritesCount :exec
UPDATE users SET favorites_count = GREATEST(favorites_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementUserFavoritesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementUserFavoritesCount, id)
	return err
}

const getFavoriteByUserAndBook = `-- name: GetFavoriteByUserAndBook :one
SELECT id, user_id, book_id, display_order, favorite_note, created_at, updated_at FROM favorites
WHERE user_id = $1 AND book_id = $2
`

type GetFavoriteByUserAndBookParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) GetFavoriteByUserAndBook(ctx context.Context, arg GetFavoriteByUserAndBookParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, getFavoriteByUserAndBook, arg.UserID, arg.BookID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.DisplayOrder,
		&i.FavoriteNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT
    f.id,
    f.user_id,
    f.book_id,
    f.display_order,
    f.favorite_note,
    f.created_at,
    f.updated_at,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.published_date,
    b.page_count,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count,
    b.preview_link
FROM favorites f
JOIN books b ON f.book_id = b.id
WHERE f.user_id = $1
ORDER BY f.display_order ASC
`

type GetUserFavoritesRow struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	BookID        uuid.UUID        `json:"book_id"`
	DisplayOrder  int32            `json:"display_order"`
	FavoriteNote  pgtype.Text      `json:"favorite_note"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Title         string           `json:"title"`
	Slug          string           `json:"slug"`
	Authors       []string         `json:"authors"`
	CoverUrl      pgtype.Text      `json:"cover_url"`
	PublishedDate pgtype.Date      `json:"published_date"`
	PageCount     pgtype.Int4      `json:"page_count"`
	Isbn13        pgtype.Text      `json:"isbn_13"`
	Description   pgtype.Text      `json:"description"`
	Categories    []string         `json:"categories"`
	Publisher     pgtype.Text      `json:"publisher"`
	Language      pgtype.Text      `json:"language"`
	Subtitle      pgtype.Text      `json:"subtitle"`
	IsbndbID      pgtype.Text      `json:"isbndb_id"`
	GoogleBooksID pgtype.Text      `json:"google_books_id"`
	AverageRating pgtype.Float8    `json:"average_rating"`
	RatingsCount  pgtype.Int4      `json:"ratings_count"`
	PreviewLink   pgtype.Text      `json:"preview_link"`
}

func (q *Queries) GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]GetUserFavoritesRow, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserFavoritesRow{}
	for rows.Next() {
		var i GetUserFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.DisplayOrder,
			&i.FavoriteNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PublishedDate,
			&i.PageCount,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
			&i.PreviewLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserFavoritesCount = `-- name: IncrementUserFavoritesCount :exec
UPDATE users SET favorites_count = favorites_count + 1 WHERE id = $1
`

func (q *Queries) IncrementUserFavoritesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserFavoritesCount, id)
	return err
}

const removeFromFavorites = `-- name: RemoveFromFavorites :exec
DELETE FROM favorites
WHERE user_id = $1 AND book_id = $2
`

type RemoveFromFavoritesParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) RemoveFromFavorites(ctx context.Context, arg RemoveFromFavoritesParams) error {
	_, err := q.db.Exec(ctx, removeFromFavorites, arg.UserID, arg.BookID)
	return err
}

const reorderFavorites = `-- name: ReorderFavorites :exec
UPDATE favorites
SET display_order = $2, updated_at = NOW()
WHERE id = $1
`

type ReorderFavoritesParams struct {
	ID           uuid.UUID `json:"id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) ReorderFavorites(ctx context.Context, arg ReorderFavoritesParams) error {
	_, err := q.db.Exec(ctx, reorderFavorites, arg.ID, arg.DisplayOrder)
	return err
}

const updateFavoriteNote = `-- name: UpdateFavoriteNote :one
UPDATE favorites
SET favorite_note = $2, updated_at = NOW()
WHERE user_id = $1 AND book_id = $3
RETURNING id, user_id, book_id, display_order, favorite_note, created_at, updated_at
`

type UpdateFavoriteNoteParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	FavoriteNote pgtype.Text `json:"favorite_note"`
	BookID       uuid.UUID   `json:"book_id"`
}

func (q *Queries) UpdateFavoriteNote(ctx context.Context, arg UpdateFavoriteNoteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, updateFavoriteNote, arg.UserID, arg.FavoriteNote, arg.BookID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.DisplayOrder,
		&i.FavoriteNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
