// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkFollowing = `-- name: CheckFollowing :one
SELECT EXISTS(SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2)
`

type CheckFollowingParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) CheckFollowing(ctx context.Context, arg CheckFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE following_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :one
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, following_id) DO NOTHING
RETURNING id, follower_id, following_id, created_at
`

type FollowUserParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error) {
	row := q.db.QueryRow(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var i Follow
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.username, u.email, u.password_hash, u.name, u.avatar_url, u.bio, u.pronouns, u.is_public, u.favorite_genres, u.settings, u.followers_count, u.following_count, u.books_read_count, u.created_at, u.updated_at, u.last_active, u.deleted_at, u.mongo_id, u.birthday, u.gender, u.links, u.total_pages_read, u.favorites_count, u.lists_count FROM follows f
JOIN users u ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	FollowingID uuid.UUID `json:"following_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
			&i.Pronouns,
			&i.IsPublic,
			&i.FavoriteGenres,
			&i.Settings,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.BooksReadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActive,
			&i.DeletedAt,
			&i.MongoID,
			&i.Birthday,
			&i.Gender,
			&i.Links,
			&i.TotalPagesRead,
			&i.FavoritesCount,
			&i.ListsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.username, u.email, u.password_hash, u.name, u.avatar_url, u.bio, u.pronouns, u.is_public, u.favorite_genres, u.settings, u.followers_count, u.following_count, u.books_read_count, u.created_at, u.updated_at, u.last_active, u.deleted_at, u.mongo_id, u.birthday, u.gender, u.links, u.total_pages_read, u.favorites_count, u.lists_count FROM follows f
JOIN users u ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
			&i.Pronouns,
			&i.IsPublic,
			&i.FavoriteGenres,
			&i.Settings,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.BooksReadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActive,
			&i.DeletedAt,
			&i.MongoID,
			&i.Birthday,
			&i.Gender,
			&i.Links,
			&i.TotalPagesRead,
			&i.FavoritesCount,
			&i.ListsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
