// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addXP = `-- name: AddXP :exec

UPDATE users
SET
  total_xp = total_xp + $2,
  level = CASE
    -- Level 31+: 12000+ XP (500 XP per level)
    WHEN (total_xp + $2) >= 12000 THEN 31 + ((total_xp + $2 - 12000) / 500)
    -- Level 26-30: 8000-12000 XP (800 XP per level)
    WHEN (total_xp + $2) >= 8000 THEN 26 + ((total_xp + $2 - 8000) / 800)
    -- Level 21-25: 5000-8000 XP (600 XP per level)
    WHEN (total_xp + $2) >= 5000 THEN 21 + ((total_xp + $2 - 5000) / 600)
    -- Level 16-20: 3000-5000 XP (400 XP per level)
    WHEN (total_xp + $2) >= 3000 THEN 16 + ((total_xp + $2 - 3000) / 400)
    -- Level 11-15: 1500-3000 XP (300 XP per level)
    WHEN (total_xp + $2) >= 1500 THEN 11 + ((total_xp + $2 - 1500) / 300)
    -- Level 6-10: 500-1500 XP (200 XP per level)
    WHEN (total_xp + $2) >= 500 THEN 6 + ((total_xp + $2 - 500) / 200)
    -- Level 1-5: 0-500 XP (100 XP per level)
    ELSE 1 + ((total_xp + $2) / 100)
  END,
  last_activity_date = CURRENT_DATE
WHERE id = $1
`

type AddXPParams struct {
	ID      uuid.UUID   `json:"id"`
	TotalXp pgtype.Int4 `json:"total_xp"`
}

// ============================================================================
// USER XP AND LEVEL MANAGEMENT
// ============================================================================
func (q *Queries) AddXP(ctx context.Context, arg AddXPParams) error {
	_, err := q.db.Exec(ctx, addXP, arg.ID, arg.TotalXp)
	return err
}

const getFriendsLeaderboard = `-- name: GetFriendsLeaderboard :many

SELECT ls.user_id, ls.username, ls.books_read, ls.pages_read, ls.diary_entries, ls.genres_explored, ls.total_xp, ls.level, ls.current_streak, ls.books_rank, ls.pages_rank, ls.diary_rank, ls.genres_rank, ls.xp_rank, ls.streak_rank, ls.updated_at
FROM leaderboard_stats ls
INNER JOIN follows f ON ls.user_id = f.followed_id
WHERE f.follower_id = $1
  AND ls.total_xp > 0
ORDER BY ls.total_xp DESC, ls.books_read DESC
LIMIT $2
`

type GetFriendsLeaderboardParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
}

// ============================================================================
// LEADERBOARD QUERIES
// ============================================================================
func (q *Queries) GetFriendsLeaderboard(ctx context.Context, arg GetFriendsLeaderboardParams) ([]LeaderboardStat, error) {
	rows, err := q.db.Query(ctx, getFriendsLeaderboard, arg.FollowerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardStat{}
	for rows.Next() {
		var i LeaderboardStat
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.BooksRead,
			&i.PagesRead,
			&i.DiaryEntries,
			&i.GenresExplored,
			&i.TotalXp,
			&i.Level,
			&i.CurrentStreak,
			&i.BooksRank,
			&i.PagesRank,
			&i.DiaryRank,
			&i.GenresRank,
			&i.XpRank,
			&i.StreakRank,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalLeaderboard = `-- name: GetGlobalLeaderboard :many
SELECT ls.user_id, ls.username, ls.books_read, ls.pages_read, ls.diary_entries, ls.genres_explored, ls.total_xp, ls.level, ls.current_streak, ls.books_rank, ls.pages_rank, ls.diary_rank, ls.genres_rank, ls.xp_rank, ls.streak_rank, ls.updated_at
FROM leaderboard_stats ls
INNER JOIN users u ON ls.user_id = u.id
WHERE u.show_on_leaderboard = true
  AND ls.total_xp > 0
ORDER BY ls.total_xp DESC, ls.books_read DESC
LIMIT $1
`

func (q *Queries) GetGlobalLeaderboard(ctx context.Context, limit int32) ([]LeaderboardStat, error) {
	rows, err := q.db.Query(ctx, getGlobalLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardStat{}
	for rows.Next() {
		var i LeaderboardStat
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.BooksRead,
			&i.PagesRead,
			&i.DiaryEntries,
			&i.GenresExplored,
			&i.TotalXp,
			&i.Level,
			&i.CurrentStreak,
			&i.BooksRank,
			&i.PagesRank,
			&i.DiaryRank,
			&i.GenresRank,
			&i.XpRank,
			&i.StreakRank,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardByDimension = `-- name: GetLeaderboardByDimension :many
SELECT ls.user_id, ls.username, ls.books_read, ls.pages_read, ls.diary_entries, ls.genres_explored, ls.total_xp, ls.level, ls.current_streak, ls.books_rank, ls.pages_rank, ls.diary_rank, ls.genres_rank, ls.xp_rank, ls.streak_rank, ls.updated_at
FROM leaderboard_stats ls
INNER JOIN users u ON ls.user_id = u.id
WHERE u.show_on_leaderboard = true
ORDER BY
  CASE $1::text
    WHEN 'books' THEN ls.books_read
    WHEN 'pages' THEN ls.pages_read
    WHEN 'diary' THEN ls.diary_entries
    WHEN 'genres' THEN ls.genres_explored
    WHEN 'streak' THEN ls.current_streak
    ELSE ls.total_xp
  END DESC,
  ls.total_xp DESC
LIMIT $2
`

type GetLeaderboardByDimensionParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetLeaderboardByDimension(ctx context.Context, arg GetLeaderboardByDimensionParams) ([]LeaderboardStat, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByDimension, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardStat{}
	for rows.Next() {
		var i LeaderboardStat
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.BooksRead,
			&i.PagesRead,
			&i.DiaryEntries,
			&i.GenresExplored,
			&i.TotalXp,
			&i.Level,
			&i.CurrentStreak,
			&i.BooksRank,
			&i.PagesRank,
			&i.DiaryRank,
			&i.GenresRank,
			&i.XpRank,
			&i.StreakRank,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLeaderboardStats = `-- name: GetUserLeaderboardStats :one

SELECT user_id, username, books_read, pages_read, diary_entries, genres_explored, total_xp, level, current_streak, books_rank, pages_rank, diary_rank, genres_rank, xp_rank, streak_rank, updated_at FROM leaderboard_stats WHERE user_id = $1
`

// ============================================================================
// LEADERBOARD STATS QUERIES
// ============================================================================
func (q *Queries) GetUserLeaderboardStats(ctx context.Context, userID uuid.UUID) (LeaderboardStat, error) {
	row := q.db.QueryRow(ctx, getUserLeaderboardStats, userID)
	var i LeaderboardStat
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.BooksRead,
		&i.PagesRead,
		&i.DiaryEntries,
		&i.GenresExplored,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.BooksRank,
		&i.PagesRank,
		&i.DiaryRank,
		&i.GenresRank,
		&i.XpRank,
		&i.StreakRank,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserXP = `-- name: GetUserXP :one
SELECT id, username, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard
FROM users
WHERE id = $1
`

type GetUserXPRow struct {
	ID                uuid.UUID   `json:"id"`
	Username          string      `json:"username"`
	TotalXp           pgtype.Int4 `json:"total_xp"`
	Level             pgtype.Int4 `json:"level"`
	CurrentStreak     pgtype.Int4 `json:"current_streak"`
	LongestStreak     pgtype.Int4 `json:"longest_streak"`
	LastActivityDate  pgtype.Date `json:"last_activity_date"`
	ShowOnLeaderboard pgtype.Bool `json:"show_on_leaderboard"`
}

func (q *Queries) GetUserXP(ctx context.Context, id uuid.UUID) (GetUserXPRow, error) {
	row := q.db.QueryRow(ctx, getUserXP, id)
	var i GetUserXPRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
	)
	return i, err
}

const getUserXPHistory = `-- name: GetUserXPHistory :many
SELECT id, action_type, xp_amount, reference_id, metadata, created_at
FROM xp_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserXPHistoryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type GetUserXPHistoryRow struct {
	ID          uuid.UUID        `json:"id"`
	ActionType  string           `json:"action_type"`
	XpAmount    int32            `json:"xp_amount"`
	ReferenceID pgtype.UUID      `json:"reference_id"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserXPHistory(ctx context.Context, arg GetUserXPHistoryParams) ([]GetUserXPHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserXPHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserXPHistoryRow{}
	for rows.Next() {
		var i GetUserXPHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.XpAmount,
			&i.ReferenceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserXPToday = `-- name: GetUserXPToday :one
SELECT COALESCE(SUM(xp_amount), 0)::INTEGER as total_xp
FROM xp_transactions
WHERE user_id = $1
  AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) GetUserXPToday(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserXPToday, userID)
	var total_xp int32
	err := row.Scan(&total_xp)
	return total_xp, err
}

const logXPTransaction = `-- name: LogXPTransaction :exec

INSERT INTO xp_transactions (user_id, action_type, xp_amount, reference_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type LogXPTransactionParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ActionType  string      `json:"action_type"`
	XpAmount    int32       `json:"xp_amount"`
	ReferenceID pgtype.UUID `json:"reference_id"`
	Metadata    []byte      `json:"metadata"`
}

// ============================================================================
// XP TRANSACTION LOGGING
// ============================================================================
func (q *Queries) LogXPTransaction(ctx context.Context, arg LogXPTransactionParams) error {
	_, err := q.db.Exec(ctx, logXPTransaction,
		arg.UserID,
		arg.ActionType,
		arg.XpAmount,
		arg.ReferenceID,
		arg.Metadata,
	)
	return err
}

const rebuildAllLeaderboardStats = `-- name: RebuildAllLeaderboardStats :exec
INSERT INTO leaderboard_stats (
  user_id,
  username,
  books_read,
  pages_read,
  diary_entries,
  genres_explored,
  total_xp,
  level,
  current_streak
)
SELECT
  u.id,
  u.username,
  COALESCE((SELECT COUNT(*) FROM bookshelf WHERE user_id = u.id AND status = 'read'), 0)::INTEGER,
  COALESCE((SELECT SUM(b.page_count)
    FROM bookshelf bs
    JOIN books b ON bs.book_id = b.id
    WHERE bs.user_id = u.id AND bs.status = 'read' AND b.page_count IS NOT NULL), 0)::INTEGER,
  COALESCE((SELECT COUNT(*) FROM diary_entries WHERE user_id = u.id), 0)::INTEGER,
  COALESCE(array_length(u.favorite_genres, 1), 0),
  u.total_xp,
  u.level,
  u.current_streak
FROM users u
ON CONFLICT (user_id)
DO UPDATE SET
  username = EXCLUDED.username,
  books_read = EXCLUDED.books_read,
  pages_read = EXCLUDED.pages_read,
  diary_entries = EXCLUDED.diary_entries,
  genres_explored = EXCLUDED.genres_explored,
  total_xp = EXCLUDED.total_xp,
  level = EXCLUDED.level,
  current_streak = EXCLUDED.current_streak,
  updated_at = NOW()
`

func (q *Queries) RebuildAllLeaderboardStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildAllLeaderboardStats)
	return err
}

const rebuildUserLeaderboardStats = `-- name: RebuildUserLeaderboardStats :one
INSERT INTO leaderboard_stats (
  user_id,
  username,
  books_read,
  pages_read,
  diary_entries,
  genres_explored,
  total_xp,
  level,
  current_streak
)
SELECT
  u.id,
  u.username,
  COALESCE((SELECT COUNT(*) FROM bookshelf WHERE user_id = u.id AND status = 'read'), 0)::INTEGER as books_read,
  COALESCE((SELECT SUM(b.page_count)
    FROM bookshelf bs
    JOIN books b ON bs.book_id = b.id
    WHERE bs.user_id = u.id AND bs.status = 'read' AND b.page_count IS NOT NULL), 0)::INTEGER as pages_read,
  COALESCE((SELECT COUNT(*) FROM diary_entries WHERE user_id = u.id), 0)::INTEGER as diary_entries,
  COALESCE(array_length(u.favorite_genres, 1), 0) as genres_explored,
  u.total_xp,
  u.level,
  u.current_streak
FROM users u
WHERE u.id = $1
ON CONFLICT (user_id)
DO UPDATE SET
  username = EXCLUDED.username,
  books_read = EXCLUDED.books_read,
  pages_read = EXCLUDED.pages_read,
  diary_entries = EXCLUDED.diary_entries,
  genres_explored = EXCLUDED.genres_explored,
  total_xp = EXCLUDED.total_xp,
  level = EXCLUDED.level,
  current_streak = EXCLUDED.current_streak,
  updated_at = NOW()
RETURNING user_id, username, books_read, pages_read, diary_entries, genres_explored, total_xp, level, current_streak, books_rank, pages_rank, diary_rank, genres_rank, xp_rank, streak_rank, updated_at
`

func (q *Queries) RebuildUserLeaderboardStats(ctx context.Context, id uuid.UUID) (LeaderboardStat, error) {
	row := q.db.QueryRow(ctx, rebuildUserLeaderboardStats, id)
	var i LeaderboardStat
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.BooksRead,
		&i.PagesRead,
		&i.DiaryEntries,
		&i.GenresExplored,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.BooksRank,
		&i.PagesRank,
		&i.DiaryRank,
		&i.GenresRank,
		&i.XpRank,
		&i.StreakRank,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeaderboardRankings = `-- name: UpdateLeaderboardRankings :exec
WITH ranked AS (
  SELECT
    user_id,
    ROW_NUMBER() OVER (ORDER BY books_read DESC, total_xp DESC) as books_rank,
    ROW_NUMBER() OVER (ORDER BY pages_read DESC, total_xp DESC) as pages_rank,
    ROW_NUMBER() OVER (ORDER BY diary_entries DESC, total_xp DESC) as diary_rank,
    ROW_NUMBER() OVER (ORDER BY genres_explored DESC, total_xp DESC) as genres_rank,
    ROW_NUMBER() OVER (ORDER BY total_xp DESC, books_read DESC) as xp_rank,
    ROW_NUMBER() OVER (ORDER BY current_streak DESC, total_xp DESC) as streak_rank
  FROM leaderboard_stats
)
UPDATE leaderboard_stats ls
SET
  books_rank = r.books_rank::INTEGER,
  pages_rank = r.pages_rank::INTEGER,
  diary_rank = r.diary_rank::INTEGER,
  genres_rank = r.genres_rank::INTEGER,
  xp_rank = r.xp_rank::INTEGER,
  streak_rank = r.streak_rank::INTEGER
FROM ranked r
WHERE ls.user_id = r.user_id
`

func (q *Queries) UpdateLeaderboardRankings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateLeaderboardRankings)
	return err
}

const updateUserStreak = `-- name: UpdateUserStreak :exec

UPDATE users
SET
  current_streak = CASE
    -- Continued streak (activity yesterday)
    WHEN last_activity_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
    -- Same day activity (no change)
    WHEN last_activity_date = CURRENT_DATE THEN current_streak
    -- Broken streak (more than 1 day gap)
    ELSE 1
  END,
  longest_streak = GREATEST(
    longest_streak,
    CASE
      WHEN last_activity_date = CURRENT_DATE - INTERVAL '1 day' THEN current_streak + 1
      WHEN last_activity_date = CURRENT_DATE THEN current_streak
      ELSE 1
    END
  ),
  last_activity_date = CURRENT_DATE
WHERE id = $1
`

// ============================================================================
// STREAK MANAGEMENT
// ============================================================================
func (q *Queries) UpdateUserStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserStreak, id)
	return err
}
