// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserLikedBook = `-- name: CheckUserLikedBook :one
SELECT EXISTS(SELECT 1 FROM likes WHERE user_id = $1 AND book_id = $2)
`

type CheckUserLikedBookParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) CheckUserLikedBook(ctx context.Context, arg CheckUserLikedBookParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserLikedBook, arg.UserID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLikes = `-- name: GetUserLikes :many
SELECT b.id, b.title, b.slug, b.authors, b.isbn_13, b.google_books_id, b.metadata, b.view_count, b.like_count, b.created_at, b.updated_at, b.description, b.published_date, b.page_count, b.language, b.cover_url, b.categories, l.created_at as liked_at
FROM likes l
JOIN books b ON l.book_id = b.id
WHERE l.user_id = $1
ORDER BY l.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserLikesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserLikesRow struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Authors       []string           `json:"authors"`
	Isbn13        pgtype.Text        `json:"isbn_13"`
	GoogleBooksID pgtype.Text        `json:"google_books_id"`
	Metadata      []byte             `json:"metadata"`
	ViewCount     pgtype.Int4        `json:"view_count"`
	LikeCount     pgtype.Int4        `json:"like_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Description   pgtype.Text        `json:"description"`
	PublishedDate pgtype.Date        `json:"published_date"`
	PageCount     pgtype.Int4        `json:"page_count"`
	Language      pgtype.Text        `json:"language"`
	CoverUrl      pgtype.Text        `json:"cover_url"`
	Categories    []string           `json:"categories"`
	LikedAt       pgtype.Timestamptz `json:"liked_at"`
}

func (q *Queries) GetUserLikes(ctx context.Context, arg GetUserLikesParams) ([]GetUserLikesRow, error) {
	rows, err := q.db.Query(ctx, getUserLikes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserLikesRow{}
	for rows.Next() {
		var i GetUserLikesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.Isbn13,
			&i.GoogleBooksID,
			&i.Metadata,
			&i.ViewCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.PublishedDate,
			&i.PageCount,
			&i.Language,
			&i.CoverUrl,
			&i.Categories,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeBook = `-- name: LikeBook :one
INSERT INTO likes (user_id, book_id)
VALUES ($1, $2)
ON CONFLICT (user_id, book_id) DO NOTHING
RETURNING id, user_id, book_id, created_at
`

type LikeBookParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) LikeBook(ctx context.Context, arg LikeBookParams) (Like, error) {
	row := q.db.QueryRow(ctx, likeBook, arg.UserID, arg.BookID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.CreatedAt,
	)
	return i, err
}

const unlikeBook = `-- name: UnlikeBook :exec
DELETE FROM likes WHERE user_id = $1 AND book_id = $2
`

type UnlikeBookParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) UnlikeBook(ctx context.Context, arg UnlikeBookParams) error {
	_, err := q.db.Exec(ctx, unlikeBook, arg.UserID, arg.BookID)
	return err
}
