// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBookToList = `-- name: AddBookToList :one

INSERT INTO list_books (list_id, book_id, display_order)
VALUES ($1, $2, $3)
RETURNING id, list_id, book_id, added_at, display_order
`

type AddBookToListParams struct {
	ListID       uuid.UUID `json:"list_id"`
	BookID       uuid.UUID `json:"book_id"`
	DisplayOrder int32     `json:"display_order"`
}

// List Books Operations
func (q *Queries) AddBookToList(ctx context.Context, arg AddBookToListParams) (ListBook, error) {
	row := q.db.QueryRow(ctx, addBookToList, arg.ListID, arg.BookID, arg.DisplayOrder)
	var i ListBook
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.BookID,
		&i.AddedAt,
		&i.DisplayOrder,
	)
	return i, err
}

const checkBookInList = `-- name: CheckBookInList :one
SELECT EXISTS(
    SELECT 1 FROM list_books
    WHERE list_id = $1 AND book_id = $2
)
`

type CheckBookInListParams struct {
	ListID uuid.UUID `json:"list_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) CheckBookInList(ctx context.Context, arg CheckBookInListParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBookInList, arg.ListID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkCanAccessList = `-- name: CheckCanAccessList :one
SELECT EXISTS(
    SELECT 1 FROM lists l
    WHERE l.id = $1
    AND (
        l.is_private = false
        OR l.user_id = $2
        OR EXISTS(SELECT 1 FROM list_access WHERE list_id = $1 AND user_id = $2)
    )
)
`

type CheckCanAccessListParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckCanAccessList(ctx context.Context, arg CheckCanAccessListParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCanAccessList, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkListAccess = `-- name: CheckListAccess :one
SELECT EXISTS(
    SELECT 1 FROM list_access
    WHERE list_id = $1 AND user_id = $2
)
`

type CheckListAccessParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckListAccess(ctx context.Context, arg CheckListAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkListAccess, arg.ListID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkListOwnership = `-- name: CheckListOwnership :one

SELECT user_id FROM lists
WHERE id = $1
`

// Authorization Helpers
func (q *Queries) CheckListOwnership(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkListOwnership, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const checkListSaved = `-- name: CheckListSaved :one
SELECT EXISTS(
    SELECT 1 FROM saved_lists
    WHERE user_id = $1 AND list_id = $2
)
`

type CheckListSavedParams struct {
	UserID uuid.UUID `json:"user_id"`
	ListID uuid.UUID `json:"list_id"`
}

func (q *Queries) CheckListSaved(ctx context.Context, arg CheckListSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkListSaved, arg.UserID, arg.ListID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countListBooks = `-- name: CountListBooks :one
SELECT COUNT(*) FROM list_books
WHERE list_id = $1
`

func (q *Queries) CountListBooks(ctx context.Context, listID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListBooks, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListSaves = `-- name: CountListSaves :one
SELECT COUNT(*) FROM saved_lists
WHERE list_id = $1
`

func (q *Queries) CountListSaves(ctx context.Context, listID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListSaves, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserLists = `-- name: CountUserLists :one
SELECT COUNT(*) FROM lists
WHERE user_id = $1
`

func (q *Queries) CountUserLists(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLists, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (user_id, title, description, is_private)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, is_private, created_at, updated_at
`

type CreateListParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPrivate   bool        `json:"is_private"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.IsPrivate,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementUserListsCount = `-- name: DecrementUserListsCount :exec
UPDATE users
SET lists_count = GREATEST(lists_count - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementUserListsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementUserListsCount, id)
	return err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists
WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getListAccessUsers = `-- name: GetListAccessUsers :many
SELECT
    la.id,
    la.list_id,
    la.user_id,
    la.granted_by,
    la.granted_at,
    u.username,
    u.name,
    u.avatar_url
FROM list_access la
JOIN users u ON la.user_id = u.id
WHERE la.list_id = $1
ORDER BY la.granted_at DESC
`

type GetListAccessUsersRow struct {
	ID        uuid.UUID        `json:"id"`
	ListID    uuid.UUID        `json:"list_id"`
	UserID    uuid.UUID        `json:"user_id"`
	GrantedBy uuid.UUID        `json:"granted_by"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
	Username  string           `json:"username"`
	Name      pgtype.Text      `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
}

func (q *Queries) GetListAccessUsers(ctx context.Context, listID uuid.UUID) ([]GetListAccessUsersRow, error) {
	rows, err := q.db.Query(ctx, getListAccessUsers, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListAccessUsersRow{}
	for rows.Next() {
		var i GetListAccessUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListBooks = `-- name: GetListBooks :many
SELECT
    lb.id,
    lb.list_id,
    lb.book_id,
    lb.added_at,
    lb.display_order,
    b.title,
    b.slug,
    b.authors,
    b.cover_url,
    b.published_date,
    b.page_count,
    b.isbn_13,
    b.description,
    b.categories,
    b.publisher,
    b.language,
    b.subtitle,
    b.isbndb_id,
    b.google_books_id,
    b.average_rating,
    b.ratings_count
FROM list_books lb
JOIN books b ON lb.book_id = b.id
WHERE lb.list_id = $1
ORDER BY lb.display_order ASC, lb.added_at DESC
`

type GetListBooksRow struct {
	ID            uuid.UUID        `json:"id"`
	ListID        uuid.UUID        `json:"list_id"`
	BookID        uuid.UUID        `json:"book_id"`
	AddedAt       pgtype.Timestamp `json:"added_at"`
	DisplayOrder  int32            `json:"display_order"`
	Title         string           `json:"title"`
	Slug          string           `json:"slug"`
	Authors       []string         `json:"authors"`
	CoverUrl      pgtype.Text      `json:"cover_url"`
	PublishedDate pgtype.Date      `json:"published_date"`
	PageCount     pgtype.Int4      `json:"page_count"`
	Isbn13        pgtype.Text      `json:"isbn_13"`
	Description   pgtype.Text      `json:"description"`
	Categories    []string         `json:"categories"`
	Publisher     pgtype.Text      `json:"publisher"`
	Language      pgtype.Text      `json:"language"`
	Subtitle      pgtype.Text      `json:"subtitle"`
	IsbndbID      pgtype.Text      `json:"isbndb_id"`
	GoogleBooksID pgtype.Text      `json:"google_books_id"`
	AverageRating pgtype.Float8    `json:"average_rating"`
	RatingsCount  pgtype.Int4      `json:"ratings_count"`
}

func (q *Queries) GetListBooks(ctx context.Context, listID uuid.UUID) ([]GetListBooksRow, error) {
	rows, err := q.db.Query(ctx, getListBooks, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListBooksRow{}
	for rows.Next() {
		var i GetListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.BookID,
			&i.AddedAt,
			&i.DisplayOrder,
			&i.Title,
			&i.Slug,
			&i.Authors,
			&i.CoverUrl,
			&i.PublishedDate,
			&i.PageCount,
			&i.Isbn13,
			&i.Description,
			&i.Categories,
			&i.Publisher,
			&i.Language,
			&i.Subtitle,
			&i.IsbndbID,
			&i.GoogleBooksID,
			&i.AverageRating,
			&i.RatingsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListByID = `-- name: GetListByID :one
SELECT id, user_id, title, description, is_private, created_at, updated_at FROM lists
WHERE id = $1
`

func (q *Queries) GetListByID(ctx context.Context, id uuid.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getListByID, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListCoverURLs = `-- name: GetListCoverURLs :many
SELECT r.cover_url
FROM (
    SELECT
        lb.display_order,
        lb.added_at,
        CAST(
            COALESCE(
                NULLIF(TRIM(b.cover_url), ''),
                CASE
                    WHEN b.google_books_id IS NOT NULL AND TRIM(b.google_books_id) <> ''
                    THEN 'https://books.google.com/books/content?id='
                        || TRIM(b.google_books_id)
                        || '&printsec=frontcover&img=1&zoom=1&source=gbs_api'
                    ELSE NULL
                END,
                CASE
                    WHEN b.isbn_13 IS NOT NULL AND TRIM(REPLACE(b.isbn_13, '-', '')) <> ''
                    THEN 'https://covers.openlibrary.org/b/isbn/'
                        || TRIM(REPLACE(b.isbn_13, '-', ''))
                        || '-M.jpg'
                    ELSE NULL
                END
            ) AS TEXT
        ) AS cover_url
    FROM list_books lb
    INNER JOIN books b ON lb.book_id = b.id
    WHERE lb.list_id = $1
) AS r
WHERE r.cover_url IS NOT NULL
ORDER BY r.display_order ASC, r.added_at DESC
LIMIT 3
`

// Prefer stored cover_url; otherwise synthesize a thumbnail URL from Google Books
// id or ISBN so list cards still show art when cover_url was never backfilled.
func (q *Queries) GetListCoverURLs(ctx context.Context, listID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getListCoverURLs, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cover_url string
		if err := rows.Scan(&cover_url); err != nil {
			return nil, err
		}
		items = append(items, cover_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLists = `-- name: GetUserLists :many
SELECT
    l.id,
    l.user_id,
    l.title,
    l.description,
    l.is_private,
    l.created_at,
    l.updated_at,
    COUNT(DISTINCT lb.book_id) as book_count
FROM lists l
LEFT JOIN list_books lb ON l.id = lb.list_id
WHERE l.user_id = $1
GROUP BY l.id
ORDER BY l.updated_at DESC
LIMIT $2 OFFSET $3
`

type GetUserListsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserListsRow struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	IsPrivate   bool             `json:"is_private"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	BookCount   int64            `json:"book_count"`
}

func (q *Queries) GetUserLists(ctx context.Context, arg GetUserListsParams) ([]GetUserListsRow, error) {
	rows, err := q.db.Query(ctx, getUserLists, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserListsRow{}
	for rows.Next() {
		var i GetUserListsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSavedLists = `-- name: GetUserSavedLists :many
SELECT
    l.id, l.user_id, l.title, l.description, l.is_private, l.created_at, l.updated_at,
    u.username as owner_username,
    sl.saved_at,
    COUNT(DISTINCT lb.book_id) as book_count
FROM saved_lists sl
JOIN lists l ON sl.list_id = l.id
JOIN users u ON l.user_id = u.id
LEFT JOIN list_books lb ON l.id = lb.list_id
WHERE sl.user_id = $1
GROUP BY l.id, u.username, sl.saved_at
ORDER BY sl.saved_at DESC
LIMIT $2 OFFSET $3
`

type GetUserSavedListsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserSavedListsRow struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	Title         string           `json:"title"`
	Description   pgtype.Text      `json:"description"`
	IsPrivate     bool             `json:"is_private"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	OwnerUsername string           `json:"owner_username"`
	SavedAt       pgtype.Timestamp `json:"saved_at"`
	BookCount     int64            `json:"book_count"`
}

func (q *Queries) GetUserSavedLists(ctx context.Context, arg GetUserSavedListsParams) ([]GetUserSavedListsRow, error) {
	rows, err := q.db.Query(ctx, getUserSavedLists, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSavedListsRow{}
	for rows.Next() {
		var i GetUserSavedListsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.SavedAt,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantListAccess = `-- name: GrantListAccess :one

INSERT INTO list_access (list_id, user_id, granted_by)
VALUES ($1, $2, $3)
RETURNING id, list_id, user_id, granted_by, granted_at
`

type GrantListAccessParams struct {
	ListID    uuid.UUID `json:"list_id"`
	UserID    uuid.UUID `json:"user_id"`
	GrantedBy uuid.UUID `json:"granted_by"`
}

// Access Control
func (q *Queries) GrantListAccess(ctx context.Context, arg GrantListAccessParams) (ListAccess, error) {
	row := q.db.QueryRow(ctx, grantListAccess, arg.ListID, arg.UserID, arg.GrantedBy)
	var i ListAccess
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.UserID,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const incrementUserListsCount = `-- name: IncrementUserListsCount :exec
UPDATE users
SET lists_count = lists_count + 1
WHERE id = $1
`

func (q *Queries) IncrementUserListsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserListsCount, id)
	return err
}

const removeBookFromList = `-- name: RemoveBookFromList :exec
DELETE FROM list_books
WHERE list_id = $1 AND book_id = $2
`

type RemoveBookFromListParams struct {
	ListID uuid.UUID `json:"list_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) RemoveBookFromList(ctx context.Context, arg RemoveBookFromListParams) error {
	_, err := q.db.Exec(ctx, removeBookFromList, arg.ListID, arg.BookID)
	return err
}

const revokeListAccess = `-- name: RevokeListAccess :exec
DELETE FROM list_access
WHERE list_id = $1 AND user_id = $2
`

type RevokeListAccessParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeListAccess(ctx context.Context, arg RevokeListAccessParams) error {
	_, err := q.db.Exec(ctx, revokeListAccess, arg.ListID, arg.UserID)
	return err
}

const saveList = `-- name: SaveList :one

INSERT INTO saved_lists (user_id, list_id)
VALUES ($1, $2)
RETURNING id, user_id, list_id, saved_at
`

type SaveListParams struct {
	UserID uuid.UUID `json:"user_id"`
	ListID uuid.UUID `json:"list_id"`
}

// Saved Lists
func (q *Queries) SaveList(ctx context.Context, arg SaveListParams) (SavedList, error) {
	row := q.db.QueryRow(ctx, saveList, arg.UserID, arg.ListID)
	var i SavedList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListID,
		&i.SavedAt,
	)
	return i, err
}

const unsaveList = `-- name: UnsaveList :exec
DELETE FROM saved_lists
WHERE user_id = $1 AND list_id = $2
`

type UnsaveListParams struct {
	UserID uuid.UUID `json:"user_id"`
	ListID uuid.UUID `json:"list_id"`
}

func (q *Queries) UnsaveList(ctx context.Context, arg UnsaveListParams) error {
	_, err := q.db.Exec(ctx, unsaveList, arg.UserID, arg.ListID)
	return err
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET
    title = $2,
    description = $3,
    is_private = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, description, is_private, created_at, updated_at
`

type UpdateListParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPrivate   bool        `json:"is_private"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsPrivate,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
