// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Authors       []string           `json:"authors"`
	Isbn13        pgtype.Text        `json:"isbn_13"`
	GoogleBooksID pgtype.Text        `json:"google_books_id"`
	Metadata      []byte             `json:"metadata"`
	ViewCount     pgtype.Int4        `json:"view_count"`
	LikeCount     pgtype.Int4        `json:"like_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	DeviceInfo []byte             `json:"device_info"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Name           pgtype.Text        `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Bio            pgtype.Text        `json:"bio"`
	Pronouns       pgtype.Text        `json:"pronouns"`
	IsPublic       pgtype.Bool        `json:"is_public"`
	FavoriteGenres []string           `json:"favorite_genres"`
	Settings       []byte             `json:"settings"`
	FollowersCount pgtype.Int4        `json:"followers_count"`
	FollowingCount pgtype.Int4        `json:"following_count"`
	BooksReadCount pgtype.Int4        `json:"books_read_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastActive     pgtype.Timestamptz `json:"last_active"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	MongoID        pgtype.Text        `json:"mongo_id"`
}
