// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccountDeletion struct {
	ID        uuid.UUID          `json:"id"`
	Reasons   []string           `json:"reasons"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	EmailHash pgtype.Text        `json:"email_hash"`
}

type Activity struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ActivityType string             `json:"activity_type"`
	BookID       pgtype.UUID        `json:"book_id"`
	ListID       pgtype.UUID        `json:"list_id"`
	ThoughtID    pgtype.UUID        `json:"thought_id"`
	TargetUserID pgtype.UUID        `json:"target_user_id"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamp   `json:"created_at"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
}

type Block struct {
	BlockerID uuid.UUID          `json:"blocker_id"`
	BlockedID uuid.UUID          `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Book struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	Authors           []string           `json:"authors"`
	Isbn13            pgtype.Text        `json:"isbn_13"`
	GoogleBooksID     pgtype.Text        `json:"google_books_id"`
	Metadata          []byte             `json:"metadata"`
	ViewCount         pgtype.Int4        `json:"view_count"`
	LikeCount         pgtype.Int4        `json:"like_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Description       pgtype.Text        `json:"description"`
	PublishedDate     pgtype.Date        `json:"published_date"`
	PageCount         pgtype.Int4        `json:"page_count"`
	Language          pgtype.Text        `json:"language"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Categories        []string           `json:"categories"`
	Subtitle          pgtype.Text        `json:"subtitle"`
	Publisher         pgtype.Text        `json:"publisher"`
	IsbndbID          pgtype.Text        `json:"isbndb_id"`
	OpenLibraryID     pgtype.Text        `json:"open_library_id"`
	AverageRating     pgtype.Float8      `json:"average_rating"`
	RatingsCount      pgtype.Int4        `json:"ratings_count"`
	PreviewLink       pgtype.Text        `json:"preview_link"`
	TotalReadsCount   pgtype.Int4        `json:"total_reads_count"`
	TotalTbrCount     pgtype.Int4        `json:"total_tbr_count"`
	Embedding         pgvector.Vector    `json:"embedding"`
	EmbeddingText     pgtype.Text        `json:"embedding_text"`
	DescriptionSource pgtype.Text        `json:"description_source"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
}

type BookReadLink struct {
	BookID              uuid.UUID          `json:"book_id"`
	GooglePlayBuyLink   pgtype.Text        `json:"google_play_buy_link"`
	GooglePlayCheckedAt pgtype.Timestamptz `json:"google_play_checked_at"`
	AppleBooksUrl       pgtype.Text        `json:"apple_books_url"`
	AppleBooksCheckedAt pgtype.Timestamptz `json:"apple_books_checked_at"`
	IsPublicDomain      bool               `json:"is_public_domain"`
	GutenbergID         pgtype.Int4        `json:"gutenberg_id"`
	GutenbergHtmlUrl    pgtype.Text        `json:"gutenberg_html_url"`
	GutenbergEpubUrl    pgtype.Text        `json:"gutenberg_epub_url"`
	GutenbergCheckedAt  pgtype.Timestamptz `json:"gutenberg_checked_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BookTrait struct {
	BookID              uuid.UUID          `json:"book_id"`
	CharacterDriven     float32            `json:"character_driven"`
	EmotionalIntensity  float32            `json:"emotional_intensity"`
	PlotIntensity       float32            `json:"plot_intensity"`
	Pacing              float32            `json:"pacing"`
	ProseDensity        float32            `json:"prose_density"`
	NarrativeComplexity float32            `json:"narrative_complexity"`
	Darkness            float32            `json:"darkness"`
	RomanceCentrality   float32            `json:"romance_centrality"`
	Worldbuilding       float32            `json:"worldbuilding"`
	Traits              []byte             `json:"traits"`
	Confidence          float32            `json:"confidence"`
	ExtractorVersion    int32              `json:"extractor_version"`
	ExtractedAt         pgtype.Timestamptz `json:"extracted_at"`
}

type Bookshelf struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	BookID              uuid.UUID          `json:"book_id"`
	Status              string             `json:"status"`
	Rating              pgtype.Int4        `json:"rating"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TbrNotes            pgtype.Text        `json:"tbr_notes"`
	TbrPriority         pgtype.Text        `json:"tbr_priority"`
	TbrAddedAt          pgtype.Timestamp   `json:"tbr_added_at"`
	CurrentPage         pgtype.Int4        `json:"current_page"`
	ReadingVelocity     pgtype.Float8      `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date        `json:"estimated_finish_date"`
	Notes               pgtype.Text        `json:"notes"`
	Format              pgtype.Text        `json:"format"`
	Review              pgtype.Text        `json:"review"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	ReviewEdited        bool               `json:"review_edited"`
}

type DeviceToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Platform  string             `json:"platform"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	BookID    pgtype.UUID        `json:"book_id"`
	EventType string             `json:"event_type"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SessionID pgtype.UUID        `json:"session_id"`
	Source    pgtype.Text        `json:"source"`
	Path      pgtype.Text        `json:"path"`
	AnonID    pgtype.UUID        `json:"anon_id"`
}

type Favorite struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       uuid.UUID        `json:"book_id"`
	DisplayOrder int32            `json:"display_order"`
	FavoriteNote pgtype.Text      `json:"favorite_note"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type FeatureFlag struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Follow struct {
	ID          uuid.UUID          `json:"id"`
	FollowerID  uuid.UUID          `json:"follower_id"`
	FollowingID uuid.UUID          `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type FollowRequest struct {
	ID          uuid.UUID          `json:"id"`
	RequesterID uuid.UUID          `json:"requester_id"`
	TargetID    uuid.UUID          `json:"target_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Fusion struct {
	ID         uuid.UUID          `json:"id"`
	UserA      uuid.UUID          `json:"user_a"`
	UserB      uuid.UUID          `json:"user_b"`
	InviterID  uuid.UUID          `json:"inviter_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Snapshot   []byte             `json:"snapshot"`
	ComputedAt pgtype.Timestamptz `json:"computed_at"`
}

type FusionInvite struct {
	Token       string             `json:"token"`
	InviterID   uuid.UUID          `json:"inviter_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy  pgtype.UUID        `json:"consumed_by"`
}

type LeaderboardStat struct {
	UserID         uuid.UUID        `json:"user_id"`
	Username       string           `json:"username"`
	BooksRead      pgtype.Int4      `json:"books_read"`
	PagesRead      pgtype.Int4      `json:"pages_read"`
	Thoughts       pgtype.Int4      `json:"thoughts"`
	GenresExplored pgtype.Int4      `json:"genres_explored"`
	TotalXp        pgtype.Int4      `json:"total_xp"`
	Level          pgtype.Int4      `json:"level"`
	CurrentStreak  pgtype.Int4      `json:"current_streak"`
	BooksRank      pgtype.Int4      `json:"books_rank"`
	PagesRank      pgtype.Int4      `json:"pages_rank"`
	ThoughtsRank   pgtype.Int4      `json:"thoughts_rank"`
	GenresRank     pgtype.Int4      `json:"genres_rank"`
	XpRank         pgtype.Int4      `json:"xp_rank"`
	StreakRank     pgtype.Int4      `json:"streak_rank"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Like struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	BookID    uuid.UUID          `json:"book_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Reason    pgtype.Text        `json:"reason"`
}

type List struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	IsPrivate   bool             `json:"is_private"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ListAccess struct {
	ID        uuid.UUID        `json:"id"`
	ListID    uuid.UUID        `json:"list_id"`
	UserID    uuid.UUID        `json:"user_id"`
	GrantedBy uuid.UUID        `json:"granted_by"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
}

type ListBook struct {
	ID           uuid.UUID        `json:"id"`
	ListID       uuid.UUID        `json:"list_id"`
	BookID       uuid.UUID        `json:"book_id"`
	AddedAt      pgtype.Timestamp `json:"added_at"`
	DisplayOrder int32            `json:"display_order"`
}

type Newsletter struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	IsActive       bool               `json:"is_active"`
	Source         string             `json:"source"`
	SubscribedAt   pgtype.Timestamptz `json:"subscribed_at"`
	UnsubscribedAt pgtype.Timestamptz `json:"unsubscribed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type NewsletterSubscription struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OtpCode struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReadingLog struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	BookID     uuid.UUID          `json:"book_id"`
	PagesDelta int32              `json:"pages_delta"`
	LoggedAt   pgtype.Timestamptz `json:"logged_at"`
}

type RecommendationFeedback struct {
	UserID      uuid.UUID          `json:"user_id"`
	BookID      uuid.UUID          `json:"book_id"`
	Verdict     string             `json:"verdict"`
	ReasonCodes []string           `json:"reason_codes"`
	ReasonType  pgtype.Text        `json:"reason_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RecommendationImpression struct {
	UserID           uuid.UUID          `json:"user_id"`
	BookID           uuid.UUID          `json:"book_id"`
	SeenCount        pgtype.Int4        `json:"seen_count"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	SuppressUntil    pgtype.Timestamptz `json:"suppress_until"`
	DismissedUntil   pgtype.Timestamptz `json:"dismissed_until"`
	DismissedForever bool               `json:"dismissed_forever"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	DeviceInfo []byte             `json:"device_info"`
}

type Report struct {
	ID          uuid.UUID          `json:"id"`
	ReporterID  uuid.UUID          `json:"reporter_id"`
	ContentType string             `json:"content_type"`
	ContentID   string             `json:"content_id"`
	Reason      string             `json:"reason"`
	Details     pgtype.Text        `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SavedList struct {
	ID      uuid.UUID        `json:"id"`
	UserID  uuid.UUID        `json:"user_id"`
	ListID  uuid.UUID        `json:"list_id"`
	SavedAt pgtype.Timestamp `json:"saved_at"`
}

type ScanCommunityCache struct {
	Isbn             string             `json:"isbn"`
	CommunitySummary string             `json:"community_summary"`
	CachedAt         pgtype.Timestamptz `json:"cached_at"`
	ReadersCount     int32              `json:"readers_count"`
	RatingsCount     int32              `json:"ratings_count"`
	RatingsAverage   float64            `json:"ratings_average"`
}

type TasteOverlap struct {
	UserA       uuid.UUID          `json:"user_a"`
	UserB       uuid.UUID          `json:"user_b"`
	Overlap     float32            `json:"overlap"`
	SharedCount int32              `json:"shared_count"`
	SharedLoved []uuid.UUID        `json:"shared_loved"`
	Disagreed   []uuid.UUID        `json:"disagreed"`
	ACouldRead  []uuid.UUID        `json:"a_could_read"`
	BCouldRead  []uuid.UUID        `json:"b_could_read"`
	ComputedAt  pgtype.Timestamptz `json:"computed_at"`
}

type Thought struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	BookID        pgtype.UUID      `json:"book_id"`
	Title         pgtype.Text      `json:"title"`
	Content       string           `json:"content"`
	IsPrivate     bool             `json:"is_private"`
	Rating        pgtype.Int4      `json:"rating"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Embedding     pgvector.Vector  `json:"embedding"`
	EmbeddingText pgtype.Text      `json:"embedding_text"`
	ThreadRootID  pgtype.UUID      `json:"thread_root_id"`
}

type ThoughtLike struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	ThoughtID uuid.UUID        `json:"thought_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ThoughtRepost struct {
	UserID    uuid.UUID        `json:"user_id"`
	ThoughtID uuid.UUID        `json:"thought_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                     uuid.UUID          `json:"id"`
	Username               string             `json:"username"`
	Email                  string             `json:"email"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	Name                   pgtype.Text        `json:"name"`
	AvatarUrl              pgtype.Text        `json:"avatar_url"`
	Bio                    pgtype.Text        `json:"bio"`
	Pronouns               []string           `json:"pronouns"`
	IsPublic               bool               `json:"is_public"`
	FavoriteGenres         []string           `json:"favorite_genres"`
	Settings               []byte             `json:"settings"`
	FollowersCount         pgtype.Int4        `json:"followers_count"`
	FollowingCount         pgtype.Int4        `json:"following_count"`
	BooksReadCount         pgtype.Int4        `json:"books_read_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LastActive             pgtype.Timestamptz `json:"last_active"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	MongoID                pgtype.Text        `json:"mongo_id"`
	Birthday               pgtype.Date        `json:"birthday"`
	Gender                 pgtype.Text        `json:"gender"`
	Links                  []string           `json:"links"`
	TotalPagesRead         pgtype.Int4        `json:"total_pages_read"`
	FavoritesCount         int32              `json:"favorites_count"`
	ListsCount             int32              `json:"lists_count"`
	ThoughtsCount          int32              `json:"thoughts_count"`
	ReadingGoalYear        pgtype.Int4        `json:"reading_goal_year"`
	ReadingGoalTarget      pgtype.Int4        `json:"reading_goal_target"`
	ReadingGoalCurrent     pgtype.Int4        `json:"reading_goal_current"`
	TotalXp                pgtype.Int4        `json:"total_xp"`
	Level                  pgtype.Int4        `json:"level"`
	CurrentStreak          pgtype.Int4        `json:"current_streak"`
	LongestStreak          pgtype.Int4        `json:"longest_streak"`
	LastActivityDate       pgtype.Date        `json:"last_activity_date"`
	ShowOnLeaderboard      pgtype.Bool        `json:"show_on_leaderboard"`
	ReferralCode           pgtype.Text        `json:"referral_code"`
	ReferredBy             pgtype.UUID        `json:"referred_by"`
	ReferralCount          pgtype.Int4        `json:"referral_count"`
	ReferralRewardsClaimed []string           `json:"referral_rewards_claimed"`
	OnboardingCompleted    bool               `json:"onboarding_completed"`
	BannerUrl              pgtype.Text        `json:"banner_url"`
	ScanUsesRemaining      int32              `json:"scan_uses_remaining"`
	AppleUserID            pgtype.Text        `json:"apple_user_id"`
}

type UserAuthorsRead struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	AuthorName     string             `json:"author_name"`
	BooksRead      int32              `json:"books_read"`
	BooksTbr       int32              `json:"books_tbr"`
	FavoriteBookID pgtype.UUID        `json:"favorite_book_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserPreferencesLegacy struct {
	UserID         uuid.UUID          `json:"user_id"`
	Payload        []byte             `json:"payload"`
	MongoUpdatedAt pgtype.Timestamptz `json:"mongo_updated_at"`
	MigratedAt     pgtype.Timestamptz `json:"migrated_at"`
}

type UserSignalProfile struct {
	UserID                uuid.UUID          `json:"user_id"`
	GenreWeights          []byte             `json:"genre_weights"`
	AuthorWeights         []byte             `json:"author_weights"`
	ComputedAt            pgtype.Timestamptz `json:"computed_at"`
	BookshelfHash         pgtype.Text        `json:"bookshelf_hash"`
	VelocitySignal        []byte             `json:"velocity_signal"`
	ThoughtSignal         []byte             `json:"thought_signal"`
	ThoughtEmbedding      pgvector.Vector    `json:"thought_embedding"`
	SocialSignal          []byte             `json:"social_signal"`
	SignalVersion         int32              `json:"signal_version"`
	FastFinishEmbedding   pgvector.Vector    `json:"fast_finish_embedding"`
	TraitPrefs            []byte             `json:"trait_prefs"`
	TraitDislikes         []byte             `json:"trait_dislikes"`
	TraitConfidence       []byte             `json:"trait_confidence"`
	DepthSignal           []byte             `json:"depth_signal"`
	TraitRecent           []byte             `json:"trait_recent"`
	TraitRecentConfidence []byte             `json:"trait_recent_confidence"`
}

type XpTransaction struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	ActionType  string           `json:"action_type"`
	XpAmount    int32            `json:"xp_amount"`
	ReferenceID pgtype.UUID      `json:"reference_id"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
