// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccountDeletion struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Username  pgtype.Text        `json:"username"`
	Reasons   []string           `json:"reasons"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type Activity struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	ActivityType string           `json:"activity_type"`
	BookID       pgtype.UUID      `json:"book_id"`
	ListID       pgtype.UUID      `json:"list_id"`
	EntryID      pgtype.UUID      `json:"entry_id"`
	TargetUserID pgtype.UUID      `json:"target_user_id"`
	Metadata     []byte           `json:"metadata"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Book struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	Authors           []string           `json:"authors"`
	Isbn13            pgtype.Text        `json:"isbn_13"`
	GoogleBooksID     pgtype.Text        `json:"google_books_id"`
	Metadata          []byte             `json:"metadata"`
	ViewCount         pgtype.Int4        `json:"view_count"`
	LikeCount         pgtype.Int4        `json:"like_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Description       pgtype.Text        `json:"description"`
	PublishedDate     pgtype.Date        `json:"published_date"`
	PageCount         pgtype.Int4        `json:"page_count"`
	Language          pgtype.Text        `json:"language"`
	CoverUrl          pgtype.Text        `json:"cover_url"`
	Categories        []string           `json:"categories"`
	Subtitle          pgtype.Text        `json:"subtitle"`
	Publisher         pgtype.Text        `json:"publisher"`
	IsbndbID          pgtype.Text        `json:"isbndb_id"`
	OpenLibraryID     pgtype.Text        `json:"open_library_id"`
	AverageRating     pgtype.Float8      `json:"average_rating"`
	RatingsCount      pgtype.Int4        `json:"ratings_count"`
	PreviewLink       pgtype.Text        `json:"preview_link"`
	TotalReadsCount   pgtype.Int4        `json:"total_reads_count"`
	TotalTbrCount     pgtype.Int4        `json:"total_tbr_count"`
	Embedding         pgvector.Vector    `json:"embedding"`
	EmbeddingText     pgtype.Text        `json:"embedding_text"`
	DescriptionSource pgtype.Text        `json:"description_source"`
	LastAccessedAt    pgtype.Timestamptz `json:"last_accessed_at"`
}

type Bookshelf struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	BookID              uuid.UUID          `json:"book_id"`
	Status              string             `json:"status"`
	Rating              pgtype.Int4        `json:"rating"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TbrNotes            pgtype.Text        `json:"tbr_notes"`
	TbrPriority         pgtype.Text        `json:"tbr_priority"`
	TbrAddedAt          pgtype.Timestamp   `json:"tbr_added_at"`
	CurrentPage         pgtype.Int4        `json:"current_page"`
	ReadingVelocity     pgtype.Float8      `json:"reading_velocity"`
	EstimatedFinishDate pgtype.Date        `json:"estimated_finish_date"`
	Notes               pgtype.Text        `json:"notes"`
	Format              pgtype.Text        `json:"format"`
	Review              pgtype.Text        `json:"review"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	ReviewEdited        bool               `json:"review_edited"`
}

type DiaryEntry struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	BookID        pgtype.UUID      `json:"book_id"`
	Title         pgtype.Text      `json:"title"`
	Content       string           `json:"content"`
	IsPrivate     bool             `json:"is_private"`
	Rating        pgtype.Int4      `json:"rating"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Embedding     pgvector.Vector  `json:"embedding"`
	EmbeddingText pgtype.Text      `json:"embedding_text"`
}

type DiaryEntryLike struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	EntryID   uuid.UUID        `json:"entry_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Event struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	BookID    pgtype.UUID        `json:"book_id"`
	EventType string             `json:"event_type"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       uuid.UUID        `json:"book_id"`
	DisplayOrder int32            `json:"display_order"`
	FavoriteNote pgtype.Text      `json:"favorite_note"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type FeatureFlag struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Follow struct {
	ID          uuid.UUID          `json:"id"`
	FollowerID  uuid.UUID          `json:"follower_id"`
	FollowingID uuid.UUID          `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LeaderboardStat struct {
	UserID         uuid.UUID        `json:"user_id"`
	Username       string           `json:"username"`
	BooksRead      pgtype.Int4      `json:"books_read"`
	PagesRead      pgtype.Int4      `json:"pages_read"`
	DiaryEntries   pgtype.Int4      `json:"diary_entries"`
	GenresExplored pgtype.Int4      `json:"genres_explored"`
	TotalXp        pgtype.Int4      `json:"total_xp"`
	Level          pgtype.Int4      `json:"level"`
	CurrentStreak  pgtype.Int4      `json:"current_streak"`
	BooksRank      pgtype.Int4      `json:"books_rank"`
	PagesRank      pgtype.Int4      `json:"pages_rank"`
	DiaryRank      pgtype.Int4      `json:"diary_rank"`
	GenresRank     pgtype.Int4      `json:"genres_rank"`
	XpRank         pgtype.Int4      `json:"xp_rank"`
	StreakRank     pgtype.Int4      `json:"streak_rank"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Like struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	BookID    uuid.UUID          `json:"book_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Reason    pgtype.Text        `json:"reason"`
}

type List struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	IsPrivate   bool             `json:"is_private"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ListAccess struct {
	ID        uuid.UUID        `json:"id"`
	ListID    uuid.UUID        `json:"list_id"`
	UserID    uuid.UUID        `json:"user_id"`
	GrantedBy uuid.UUID        `json:"granted_by"`
	GrantedAt pgtype.Timestamp `json:"granted_at"`
}

type ListBook struct {
	ID           uuid.UUID        `json:"id"`
	ListID       uuid.UUID        `json:"list_id"`
	BookID       uuid.UUID        `json:"book_id"`
	AddedAt      pgtype.Timestamp `json:"added_at"`
	DisplayOrder int32            `json:"display_order"`
}

type Newsletter struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	IsActive       bool               `json:"is_active"`
	Source         string             `json:"source"`
	SubscribedAt   pgtype.Timestamptz `json:"subscribed_at"`
	UnsubscribedAt pgtype.Timestamptz `json:"unsubscribed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type NewsletterSubscription struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OtpCode struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Metadata    []byte             `json:"metadata"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReadingLog struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	BookID     uuid.UUID          `json:"book_id"`
	PagesDelta int32              `json:"pages_delta"`
	LoggedAt   pgtype.Timestamptz `json:"logged_at"`
}

type RecommendationImpression struct {
	UserID        uuid.UUID          `json:"user_id"`
	BookID        uuid.UUID          `json:"book_id"`
	SeenCount     pgtype.Int4        `json:"seen_count"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	SuppressUntil pgtype.Timestamptz `json:"suppress_until"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	DeviceInfo []byte             `json:"device_info"`
}

type SavedList struct {
	ID      uuid.UUID        `json:"id"`
	UserID  uuid.UUID        `json:"user_id"`
	ListID  uuid.UUID        `json:"list_id"`
	SavedAt pgtype.Timestamp `json:"saved_at"`
}

type User struct {
	ID                     uuid.UUID          `json:"id"`
	Username               string             `json:"username"`
	Email                  string             `json:"email"`
	PasswordHash           pgtype.Text        `json:"password_hash"`
	Name                   pgtype.Text        `json:"name"`
	AvatarUrl              pgtype.Text        `json:"avatar_url"`
	Bio                    pgtype.Text        `json:"bio"`
	Pronouns               []string           `json:"pronouns"`
	IsPublic               pgtype.Bool        `json:"is_public"`
	FavoriteGenres         []string           `json:"favorite_genres"`
	Settings               []byte             `json:"settings"`
	FollowersCount         pgtype.Int4        `json:"followers_count"`
	FollowingCount         pgtype.Int4        `json:"following_count"`
	BooksReadCount         pgtype.Int4        `json:"books_read_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LastActive             pgtype.Timestamptz `json:"last_active"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	MongoID                pgtype.Text        `json:"mongo_id"`
	Birthday               pgtype.Date        `json:"birthday"`
	Gender                 pgtype.Text        `json:"gender"`
	Links                  []string           `json:"links"`
	TotalPagesRead         pgtype.Int4        `json:"total_pages_read"`
	FavoritesCount         int32              `json:"favorites_count"`
	ListsCount             int32              `json:"lists_count"`
	DiaryEntriesCount      int32              `json:"diary_entries_count"`
	ReadingGoalYear        pgtype.Int4        `json:"reading_goal_year"`
	ReadingGoalTarget      pgtype.Int4        `json:"reading_goal_target"`
	ReadingGoalCurrent     pgtype.Int4        `json:"reading_goal_current"`
	TotalXp                pgtype.Int4        `json:"total_xp"`
	Level                  pgtype.Int4        `json:"level"`
	CurrentStreak          pgtype.Int4        `json:"current_streak"`
	LongestStreak          pgtype.Int4        `json:"longest_streak"`
	LastActivityDate       pgtype.Date        `json:"last_activity_date"`
	ShowOnLeaderboard      pgtype.Bool        `json:"show_on_leaderboard"`
	ReferralCode           pgtype.Text        `json:"referral_code"`
	ReferredBy             pgtype.UUID        `json:"referred_by"`
	ReferralCount          pgtype.Int4        `json:"referral_count"`
	ReferralRewardsClaimed []string           `json:"referral_rewards_claimed"`
	OnboardingCompleted    bool               `json:"onboarding_completed"`
}

type UserAuthorsRead struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	AuthorName     string             `json:"author_name"`
	BooksRead      int32              `json:"books_read"`
	BooksTbr       int32              `json:"books_tbr"`
	FavoriteBookID pgtype.UUID        `json:"favorite_book_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserPreferencesLegacy struct {
	UserID         uuid.UUID          `json:"user_id"`
	Payload        []byte             `json:"payload"`
	MongoUpdatedAt pgtype.Timestamptz `json:"mongo_updated_at"`
	MigratedAt     pgtype.Timestamptz `json:"migrated_at"`
}

type UserSignalProfile struct {
	UserID              uuid.UUID          `json:"user_id"`
	GenreWeights        []byte             `json:"genre_weights"`
	AuthorWeights       []byte             `json:"author_weights"`
	ComputedAt          pgtype.Timestamptz `json:"computed_at"`
	BookshelfHash       pgtype.Text        `json:"bookshelf_hash"`
	VelocitySignal      []byte             `json:"velocity_signal"`
	DiarySignal         []byte             `json:"diary_signal"`
	DiaryEmbedding      pgvector.Vector    `json:"diary_embedding"`
	SocialSignal        []byte             `json:"social_signal"`
	SignalVersion       int32              `json:"signal_version"`
	FastFinishEmbedding pgvector.Vector    `json:"fast_finish_embedding"`
}

type XpTransaction struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	ActionType  string           `json:"action_type"`
	XpAmount    int32            `json:"xp_amount"`
	ReferenceID pgtype.UUID      `json:"reference_id"`
	Metadata    []byte           `json:"metadata"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
