// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const checkBlocked = `-- name: CheckBlocked :one
SELECT EXISTS(
    SELECT 1 FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
)
`

type CheckBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) CheckBlocked(ctx context.Context, arg CheckBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBlocked, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkBlockedEither = `-- name: CheckBlockedEither :one
SELECT EXISTS(
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
)
`

type CheckBlockedEitherParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) CheckBlockedEither(ctx context.Context, arg CheckBlockedEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBlockedEither, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, content_type, content_id, reason, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, reporter_id, content_type, content_id, reason, details, created_at
`

type CreateReportParams struct {
	ReporterID  uuid.UUID   `json:"reporter_id"`
	ContentType string      `json:"content_type"`
	ContentID   string      `json:"content_id"`
	Reason      string      `json:"reason"`
	Details     pgtype.Text `json:"details"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.ContentType,
		arg.ContentID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ContentType,
		&i.ContentID,
		&i.Reason,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}
