// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (
    email, code_hash, expires_at, max_attempts
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email, code_hash, expires_at, attempts, max_attempts, used_at, created_at
`

type CreateOTPParams struct {
	Email       string             `json:"email"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MaxAttempts int32              `json:"max_attempts"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPByEmail = `-- name: DeleteOTPByEmail :exec
DELETE FROM otp_codes
WHERE email = $1
`

func (q *Queries) DeleteOTPByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOTPByEmail, email)
	return err
}

const getOTPByEmail = `-- name: GetOTPByEmail :one
SELECT id, email, code_hash, expires_at, attempts, max_attempts, used_at, created_at FROM otp_codes
WHERE email = $1
  AND used_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOTPByEmail(ctx context.Context, email string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPByEmail, email)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
