// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Going public accepts everyone who was waiting, so no request is orphaned
	// behind a switch the requester cannot see.
	AcceptAllFollowRequests(ctx context.Context, targetID uuid.UUID) error
	// List Books Operations
	AddBookToList(ctx context.Context, arg AddBookToListParams) (ListBook, error)
	AddToBookshelf(ctx context.Context, arg AddToBookshelfParams) (Bookshelf, error)
	AddToFavorites(ctx context.Context, arg AddToFavoritesParams) (Favorite, error)
	// ============================================================================
	// USER XP AND LEVEL MANAGEMENT
	// ============================================================================
	AddXP(ctx context.Context, arg AddXPParams) error
	BlockUser(ctx context.Context, arg BlockUserParams) error
	BumpBookAccess(ctx context.Context, id uuid.UUID) error
	CheckBlocked(ctx context.Context, arg CheckBlockedParams) (bool, error)
	CheckBlockedEither(ctx context.Context, arg CheckBlockedEitherParams) (bool, error)
	CheckBookInList(ctx context.Context, arg CheckBookInListParams) (bool, error)
	CheckCanAccessList(ctx context.Context, arg CheckCanAccessListParams) (bool, error)
	CheckEntryLiked(ctx context.Context, arg CheckEntryLikedParams) (bool, error)
	CheckEntryOwnership(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CheckFavoriteExists(ctx context.Context, arg CheckFavoriteExistsParams) (bool, error)
	CheckFollowRequest(ctx context.Context, arg CheckFollowRequestParams) (bool, error)
	CheckFollowing(ctx context.Context, arg CheckFollowingParams) (bool, error)
	CheckListAccess(ctx context.Context, arg CheckListAccessParams) (bool, error)
	// Authorization Helpers
	CheckListOwnership(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CheckListSaved(ctx context.Context, arg CheckListSavedParams) (bool, error)
	CheckNewActivities(ctx context.Context, arg CheckNewActivitiesParams) (bool, error)
	CheckUserLikedBook(ctx context.Context, arg CheckUserLikedBookParams) (bool, error)
	// Sliding window: deletes books whose last_accessed_at is older than 15 days,
	// excluding any book referenced by bookshelf or likes.
	CleanupStaleBooks(ctx context.Context) (int64, error)
	CountEntryLikes(ctx context.Context, entryID uuid.UUID) (int64, error)
	CountFollowers(ctx context.Context, followingID uuid.UUID) (int64, error)
	CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error)
	// Counts friends actively reading this book right now.
	CountFriendsReadingBook(ctx context.Context, arg CountFriendsReadingBookParams) (int64, error)
	CountIncomingFollowRequests(ctx context.Context, targetID uuid.UUID) (int64, error)
	CountListBooks(ctx context.Context, listID uuid.UUID) (int64, error)
	CountListSaves(ctx context.Context, listID uuid.UUID) (int64, error)
	// Unread badge for the notifications sheet. target_user_id is the "addressed to
	// you" marker — every activity type that carries one (liked_diary_entry,
	// shared_list, shared_book, granted_access) is notification-worthy, so no
	// activity_type filter is needed here.
	CountUnreadActivities(ctx context.Context, targetUserID pgtype.UUID) (int64, error)
	CountUserBooks(ctx context.Context, arg CountUserBooksParams) (int64, error)
	CountUserDiaryEntries(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserFavorites(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserLists(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookFromISBNdb(ctx context.Context, arg CreateBookFromISBNdbParams) (Book, error)
	CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error)
	// ── Follow requests (private profiles) ───────────────────────────────────────
	CreateFollowRequest(ctx context.Context, arg CreateFollowRequestParams) (FollowRequest, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreateOTPWithMetadata(ctx context.Context, arg CreateOTPWithMetadataParams) (OtpCode, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementUserDiaryCount(ctx context.Context, id uuid.UUID) error
	DecrementUserFavoritesCount(ctx context.Context, id uuid.UUID) error
	DecrementUserListsCount(ctx context.Context, id uuid.UUID) error
	// Logout path. Scoped to the caller so one user cannot deregister another's device.
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	// Provider-rejection path (FCM UNREGISTERED, APNs 410 Unregistered). The token
	// is dead regardless of who owns it, so this is intentionally unscoped.
	DeleteDeviceTokenByToken(ctx context.Context, token string) error
	DeleteDiaryEntry(ctx context.Context, id uuid.UUID) error
	DeleteFollowRequest(ctx context.Context, arg DeleteFollowRequestParams) error
	DeleteList(ctx context.Context, id uuid.UUID) error
	DeleteOTPByEmail(ctx context.Context, email string) error
	DeleteStaleDeviceTokens(ctx context.Context, updatedAt pgtype.Timestamptz) error
	DeleteUserActivities(ctx context.Context, arg DeleteUserActivitiesParams) error
	FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error)
	GetActivityByID(ctx context.Context, id uuid.UUID) (Activity, error)
	GetBookByGoogleID(ctx context.Context, googleBooksID pgtype.Text) (Book, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (Book, error)
	GetBookByISBN(ctx context.Context, isbn13 pgtype.Text) (Book, error)
	GetBookBySlug(ctx context.Context, slug string) (Book, error)
	GetBookDiaryEntries(ctx context.Context, arg GetBookDiaryEntriesParams) ([]GetBookDiaryEntriesRow, error)
	GetBookEmbeddingsByIDs(ctx context.Context, dollar_1 []string) ([]GetBookEmbeddingsByIDsRow, error)
	// viewer_id filters out reviews across a block in either direction;
	// anonymous viewers pass the nil UUID (matches no blocks rows).
	GetBookReviews(ctx context.Context, arg GetBookReviewsParams) ([]GetBookReviewsRow, error)
	// Reviews on a book authored by users the current viewer follows.
	// $1 = book_id, $2 = viewer's user_id (follower).
	GetBookReviewsByFriends(ctx context.Context, arg GetBookReviewsByFriendsParams) ([]GetBookReviewsByFriendsRow, error)
	GetBooksByAuthor(ctx context.Context, arg GetBooksByAuthorParams) ([]Book, error)
	GetBookshelfEntry(ctx context.Context, arg GetBookshelfEntryParams) (Bookshelf, error)
	// A streak day is a UTC day whose NET pages read is positive. Correcting a page
	// count downward (an error fix, net <= 0 for the day) is not reading progress, so
	// it neither starts nor extends a streak.
	GetCurrentStreak(ctx context.Context, userID uuid.UUID) (int32, error)
	GetCurrentlyReading(ctx context.Context, userID uuid.UUID) ([]GetCurrentlyReadingRow, error)
	GetDiaryEmbeddingsForUser(ctx context.Context, userID uuid.UUID) ([]GetDiaryEmbeddingsForUserRow, error)
	GetDiaryEntriesWithoutEmbedding(ctx context.Context) ([]GetDiaryEntriesWithoutEmbeddingRow, error)
	GetDiaryEntryByID(ctx context.Context, id uuid.UUID) (DiaryEntry, error)
	GetEntryLikes(ctx context.Context, entryID uuid.UUID) ([]GetEntryLikesRow, error)
	GetFavoriteByUserAndBook(ctx context.Context, arg GetFavoriteByUserAndBookParams) (Favorite, error)
	GetFollowers(ctx context.Context, arg GetFollowersParams) ([]User, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]User, error)
	GetFollowingActivities(ctx context.Context, arg GetFollowingActivitiesParams) ([]GetFollowingActivitiesRow, error)
	// ============================================================================
	// LEADERBOARD QUERIES
	// ============================================================================
	// Includes the caller and everyone they follow, ranked together.
	GetFriendsLeaderboard(ctx context.Context, arg GetFriendsLeaderboardParams) ([]LeaderboardStat, error)
	// Friends (people the viewer follows) who have this book on their shelf
	// with status 'reading' or 'to-read', prioritised by active readers first.
	// $1 = viewer's user_id (follower), $2 = book_id.
	GetFriendsReadingBook(ctx context.Context, arg GetFriendsReadingBookParams) ([]GetFriendsReadingBookRow, error)
	GetGlobalLeaderboard(ctx context.Context, limit int32) ([]LeaderboardStat, error)
	GetLastLoggedBook(ctx context.Context, userID uuid.UUID) (GetLastLoggedBookRow, error)
	GetLastLoggedBookToday(ctx context.Context, userID uuid.UUID) (GetLastLoggedBookTodayRow, error)
	GetLatestBooks(ctx context.Context, arg GetLatestBooksParams) ([]Book, error)
	GetLeaderboardByDimension(ctx context.Context, arg GetLeaderboardByDimensionParams) ([]LeaderboardStat, error)
	GetListAccessUsers(ctx context.Context, listID uuid.UUID) ([]GetListAccessUsersRow, error)
	GetListBooks(ctx context.Context, listID uuid.UUID) ([]GetListBooksRow, error)
	GetListByID(ctx context.Context, id uuid.UUID) (List, error)
	// Prefer stored cover_url; otherwise synthesize a thumbnail URL from Google Books
	// id or ISBN so list cards still show art when cover_url was never backfilled.
	GetListCoverURLs(ctx context.Context, listID uuid.UUID) ([]string, error)
	GetListOwnerUsername(ctx context.Context, id uuid.UUID) (string, error)
	GetOTPByEmail(ctx context.Context, email string) (OtpCode, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPopularBooks(ctx context.Context, arg GetPopularBooksParams) ([]Book, error)
	GetRandomBooks(ctx context.Context, limit int32) ([]Book, error)
	// Per-day page totals across an inclusive date range, for the GitHub-style
	// reading heatmap. Only days with at least one logged entry are returned; the
	// handler fills the gaps with zeros.
	GetReadingActivityRange(ctx context.Context, arg GetReadingActivityRangeParams) ([]GetReadingActivityRangeRow, error)
	// Reading progress snapshot for a book on a single user's shelf.
	GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (GetReadingProgressRow, error)
	GetReferralStats(ctx context.Context, referredBy pgtype.UUID) (GetReferralStatsRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTodayReadingStats(ctx context.Context, userID uuid.UUID) (GetTodayReadingStatsRow, error)
	GetUserActivities(ctx context.Context, arg GetUserActivitiesParams) ([]GetUserActivitiesRow, error)
	GetUserAuthors(ctx context.Context, userID uuid.UUID) ([]GetUserAuthorsRow, error)
	// Most-recently-touched first: a freshly added/updated book (updated_at = NOW())
	// always lands at the top of its tab.
	GetUserBookshelf(ctx context.Context, arg GetUserBookshelfParams) ([]GetUserBookshelfRow, error)
	GetUserByAppleUserID(ctx context.Context, appleUserID pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByReferralCode(ctx context.Context, referralCode pgtype.Text) (GetUserByReferralCodeRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserDNF(ctx context.Context, userID uuid.UUID) ([]GetUserDNFRow, error)
	GetUserDiaryEntries(ctx context.Context, arg GetUserDiaryEntriesParams) ([]GetUserDiaryEntriesRow, error)
	GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]GetUserFavoritesRow, error)
	// ============================================================================
	// LEADERBOARD STATS QUERIES
	// ============================================================================
	GetUserLeaderboardStats(ctx context.Context, userID uuid.UUID) (LeaderboardStat, error)
	GetUserLikes(ctx context.Context, arg GetUserLikesParams) ([]GetUserLikesRow, error)
	GetUserLists(ctx context.Context, arg GetUserListsParams) ([]GetUserListsRow, error)
	// Live books-read count and total pages read, computed from the shelf so the
	// profile never shows the stale cached `users.books_read_count` / `total_pages_read`.
	GetUserReadStats(ctx context.Context, userID uuid.UUID) (GetUserReadStatsRow, error)
	GetUserReferralCode(ctx context.Context, id uuid.UUID) (GetUserReferralCodeRow, error)
	GetUserReferrals(ctx context.Context, arg GetUserReferralsParams) ([]GetUserReferralsRow, error)
	GetUserSavedLists(ctx context.Context, arg GetUserSavedListsParams) ([]GetUserSavedListsRow, error)
	// Most-recently-touched first so a book just marked to-read lands on top.
	GetUserTBR(ctx context.Context, userID uuid.UUID) ([]GetUserTBRRow, error)
	GetUserXP(ctx context.Context, id uuid.UUID) (GetUserXPRow, error)
	GetUserXPHistory(ctx context.Context, arg GetUserXPHistoryParams) ([]GetUserXPHistoryRow, error)
	GetUserXPToday(ctx context.Context, userID uuid.UUID) (int32, error)
	GetWeeklyReadingStats(ctx context.Context, userID uuid.UUID) ([]GetWeeklyReadingStatsRow, error)
	// Access Control
	GrantListAccess(ctx context.Context, arg GrantListAccessParams) (ListAccess, error)
	HasClaimedReferralReward(ctx context.Context, arg HasClaimedReferralRewardParams) (bool, error)
	IncrementBookViews(ctx context.Context, id uuid.UUID) error
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error
	IncrementReferralCount(ctx context.Context, id uuid.UUID) error
	IncrementUserDiaryCount(ctx context.Context, id uuid.UUID) error
	IncrementUserFavoritesCount(ctx context.Context, id uuid.UUID) error
	IncrementUserListsCount(ctx context.Context, id uuid.UUID) error
	LikeBook(ctx context.Context, arg LikeBookParams) (Like, error)
	// Likes
	LikeDiaryEntry(ctx context.Context, arg LikeDiaryEntryParams) (DiaryEntryLike, error)
	LinkAppleUserID(ctx context.Context, arg LinkAppleUserIDParams) error
	ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ListIncomingFollowRequests(ctx context.Context, arg ListIncomingFollowRequestsParams) ([]ListIncomingFollowRequestsRow, error)
	LogReadingProgress(ctx context.Context, arg LogReadingProgressParams) error
	// ============================================================================
	// XP TRANSACTION LOGGING
	// ============================================================================
	LogXPTransaction(ctx context.Context, arg LogXPTransactionParams) error
	// Called when the sheet opens. Idempotent; leaves already-read rows alone so a
	// reopen does not churn timestamps.
	MarkActivitiesRead(ctx context.Context, targetUserID pgtype.UUID) error
	MarkAsFinished(ctx context.Context, arg MarkAsFinishedParams) (Bookshelf, error)
	MarkAsStarted(ctx context.Context, arg MarkAsStartedParams) (Bookshelf, error)
	MarkOTPUsed(ctx context.Context, id uuid.UUID) error
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkReferralRewardClaimed(ctx context.Context, arg MarkReferralRewardClaimedParams) error
	RebuildAllLeaderboardStats(ctx context.Context) error
	RebuildUserLeaderboardStats(ctx context.Context, id uuid.UUID) (LeaderboardStat, error)
	RecordAccountDeletion(ctx context.Context, arg RecordAccountDeletionParams) error
	RemoveBookFromList(ctx context.Context, arg RemoveBookFromListParams) error
	RemoveFromBookshelf(ctx context.Context, arg RemoveFromBookshelfParams) error
	RemoveFromFavorites(ctx context.Context, arg RemoveFromFavoritesParams) error
	ReorderFavorites(ctx context.Context, arg ReorderFavoritesParams) error
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeListAccess(ctx context.Context, arg RevokeListAccessParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	// Saved Lists
	SaveList(ctx context.Context, arg SaveListParams) (SavedList, error)
	SearchBooksInDB(ctx context.Context, arg SearchBooksInDBParams) ([]Book, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetUserReferredBy(ctx context.Context, arg SetUserReferredByParams) error
	SetUserVisibility(ctx context.Context, arg SetUserVisibilityParams) (User, error)
	// Soft-delete the user and free their email/username so they (or anyone) can
	// re-register with the same identifiers. The original values are preserved in
	// the account_deletions audit table by RecordAccountDeletion (called first).
	// The UUID-based placeholders are deterministic and lowercase, satisfying the
	// column-level UNIQUE constraints and the username_lowercase CHECK.
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UnlikeBook(ctx context.Context, arg UnlikeBookParams) error
	UnlikeDiaryEntry(ctx context.Context, arg UnlikeDiaryEntryParams) error
	UnsaveList(ctx context.Context, arg UnsaveListParams) error
	UpdateBookshelfRating(ctx context.Context, arg UpdateBookshelfRatingParams) (Bookshelf, error)
	UpdateBookshelfStatus(ctx context.Context, arg UpdateBookshelfStatusParams) (Bookshelf, error)
	UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (DiaryEntry, error)
	UpdateDiaryEntryEmbedding(ctx context.Context, arg UpdateDiaryEntryEmbeddingParams) error
	UpdateFavoriteNote(ctx context.Context, arg UpdateFavoriteNoteParams) (Favorite, error)
	UpdateLeaderboardRankings(ctx context.Context) error
	UpdateList(ctx context.Context, arg UpdateListParams) (List, error)
	UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) (Bookshelf, error)
	UpdateRefreshTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateTBRNotes(ctx context.Context, arg UpdateTBRNotesParams) (Bookshelf, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserGenres(ctx context.Context, arg UpdateUserGenresParams) (User, error)
	UpdateUserLastActive(ctx context.Context, id uuid.UUID) error
	UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error
	// ============================================================================
	// STREAK MANAGEMENT
	// ============================================================================
	UpdateUserStreak(ctx context.Context, id uuid.UUID) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
	UpsertAuthorRead(ctx context.Context, arg UpsertAuthorReadParams) (UserAuthorsRead, error)
	// Conflict target is `token` alone: a push token belongs to a device, so when a
	// different account signs in on that device the row must change hands rather
	// than accumulate a second owner. See migrations/000036 for the full rationale.
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	VibeSearchBooks(ctx context.Context, arg VibeSearchBooksParams) ([]VibeSearchBooksRow, error)
	// Still marked "reading", started before the month ended, and untouched since
	// stall_before. Ordered by how little of it was read — the most abandoned one
	// makes the best chapter.
	WrappedAbandoned(ctx context.Context, arg WrappedAbandonedParams) (WrappedAbandonedRow, error)
	WrappedBooksFinished(ctx context.Context, arg WrappedBooksFinishedParams) (int32, error)
	// Only days with entries come back; the handler fills the rest of the month
	// with zeros so the calendar grid is always month-length.
	WrappedDailyPages(ctx context.Context, arg WrappedDailyPagesParams) ([]WrappedDailyPagesRow, error)
	// Categories weighted by pages read, not by book count: a 900-page epic should
	// outweigh a novella. The handler turns these into percentages.
	WrappedGenres(ctx context.Context, arg WrappedGenresParams) ([]WrappedGenresRow, error)
	WrappedHourHistogram(ctx context.Context, arg WrappedHourHistogramParams) ([]WrappedHourHistogramRow, error)
	// Where the reader landed against everyone who read anything that month.
	WrappedRank(ctx context.Context, arg WrappedRankParams) (WrappedRankRow, error)
	// Pages are attributed to every credited author of a book; a co-authored book
	// counts once for each of them, which is how the reader thinks about it.
	WrappedTopAuthors(ctx context.Context, arg WrappedTopAuthorsParams) ([]WrappedTopAuthorsRow, error)
	WrappedTopBooks(ctx context.Context, arg WrappedTopBooksParams) ([]WrappedTopBooksRow, error)
	// The month's best book: highest rating finished inside the window, most
	// recent finish breaking ties. Its review is the chapter's pull quote.
	WrappedTopRated(ctx context.Context, arg WrappedTopRatedParams) (WrappedTopRatedRow, error)
	// Monthly Wrapped aggregates.
	//
	// Every query is bounded by an explicit [month_start, month_end) window the
	// handler computes in the reader's own timezone, and buckets days/hours in
	// that same zone: a book read at 1am in Delhi belongs to the Delhi night, not
	// to the previous UTC day.
	//
	// pages_delta can be negative (a reader correcting a page count downward), so
	// every page total clamps with GREATEST(pages_delta, 0) — a correction is not
	// reading.
	WrappedTotals(ctx context.Context, arg WrappedTotalsParams) (WrappedTotalsRow, error)
}

var _ Querier = (*Queries)(nil)
