// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReadLinksByBookID = `-- name: GetReadLinksByBookID :one
SELECT book_id, google_play_buy_link, google_play_checked_at, apple_books_url, apple_books_checked_at, is_public_domain, gutenberg_id, gutenberg_html_url, gutenberg_epub_url, gutenberg_checked_at, updated_at FROM book_read_links WHERE book_id = $1
`

func (q *Queries) GetReadLinksByBookID(ctx context.Context, bookID uuid.UUID) (BookReadLink, error) {
	row := q.db.QueryRow(ctx, getReadLinksByBookID, bookID)
	var i BookReadLink
	err := row.Scan(
		&i.BookID,
		&i.GooglePlayBuyLink,
		&i.GooglePlayCheckedAt,
		&i.AppleBooksUrl,
		&i.AppleBooksCheckedAt,
		&i.IsPublicDomain,
		&i.GutenbergID,
		&i.GutenbergHtmlUrl,
		&i.GutenbergEpubUrl,
		&i.GutenbergCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooksNeedingGutenbergCheck = `-- name: ListBooksNeedingGutenbergCheck :many
SELECT b.id, b.title, b.authors FROM books b
LEFT JOIN book_read_links rl ON rl.book_id = b.id
WHERE rl.gutenberg_checked_at IS NULL
   OR rl.gutenberg_checked_at < NOW() - INTERVAL '30 days'
ORDER BY b.last_accessed_at DESC NULLS LAST, b.view_count DESC NULLS LAST
LIMIT $1
`

type ListBooksNeedingGutenbergCheckRow struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Authors []string  `json:"authors"`
}

// Most recently opened first, so a capped nightly run covers the books
// people actually look at.
func (q *Queries) ListBooksNeedingGutenbergCheck(ctx context.Context, limit int32) ([]ListBooksNeedingGutenbergCheckRow, error) {
	rows, err := q.db.Query(ctx, listBooksNeedingGutenbergCheck, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksNeedingGutenbergCheckRow{}
	for rows.Next() {
		var i ListBooksNeedingGutenbergCheckRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Authors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublicDomain = `-- name: UpsertPublicDomain :one
INSERT INTO book_read_links (
    book_id, is_public_domain, gutenberg_id, gutenberg_html_url, gutenberg_epub_url, gutenberg_checked_at
) VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (book_id) DO UPDATE SET
    is_public_domain     = EXCLUDED.is_public_domain,
    gutenberg_id         = EXCLUDED.gutenberg_id,
    gutenberg_html_url   = EXCLUDED.gutenberg_html_url,
    gutenberg_epub_url   = EXCLUDED.gutenberg_epub_url,
    gutenberg_checked_at = NOW(),
    updated_at           = NOW()
RETURNING book_id, google_play_buy_link, google_play_checked_at, apple_books_url, apple_books_checked_at, is_public_domain, gutenberg_id, gutenberg_html_url, gutenberg_epub_url, gutenberg_checked_at, updated_at
`

type UpsertPublicDomainParams struct {
	BookID           uuid.UUID   `json:"book_id"`
	IsPublicDomain   bool        `json:"is_public_domain"`
	GutenbergID      pgtype.Int4 `json:"gutenberg_id"`
	GutenbergHtmlUrl pgtype.Text `json:"gutenberg_html_url"`
	GutenbergEpubUrl pgtype.Text `json:"gutenberg_epub_url"`
}

// Gutenberg half only; store links are left alone.
func (q *Queries) UpsertPublicDomain(ctx context.Context, arg UpsertPublicDomainParams) (BookReadLink, error) {
	row := q.db.QueryRow(ctx, upsertPublicDomain,
		arg.BookID,
		arg.IsPublicDomain,
		arg.GutenbergID,
		arg.GutenbergHtmlUrl,
		arg.GutenbergEpubUrl,
	)
	var i BookReadLink
	err := row.Scan(
		&i.BookID,
		&i.GooglePlayBuyLink,
		&i.GooglePlayCheckedAt,
		&i.AppleBooksUrl,
		&i.AppleBooksCheckedAt,
		&i.IsPublicDomain,
		&i.GutenbergID,
		&i.GutenbergHtmlUrl,
		&i.GutenbergEpubUrl,
		&i.GutenbergCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStoreLinks = `-- name: UpsertStoreLinks :one
INSERT INTO book_read_links (
    book_id, google_play_buy_link, google_play_checked_at, apple_books_url, apple_books_checked_at
) VALUES (
    $1,
    $2, CASE WHEN $3::boolean THEN NOW() END,
    $4,      CASE WHEN $5::boolean THEN NOW() END
)
ON CONFLICT (book_id) DO UPDATE SET
    google_play_buy_link   = CASE WHEN $3::boolean THEN EXCLUDED.google_play_buy_link ELSE book_read_links.google_play_buy_link END,
    google_play_checked_at = CASE WHEN $3::boolean THEN NOW() ELSE book_read_links.google_play_checked_at END,
    apple_books_url        = CASE WHEN $5::boolean THEN EXCLUDED.apple_books_url ELSE book_read_links.apple_books_url END,
    apple_books_checked_at = CASE WHEN $5::boolean THEN NOW() ELSE book_read_links.apple_books_checked_at END,
    updated_at             = NOW()
RETURNING book_id, google_play_buy_link, google_play_checked_at, apple_books_url, apple_books_checked_at, is_public_domain, gutenberg_id, gutenberg_html_url, gutenberg_epub_url, gutenberg_checked_at, updated_at
`

type UpsertStoreLinksParams struct {
	BookID            uuid.UUID   `json:"book_id"`
	GooglePlayBuyLink pgtype.Text `json:"google_play_buy_link"`
	GoogleChecked     bool        `json:"google_checked"`
	AppleBooksUrl     pgtype.Text `json:"apple_books_url"`
	AppleChecked      bool        `json:"apple_checked"`
}

// Writes only the stores whose lookup answered (google_checked /
// apple_checked); the others keep their link and checked_at untouched.
func (q *Queries) UpsertStoreLinks(ctx context.Context, arg UpsertStoreLinksParams) (BookReadLink, error) {
	row := q.db.QueryRow(ctx, upsertStoreLinks,
		arg.BookID,
		arg.GooglePlayBuyLink,
		arg.GoogleChecked,
		arg.AppleBooksUrl,
		arg.AppleChecked,
	)
	var i BookReadLink
	err := row.Scan(
		&i.BookID,
		&i.GooglePlayBuyLink,
		&i.GooglePlayCheckedAt,
		&i.AppleBooksUrl,
		&i.AppleBooksCheckedAt,
		&i.IsPublicDomain,
		&i.GutenbergID,
		&i.GutenbergHtmlUrl,
		&i.GutenbergEpubUrl,
		&i.GutenbergCheckedAt,
		&i.UpdatedAt,
	)
	return i, err
}
