// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referral.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReferralStats = `-- name: GetReferralStats :one
SELECT
  COUNT(*)                                             AS total_referrals,
  COUNT(*) FILTER (WHERE COALESCE(total_xp, 0) > 0)   AS active_referrals,
  COUNT(*) FILTER (WHERE COALESCE(current_streak, 0) >= 30) AS long_term_referrals
FROM users
WHERE referred_by = $1 AND deleted_at IS NULL
`

type GetReferralStatsRow struct {
	TotalReferrals    int64 `json:"total_referrals"`
	ActiveReferrals   int64 `json:"active_referrals"`
	LongTermReferrals int64 `json:"long_term_referrals"`
}

func (q *Queries) GetReferralStats(ctx context.Context, referredBy pgtype.UUID) (GetReferralStatsRow, error) {
	row := q.db.QueryRow(ctx, getReferralStats, referredBy)
	var i GetReferralStatsRow
	err := row.Scan(&i.TotalReferrals, &i.ActiveReferrals, &i.LongTermReferrals)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, username, email
FROM users
WHERE referral_code = $1 AND deleted_at IS NULL
`

type GetUserByReferralCodeRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode pgtype.Text) (GetUserByReferralCodeRow, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i GetUserByReferralCodeRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const getUserReferralCode = `-- name: GetUserReferralCode :one
SELECT id, username, referral_code, referral_count
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserReferralCodeRow struct {
	ID            uuid.UUID   `json:"id"`
	Username      string      `json:"username"`
	ReferralCode  pgtype.Text `json:"referral_code"`
	ReferralCount pgtype.Int4 `json:"referral_count"`
}

func (q *Queries) GetUserReferralCode(ctx context.Context, id uuid.UUID) (GetUserReferralCodeRow, error) {
	row := q.db.QueryRow(ctx, getUserReferralCode, id)
	var i GetUserReferralCodeRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ReferralCode,
		&i.ReferralCount,
	)
	return i, err
}

const getUserReferrals = `-- name: GetUserReferrals :many
SELECT id, username, email, created_at, total_xp, level, current_streak
FROM users
WHERE referred_by = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetUserReferralsParams struct {
	ReferredBy pgtype.UUID `json:"referred_by"`
	Limit      int32       `json:"limit"`
}

type GetUserReferralsRow struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TotalXp       pgtype.Int4        `json:"total_xp"`
	Level         pgtype.Int4        `json:"level"`
	CurrentStreak pgtype.Int4        `json:"current_streak"`
}

func (q *Queries) GetUserReferrals(ctx context.Context, arg GetUserReferralsParams) ([]GetUserReferralsRow, error) {
	rows, err := q.db.Query(ctx, getUserReferrals, arg.ReferredBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserReferralsRow{}
	for rows.Next() {
		var i GetUserReferralsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.TotalXp,
			&i.Level,
			&i.CurrentStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasClaimedReferralReward = `-- name: HasClaimedReferralReward :one
SELECT $2::text = ANY(COALESCE(referral_rewards_claimed, '{}')) AS claimed
FROM users
WHERE id = $1
`

type HasClaimedReferralRewardParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) HasClaimedReferralReward(ctx context.Context, arg HasClaimedReferralRewardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasClaimedReferralReward, arg.ID, arg.Column2)
	var claimed bool
	err := row.Scan(&claimed)
	return claimed, err
}

const incrementReferralCount = `-- name: IncrementReferralCount :exec
UPDATE users
SET referral_count = COALESCE(referral_count, 0) + 1
WHERE id = $1
`

func (q *Queries) IncrementReferralCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralCount, id)
	return err
}

const markReferralRewardClaimed = `-- name: MarkReferralRewardClaimed :exec
UPDATE users
SET referral_rewards_claimed = array_append(COALESCE(referral_rewards_claimed, '{}'), $2::text)
WHERE id = $1
`

type MarkReferralRewardClaimedParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) MarkReferralRewardClaimed(ctx context.Context, arg MarkReferralRewardClaimedParams) error {
	_, err := q.db.Exec(ctx, markReferralRewardClaimed, arg.ID, arg.Column2)
	return err
}

const setUserReferredBy = `-- name: SetUserReferredBy :exec
UPDATE users
SET referred_by = $2
WHERE id = $1
`

type SetUserReferredByParams struct {
	ID         uuid.UUID   `json:"id"`
	ReferredBy pgtype.UUID `json:"referred_by"`
}

func (q *Queries) SetUserReferredBy(ctx context.Context, arg SetUserReferredByParams) error {
	_, err := q.db.Exec(ctx, setUserReferredBy, arg.ID, arg.ReferredBy)
	return err
}
