// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscription = `-- name: GetSubscription :one
SELECT user_id, store, store_id, product_id, expires_at, auto_renew, environment, created_at, updated_at FROM subscriptions
WHERE user_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Store,
		&i.StoreID,
		&i.ProductID,
		&i.ExpiresAt,
		&i.AutoRenew,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionByStoreID = `-- name: UpdateSubscriptionByStoreID :one
UPDATE subscriptions
SET product_id = $3,
    expires_at = $4,
    auto_renew = $5,
    updated_at = NOW()
WHERE store = $1 AND store_id = $2
RETURNING user_id
`

type UpdateSubscriptionByStoreIDParams struct {
	Store     string             `json:"store"`
	StoreID   string             `json:"store_id"`
	ProductID string             `json:"product_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	AutoRenew bool               `json:"auto_renew"`
}

// Webhook path: the store tells us about a receipt, not a user. Returns the
// owner so the analytics event can be attributed; ErrNoRows when nobody has
// linked this receipt yet.
func (q *Queries) UpdateSubscriptionByStoreID(ctx context.Context, arg UpdateSubscriptionByStoreIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionByStoreID,
		arg.Store,
		arg.StoreID,
		arg.ProductID,
		arg.ExpiresAt,
		arg.AutoRenew,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (user_id, store, store_id, product_id, expires_at, auto_renew, environment)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE
SET store       = EXCLUDED.store,
    store_id    = EXCLUDED.store_id,
    product_id  = EXCLUDED.product_id,
    expires_at  = EXCLUDED.expires_at,
    auto_renew  = EXCLUDED.auto_renew,
    environment = EXCLUDED.environment,
    updated_at  = NOW()
RETURNING user_id, store, store_id, product_id, expires_at, auto_renew, environment, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	Store       string             `json:"store"`
	StoreID     string             `json:"store_id"`
	ProductID   string             `json:"product_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AutoRenew   bool               `json:"auto_renew"`
	Environment string             `json:"environment"`
}

// Client path: a signed-in reader hands us a receipt. Conflict on user_id so a
// plan change or a second store simply replaces what backs the entitlement.
// The (store, store_id) unique index is deliberately NOT a conflict target:
// a receipt already linked to another account must fail, not move.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.Store,
		arg.StoreID,
		arg.ProductID,
		arg.ExpiresAt,
		arg.AutoRenew,
		arg.Environment,
	)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Store,
		&i.StoreID,
		&i.ProductID,
		&i.ExpiresAt,
		&i.AutoRenew,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
