// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thoughts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const checkThoughtLiked = `-- name: CheckThoughtLiked :one
SELECT EXISTS(
    SELECT 1 FROM thought_likes
    WHERE user_id = $1 AND thought_id = $2
)
`

type CheckThoughtLikedParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

func (q *Queries) CheckThoughtLiked(ctx context.Context, arg CheckThoughtLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkThoughtLiked, arg.UserID, arg.ThoughtID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkThoughtOwnership = `-- name: CheckThoughtOwnership :one
SELECT user_id FROM thoughts
WHERE id = $1
`

func (q *Queries) CheckThoughtOwnership(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkThoughtOwnership, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const checkThoughtReposted = `-- name: CheckThoughtReposted :one
SELECT EXISTS(
    SELECT 1 FROM thought_reposts
    WHERE user_id = $1 AND thought_id = $2
)
`

type CheckThoughtRepostedParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

func (q *Queries) CheckThoughtReposted(ctx context.Context, arg CheckThoughtRepostedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkThoughtReposted, arg.UserID, arg.ThoughtID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countThoughtLikes = `-- name: CountThoughtLikes :one
SELECT COUNT(*) FROM thought_likes
WHERE thought_id = $1
`

func (q *Queries) CountThoughtLikes(ctx context.Context, thoughtID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countThoughtLikes, thoughtID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThoughtReposts = `-- name: CountThoughtReposts :one
SELECT COUNT(*) FROM thought_reposts
WHERE thought_id = $1
`

func (q *Queries) CountThoughtReposts(ctx context.Context, thoughtID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countThoughtReposts, thoughtID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreadFollowUps = `-- name: CountThreadFollowUps :one
SELECT COUNT(*) FROM thoughts
WHERE thread_root_id = $1
`

func (q *Queries) CountThreadFollowUps(ctx context.Context, threadRootID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadFollowUps, threadRootID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserThoughts = `-- name: CountUserThoughts :one
SELECT COUNT(*) FROM thoughts
WHERE user_id = $1 AND thread_root_id IS NULL
`

// Thoughts that start a thread or stand alone; follow-ups are part of those.
func (q *Queries) CountUserThoughts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserThoughts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserThoughtsFeed = `-- name: CountUserThoughtsFeed :one
SELECT
    (SELECT COUNT(*) FROM thoughts t
      WHERE t.user_id = $1
        AND t.thread_root_id IS NULL
        AND (t.is_private = false OR t.user_id = $2))
  + (SELECT COUNT(*) FROM thought_reposts r WHERE r.user_id = $1)
`

type CountUserThoughtsFeedParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ViewerID  uuid.UUID `json:"viewer_id"`
}

// ponytail: counts reposts before the read-time visibility filter, so a page
// count can run one short page long; filter here too if that ever shows.
func (q *Queries) CountUserThoughtsFeed(ctx context.Context, arg CountUserThoughtsFeedParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUserThoughtsFeed, arg.ProfileID, arg.ViewerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createThought = `-- name: CreateThought :one
INSERT INTO thoughts (user_id, book_id, title, content, is_private, rating, thread_root_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text, thread_root_id
`

type CreateThoughtParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	BookID       pgtype.UUID `json:"book_id"`
	Title        pgtype.Text `json:"title"`
	Content      string      `json:"content"`
	IsPrivate    bool        `json:"is_private"`
	Rating       pgtype.Int4 `json:"rating"`
	ThreadRootID pgtype.UUID `json:"thread_root_id"`
}

func (q *Queries) CreateThought(ctx context.Context, arg CreateThoughtParams) (Thought, error) {
	row := q.db.QueryRow(ctx, createThought,
		arg.UserID,
		arg.BookID,
		arg.Title,
		arg.Content,
		arg.IsPrivate,
		arg.Rating,
		arg.ThreadRootID,
	)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
		&i.ThreadRootID,
	)
	return i, err
}

const decrementUserThoughtCount = `-- name: DecrementUserThoughtCount :exec
UPDATE users
SET thoughts_count = GREATEST(thoughts_count - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementUserThoughtCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementUserThoughtCount, id)
	return err
}

const deleteRepostActivity = `-- name: DeleteRepostActivity :exec
DELETE FROM activities
WHERE user_id = $1 AND thought_id = $2 AND activity_type = 'reposted_thought'
`

type DeleteRepostActivityParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ThoughtID pgtype.UUID `json:"thought_id"`
}

// Undoing a repost takes back the "reposted your thought" notification too.
func (q *Queries) DeleteRepostActivity(ctx context.Context, arg DeleteRepostActivityParams) error {
	_, err := q.db.Exec(ctx, deleteRepostActivity, arg.UserID, arg.ThoughtID)
	return err
}

const deleteThought = `-- name: DeleteThought :exec
DELETE FROM thoughts
WHERE id = $1
`

func (q *Queries) DeleteThought(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteThought, id)
	return err
}

const getBookThoughts = `-- name: GetBookThoughts :many
SELECT
    de.id,
    de.user_id,
    de.book_id,
    de.title,
    de.content,
    de.is_private,
    de.rating,
    de.created_at,
    de.updated_at,
    u.username,
    u.name,
    u.avatar_url
FROM thoughts de
JOIN users u ON de.user_id = u.id
WHERE de.book_id = $1 AND de.is_private = false
  AND de.thread_root_id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM blocks bl
      WHERE (bl.blocker_id = $2 AND bl.blocked_id = de.user_id)
         OR (bl.blocker_id = de.user_id AND bl.blocked_id = $2)
  )
ORDER BY de.created_at DESC
LIMIT $4 OFFSET $3
`

type GetBookThoughtsParams struct {
	BookID   pgtype.UUID `json:"book_id"`
	ViewerID uuid.UUID   `json:"viewer_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

type GetBookThoughtsRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	BookID    pgtype.UUID      `json:"book_id"`
	Title     pgtype.Text      `json:"title"`
	Content   string           `json:"content"`
	IsPrivate bool             `json:"is_private"`
	Rating    pgtype.Int4      `json:"rating"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Username  string           `json:"username"`
	Name      pgtype.Text      `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
}

// Follow-ups are left out: they belong to their thread, not to the book page.
func (q *Queries) GetBookThoughts(ctx context.Context, arg GetBookThoughtsParams) ([]GetBookThoughtsRow, error) {
	rows, err := q.db.Query(ctx, getBookThoughts,
		arg.BookID,
		arg.ViewerID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookThoughtsRow{}
	for rows.Next() {
		var i GetBookThoughtsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Content,
			&i.IsPrivate,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThoughtByID = `-- name: GetThoughtByID :one
SELECT id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text, thread_root_id FROM thoughts
WHERE id = $1
`

func (q *Queries) GetThoughtByID(ctx context.Context, id uuid.UUID) (Thought, error) {
	row := q.db.QueryRow(ctx, getThoughtByID, id)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
		&i.ThreadRootID,
	)
	return i, err
}

const getThoughtEmbeddingsForUser = `-- name: GetThoughtEmbeddingsForUser :many
SELECT id, embedding_text, embedding
FROM thoughts
WHERE user_id = $1
  AND embedding IS NOT NULL
ORDER BY created_at DESC
LIMIT 50
`

type GetThoughtEmbeddingsForUserRow struct {
	ID            uuid.UUID       `json:"id"`
	EmbeddingText pgtype.Text     `json:"embedding_text"`
	Embedding     pgvector.Vector `json:"embedding"`
}

func (q *Queries) GetThoughtEmbeddingsForUser(ctx context.Context, userID uuid.UUID) ([]GetThoughtEmbeddingsForUserRow, error) {
	rows, err := q.db.Query(ctx, getThoughtEmbeddingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThoughtEmbeddingsForUserRow{}
	for rows.Next() {
		var i GetThoughtEmbeddingsForUserRow
		if err := rows.Scan(&i.ID, &i.EmbeddingText, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThoughtLikes = `-- name: GetThoughtLikes :many
SELECT
    tl.id,
    tl.user_id,
    tl.thought_id,
    tl.created_at,
    u.username,
    u.name,
    u.avatar_url
FROM thought_likes tl
JOIN users u ON tl.user_id = u.id
WHERE tl.thought_id = $1
ORDER BY tl.created_at DESC
`

type GetThoughtLikesRow struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	ThoughtID uuid.UUID        `json:"thought_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Username  string           `json:"username"`
	Name      pgtype.Text      `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
}

func (q *Queries) GetThoughtLikes(ctx context.Context, thoughtID uuid.UUID) ([]GetThoughtLikesRow, error) {
	rows, err := q.db.Query(ctx, getThoughtLikes, thoughtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThoughtLikesRow{}
	for rows.Next() {
		var i GetThoughtLikesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ThoughtID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThoughtThread = `-- name: GetThoughtThread :many
SELECT
    t.id,
    t.user_id,
    t.book_id,
    t.title,
    t.content,
    t.is_private,
    t.rating,
    t.thread_root_id,
    t.created_at,
    t.updated_at,
    u.username,
    u.name,
    u.avatar_url,
    b.title     AS book_title,
    b.slug      AS book_slug,
    b.authors   AS book_authors,
    b.cover_url AS book_cover_url,
    (SELECT COUNT(*) FROM thought_likes l   WHERE l.thought_id = t.id)   AS likes_count,
    (SELECT COUNT(*) FROM thought_reposts rp WHERE rp.thought_id = t.id) AS reposts_count,
    EXISTS(SELECT 1 FROM thought_likes l    WHERE l.thought_id = t.id  AND l.user_id  = $1) AS is_liked,
    EXISTS(SELECT 1 FROM thought_reposts rp WHERE rp.thought_id = t.id AND rp.user_id = $1) AS is_reposted
FROM thoughts t
JOIN users u ON u.id = t.user_id
LEFT JOIN books b ON b.id = t.book_id
WHERE t.id = $2 OR t.thread_root_id = $2
ORDER BY t.thread_root_id IS NOT NULL, t.created_at
`

type GetThoughtThreadParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	RootID   uuid.UUID `json:"root_id"`
}

type GetThoughtThreadRow struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       pgtype.UUID      `json:"book_id"`
	Title        pgtype.Text      `json:"title"`
	Content      string           `json:"content"`
	IsPrivate    bool             `json:"is_private"`
	Rating       pgtype.Int4      `json:"rating"`
	ThreadRootID pgtype.UUID      `json:"thread_root_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Username     string           `json:"username"`
	Name         pgtype.Text      `json:"name"`
	AvatarUrl    pgtype.Text      `json:"avatar_url"`
	BookTitle    pgtype.Text      `json:"book_title"`
	BookSlug     pgtype.Text      `json:"book_slug"`
	BookAuthors  []string         `json:"book_authors"`
	BookCoverUrl pgtype.Text      `json:"book_cover_url"`
	LikesCount   int64            `json:"likes_count"`
	RepostsCount int64            `json:"reposts_count"`
	IsLiked      bool             `json:"is_liked"`
	IsReposted   bool             `json:"is_reposted"`
}

// The first thought and every follow-up, in writing order.
func (q *Queries) GetThoughtThread(ctx context.Context, arg GetThoughtThreadParams) ([]GetThoughtThreadRow, error) {
	rows, err := q.db.Query(ctx, getThoughtThread, arg.ViewerID, arg.RootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThoughtThreadRow{}
	for rows.Next() {
		var i GetThoughtThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Content,
			&i.IsPrivate,
			&i.Rating,
			&i.ThreadRootID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.BookAuthors,
			&i.BookCoverUrl,
			&i.LikesCount,
			&i.RepostsCount,
			&i.IsLiked,
			&i.IsReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThoughtsWithoutEmbedding = `-- name: GetThoughtsWithoutEmbedding :many
SELECT
    de.id,
    de.user_id,
    de.content,
    de.embedding_text,
    b.title   AS book_title,
    b.authors AS book_authors
FROM thoughts de
LEFT JOIN books b ON de.book_id = b.id
WHERE de.embedding IS NULL
ORDER BY de.created_at DESC
`

type GetThoughtsWithoutEmbeddingRow struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Content       string      `json:"content"`
	EmbeddingText pgtype.Text `json:"embedding_text"`
	BookTitle     pgtype.Text `json:"book_title"`
	BookAuthors   []string    `json:"book_authors"`
}

func (q *Queries) GetThoughtsWithoutEmbedding(ctx context.Context) ([]GetThoughtsWithoutEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, getThoughtsWithoutEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThoughtsWithoutEmbeddingRow{}
	for rows.Next() {
		var i GetThoughtsWithoutEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.EmbeddingText,
			&i.BookTitle,
			&i.BookAuthors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserThoughtsFeed = `-- name: GetUserThoughtsFeed :many
WITH items AS (
    SELECT t.id AS thought_id, false AS is_repost, t.created_at AS sort_at
    FROM thoughts t
    WHERE t.user_id = $4
      AND t.thread_root_id IS NULL
      AND (t.is_private = false OR t.user_id = $1)
    UNION ALL
    SELECT r.thought_id, true, r.created_at
    FROM thought_reposts r
    WHERE r.user_id = $4
)
SELECT
    t.id,
    t.user_id,
    t.book_id,
    t.title,
    t.content,
    t.is_private,
    t.rating,
    t.thread_root_id,
    t.created_at,
    t.updated_at,
    i.is_repost::bool AS is_repost,
    u.username,
    u.name,
    u.avatar_url,
    b.title     AS book_title,
    b.slug      AS book_slug,
    b.authors   AS book_authors,
    b.cover_url AS book_cover_url,
    (SELECT COUNT(*) FROM thought_likes l   WHERE l.thought_id = t.id)       AS likes_count,
    (SELECT COUNT(*) FROM thought_reposts rp WHERE rp.thought_id = t.id)     AS reposts_count,
    (SELECT COUNT(*) FROM thoughts c        WHERE c.thread_root_id = t.id)   AS thread_count,
    EXISTS(SELECT 1 FROM thought_likes l    WHERE l.thought_id = t.id  AND l.user_id  = $1) AS is_liked,
    EXISTS(SELECT 1 FROM thought_reposts rp WHERE rp.thought_id = t.id AND rp.user_id = $1) AS is_reposted
FROM items i
JOIN thoughts t ON t.id = i.thought_id
JOIN users u ON u.id = t.user_id
LEFT JOIN books b ON b.id = t.book_id
WHERE i.is_repost = false
   OR (
        t.is_private = false
        AND u.deleted_at IS NULL
        AND (
            u.is_public
            OR u.id = $1
            OR EXISTS (SELECT 1 FROM follows f WHERE f.follower_id = $1 AND f.following_id = u.id)
        )
        AND NOT EXISTS (
            SELECT 1 FROM blocks bl
            WHERE (bl.blocker_id = $1 AND bl.blocked_id = u.id)
               OR (bl.blocker_id = u.id AND bl.blocked_id = $1)
        )
   )
ORDER BY i.sort_at DESC
LIMIT $3 OFFSET $2
`

type GetUserThoughtsFeedParams struct {
	ViewerID  uuid.UUID `json:"viewer_id"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
	ProfileID uuid.UUID `json:"profile_id"`
}

type GetUserThoughtsFeedRow struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	BookID       pgtype.UUID      `json:"book_id"`
	Title        pgtype.Text      `json:"title"`
	Content      string           `json:"content"`
	IsPrivate    bool             `json:"is_private"`
	Rating       pgtype.Int4      `json:"rating"`
	ThreadRootID pgtype.UUID      `json:"thread_root_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	IsRepost     bool             `json:"is_repost"`
	Username     string           `json:"username"`
	Name         pgtype.Text      `json:"name"`
	AvatarUrl    pgtype.Text      `json:"avatar_url"`
	BookTitle    pgtype.Text      `json:"book_title"`
	BookSlug     pgtype.Text      `json:"book_slug"`
	BookAuthors  []string         `json:"book_authors"`
	BookCoverUrl pgtype.Text      `json:"book_cover_url"`
	LikesCount   int64            `json:"likes_count"`
	RepostsCount int64            `json:"reposts_count"`
	ThreadCount  int64            `json:"thread_count"`
	IsLiked      bool             `json:"is_liked"`
	IsReposted   bool             `json:"is_reposted"`
}

// The profile's Thoughts tab: the owner's thoughts that start a thread (or
// stand alone) interleaved with thoughts they reposted, newest activity first.
// A repost is re-checked against the original author on every read, so a
// thought that went private, an author who went private, or a block made after
// the repost all hide it without touching thought_reposts.
func (q *Queries) GetUserThoughtsFeed(ctx context.Context, arg GetUserThoughtsFeedParams) ([]GetUserThoughtsFeedRow, error) {
	rows, err := q.db.Query(ctx, getUserThoughtsFeed,
		arg.ViewerID,
		arg.Offset,
		arg.Limit,
		arg.ProfileID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserThoughtsFeedRow{}
	for rows.Next() {
		var i GetUserThoughtsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Content,
			&i.IsPrivate,
			&i.Rating,
			&i.ThreadRootID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsRepost,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.BookTitle,
			&i.BookSlug,
			&i.BookAuthors,
			&i.BookCoverUrl,
			&i.LikesCount,
			&i.RepostsCount,
			&i.ThreadCount,
			&i.IsLiked,
			&i.IsReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserThoughtCount = `-- name: IncrementUserThoughtCount :exec
UPDATE users
SET thoughts_count = thoughts_count + 1
WHERE id = $1
`

func (q *Queries) IncrementUserThoughtCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserThoughtCount, id)
	return err
}

const likeThought = `-- name: LikeThought :one

INSERT INTO thought_likes (user_id, thought_id)
VALUES ($1, $2)
RETURNING id, user_id, thought_id, created_at
`

type LikeThoughtParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

// Likes
func (q *Queries) LikeThought(ctx context.Context, arg LikeThoughtParams) (ThoughtLike, error) {
	row := q.db.QueryRow(ctx, likeThought, arg.UserID, arg.ThoughtID)
	var i ThoughtLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ThoughtID,
		&i.CreatedAt,
	)
	return i, err
}

const repostThought = `-- name: RepostThought :execrows

INSERT INTO thought_reposts (user_id, thought_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type RepostThoughtParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

// Reposts
func (q *Queries) RepostThought(ctx context.Context, arg RepostThoughtParams) (int64, error) {
	result, err := q.db.Exec(ctx, repostThought, arg.UserID, arg.ThoughtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setThreadPrivacy = `-- name: SetThreadPrivacy :exec
UPDATE thoughts
SET is_private     = $1::bool,
    embedding      = CASE WHEN $1::bool THEN NULL ELSE embedding END,
    embedding_text = CASE WHEN $1::bool THEN NULL ELSE embedding_text END,
    updated_at     = NOW()
WHERE thread_root_id = $2
`

type SetThreadPrivacyParams struct {
	IsPrivate bool        `json:"is_private"`
	RootID    pgtype.UUID `json:"root_id"`
}

// A thread is private or public as a whole. Going private also retracts the
// follow-ups' embeddings, for the same reason the single-thought path does.
func (q *Queries) SetThreadPrivacy(ctx context.Context, arg SetThreadPrivacyParams) error {
	_, err := q.db.Exec(ctx, setThreadPrivacy, arg.IsPrivate, arg.RootID)
	return err
}

const unlikeThought = `-- name: UnlikeThought :exec
DELETE FROM thought_likes
WHERE user_id = $1 AND thought_id = $2
`

type UnlikeThoughtParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

func (q *Queries) UnlikeThought(ctx context.Context, arg UnlikeThoughtParams) error {
	_, err := q.db.Exec(ctx, unlikeThought, arg.UserID, arg.ThoughtID)
	return err
}

const unrepostThought = `-- name: UnrepostThought :execrows
DELETE FROM thought_reposts
WHERE user_id = $1 AND thought_id = $2
`

type UnrepostThoughtParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ThoughtID uuid.UUID `json:"thought_id"`
}

func (q *Queries) UnrepostThought(ctx context.Context, arg UnrepostThoughtParams) (int64, error) {
	result, err := q.db.Exec(ctx, unrepostThought, arg.UserID, arg.ThoughtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateThought = `-- name: UpdateThought :one
UPDATE thoughts
SET
    title = $2,
    content = $3,
    is_private = $4,
    rating = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, book_id, title, content, is_private, rating, created_at, updated_at, embedding, embedding_text, thread_root_id
`

type UpdateThoughtParams struct {
	ID        uuid.UUID   `json:"id"`
	Title     pgtype.Text `json:"title"`
	Content   string      `json:"content"`
	IsPrivate bool        `json:"is_private"`
	Rating    pgtype.Int4 `json:"rating"`
}

func (q *Queries) UpdateThought(ctx context.Context, arg UpdateThoughtParams) (Thought, error) {
	row := q.db.QueryRow(ctx, updateThought,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPrivate,
		arg.Rating,
	)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Content,
		&i.IsPrivate,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
		&i.EmbeddingText,
		&i.ThreadRootID,
	)
	return i, err
}

const updateThoughtEmbedding = `-- name: UpdateThoughtEmbedding :exec

UPDATE thoughts
SET embedding = $2::vector, embedding_text = $3
WHERE id = $1
`

type UpdateThoughtEmbeddingParams struct {
	ID            uuid.UUID       `json:"id"`
	Column2       pgvector.Vector `json:"column_2"`
	EmbeddingText pgtype.Text     `json:"embedding_text"`
}

// Embeddings
func (q *Queries) UpdateThoughtEmbedding(ctx context.Context, arg UpdateThoughtEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateThoughtEmbedding, arg.ID, arg.Column2, arg.EmbeddingText)
	return err
}
