// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, name, favorite_genres
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	PasswordHash   pgtype.Text `json:"password_hash"`
	Name           pgtype.Text `json:"name"`
	FavoriteGenres []string    `json:"favorite_genres"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.FavoriteGenres,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const followingIDs = `-- name: FollowingIDs :many
SELECT following_id FROM follows WHERE follower_id = $1 LIMIT 1000
`

func (q *Queries) FollowingIDs(ctx context.Context, followerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, followingIDs, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var following_id uuid.UUID
		if err := rows.Scan(&following_id); err != nil {
			return nil, err
		}
		items = append(items, following_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularReaders = `-- name: GetPopularReaders :many
SELECT
    u.id,
    u.username,
    u.name,
    u.avatar_url,
    u.bio,
    u.followers_count,
    (SELECT COUNT(*) FROM bookshelf bs WHERE bs.user_id = u.id AND bs.status = 'read')::int AS books_read_count,
    ARRAY(
        SELECT COALESCE(b.cover_url, '')
        FROM favorites f JOIN books b ON b.id = f.book_id
        WHERE f.user_id = u.id
        ORDER BY f.display_order
        LIMIT 4
    )::text[] AS favorite_covers
FROM users u
WHERE u.deleted_at IS NULL
  AND u.is_public = true
  AND EXISTS (SELECT 1 FROM bookshelf bs WHERE bs.user_id = u.id)
ORDER BY u.followers_count DESC, books_read_count DESC, u.created_at ASC
LIMIT $1
`

type GetPopularReadersRow struct {
	ID             uuid.UUID   `json:"id"`
	Username       string      `json:"username"`
	Name           pgtype.Text `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Bio            pgtype.Text `json:"bio"`
	FollowersCount pgtype.Int4 `json:"followers_count"`
	BooksReadCount int32       `json:"books_read_count"`
	FavoriteCovers []string    `json:"favorite_covers"`
}

// Public readers for the logged-out "who is here" strip. Followers first, then
// live read count; must have something on the shelf so the Top 4 / count are
// not both empty.
func (q *Queries) GetPopularReaders(ctx context.Context, limit int32) ([]GetPopularReadersRow, error) {
	rows, err := q.db.Query(ctx, getPopularReaders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularReadersRow{}
	for rows.Next() {
		var i GetPopularReadersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
			&i.FollowersCount,
			&i.BooksReadCount,
			&i.FavoriteCovers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAppleUserID = `-- name: GetUserByAppleUserID :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period FROM users
WHERE apple_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByAppleUserID(ctx context.Context, appleUserID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleUserID, appleUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const linkAppleUserID = `-- name: LinkAppleUserID :exec
UPDATE users
SET apple_user_id = $2, updated_at = NOW()
WHERE id = $1
`

type LinkAppleUserIDParams struct {
	ID          uuid.UUID   `json:"id"`
	AppleUserID pgtype.Text `json:"apple_user_id"`
}

func (q *Queries) LinkAppleUserID(ctx context.Context, arg LinkAppleUserIDParams) error {
	_, err := q.db.Exec(ctx, linkAppleUserID, arg.ID, arg.AppleUserID)
	return err
}

const mutualFollowCounts = `-- name: MutualFollowCounts :many
SELECT f.following_id AS user_id, COUNT(*)::int AS mutuals
FROM follows f
WHERE f.following_id = ANY($1::uuid[])
  AND f.follower_id = ANY($2::uuid[])
GROUP BY f.following_id
`

type MutualFollowCountsParams struct {
	CandidateIds []uuid.UUID `json:"candidate_ids"`
	FollowerIds  []uuid.UUID `json:"follower_ids"`
}

type MutualFollowCountsRow struct {
	UserID  uuid.UUID `json:"user_id"`
	Mutuals int32     `json:"mutuals"`
}

// Candidates followed by people the viewer already follows.
func (q *Queries) MutualFollowCounts(ctx context.Context, arg MutualFollowCountsParams) ([]MutualFollowCountsRow, error) {
	rows, err := q.db.Query(ctx, mutualFollowCounts, arg.CandidateIds, arg.FollowerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MutualFollowCountsRow{}
	for rows.Next() {
		var i MutualFollowCountsRow
		if err := rows.Scan(&i.UserID, &i.Mutuals); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAccountDeletion = `-- name: RecordAccountDeletion :exec
INSERT INTO account_deletions (
    user_id, email_hash, reasons
) VALUES (
    $1, $2, $3
)
`

type RecordAccountDeletionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EmailHash pgtype.Text `json:"email_hash"`
	Reasons   []string    `json:"reasons"`
}

// email_hash, not the address: this row outlives the 30-day hard purge, so a
// cleartext address here would outlive the account forever. See migration 41.
func (q *Queries) RecordAccountDeletion(ctx context.Context, arg RecordAccountDeletionParams) error {
	_, err := q.db.Exec(ctx, recordAccountDeletion, arg.UserID, arg.EmailHash, arg.Reasons)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period FROM users
WHERE (username ILIKE '%' || $1 || '%'
   OR name ILIKE '%' || $1 || '%')
   AND deleted_at IS NULL
ORDER BY followers_count DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
			&i.Pronouns,
			&i.IsPublic,
			&i.FavoriteGenres,
			&i.Settings,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.BooksReadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActive,
			&i.DeletedAt,
			&i.MongoID,
			&i.Birthday,
			&i.Gender,
			&i.Links,
			&i.TotalPagesRead,
			&i.FavoritesCount,
			&i.ListsCount,
			&i.ThoughtsCount,
			&i.ReadingGoalYear,
			&i.ReadingGoalTarget,
			&i.ReadingGoalCurrent,
			&i.TotalXp,
			&i.Level,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LastActivityDate,
			&i.ShowOnLeaderboard,
			&i.ReferralCode,
			&i.ReferredBy,
			&i.ReferralCount,
			&i.ReferralRewardsClaimed,
			&i.OnboardingCompleted,
			&i.BannerUrl,
			&i.ScanUsesRemaining,
			&i.AppleUserID,
			&i.ScanPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserVisibility = `-- name: SetUserVisibility :one
UPDATE users SET is_public = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period
`

type SetUserVisibilityParams struct {
	ID       uuid.UUID `json:"id"`
	IsPublic bool      `json:"is_public"`
}

func (q *Queries) SetUserVisibility(ctx context.Context, arg SetUserVisibilityParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserVisibility, arg.ID, arg.IsPublic)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const sharedReadCounts = `-- name: SharedReadCounts :many
SELECT bs.user_id, COUNT(*)::int AS shared, MIN(bk.title)::text AS sample_title
FROM bookshelf bs
JOIN books bk ON bk.id = bs.book_id
WHERE bs.user_id = ANY($1::uuid[])
  AND bs.status = 'read'
  AND bs.book_id = ANY($2::uuid[])
GROUP BY bs.user_id
`

type SharedReadCountsParams struct {
	CandidateIds []uuid.UUID `json:"candidate_ids"`
	BookIds      []uuid.UUID `json:"book_ids"`
}

type SharedReadCountsRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Shared      int32     `json:"shared"`
	SampleTitle string    `json:"sample_title"`
}

// How many of those books each candidate has also finished, plus one title to
// name. MIN(title) keeps the sample stable between calls.
func (q *Queries) SharedReadCounts(ctx context.Context, arg SharedReadCountsParams) ([]SharedReadCountsRow, error) {
	rows, err := q.db.Query(ctx, sharedReadCounts, arg.CandidateIds, arg.BookIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedReadCountsRow{}
	for rows.Next() {
		var i SharedReadCountsRow
		if err := rows.Scan(&i.UserID, &i.Shared, &i.SampleTitle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(),
    updated_at = NOW(),
    email      = 'd_' || REPLACE(id::text, '-', '') || '@deleted.local',
    username   = 'd_' || REPLACE(id::text, '-', '')
WHERE id = $1 AND deleted_at IS NULL
`

// Soft-delete the user and free their email/username so they (or anyone) can
// re-register with the same identifiers. The original values are preserved in
// the account_deletions audit table by RecordAccountDeletion (called first).
// The UUID-based placeholders are deterministic and lowercase, satisfying the
// column-level UNIQUE constraints and the username_lowercase CHECK.
func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const suggestedUsers = `-- name: SuggestedUsers :many
SELECT
    u.id,
    u.username,
    u.name,
    u.avatar_url,
    u.bio,
    u.followers_count,
    (SELECT COUNT(*) FROM bookshelf bs WHERE bs.user_id = u.id AND bs.status = 'read')::int AS books_read_count,
    ARRAY(SELECT g FROM unnest(u.favorite_genres) AS g WHERE g = ANY($1::text[]))::text[] AS shared_genres
FROM users u
WHERE u.deleted_at IS NULL
  AND u.is_public = true
  AND u.id <> $2
  AND NOT EXISTS (
      SELECT 1 FROM follows f
      WHERE f.follower_id = $2 AND f.following_id = u.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocks b
      WHERE (b.blocker_id = $2 AND b.blocked_id = u.id)
         OR (b.blocker_id = u.id AND b.blocked_id = $2)
  )
  AND EXISTS (SELECT 1 FROM bookshelf bs WHERE bs.user_id = u.id)
ORDER BY
    cardinality(ARRAY(SELECT g FROM unnest(u.favorite_genres) AS g WHERE g = ANY($1::text[]))) DESC,
    books_read_count DESC,
    u.followers_count DESC
LIMIT $3
`

type SuggestedUsersParams struct {
	ViewerGenres []string  `json:"viewer_genres"`
	ViewerID     uuid.UUID `json:"viewer_id"`
	RowLimit     int32     `json:"row_limit"`
}

type SuggestedUsersRow struct {
	ID             uuid.UUID   `json:"id"`
	Username       string      `json:"username"`
	Name           pgtype.Text `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Bio            pgtype.Text `json:"bio"`
	FollowersCount pgtype.Int4 `json:"followers_count"`
	BooksReadCount int32       `json:"books_read_count"`
	SharedGenres   []string    `json:"shared_genres"`
}

// Candidate readers to follow: public, not self, not already followed, not
// blocked either way, and with something on their shelf so the feed they
// produce is non-empty. Ordered by favourite-genre overlap, then live read
// count (the cached users.books_read_count drifts), then followers.
//
// The handler over-fetches here and re-ranks with SharedReadCounts and
// MutualFollowCounts, which carry the stronger "you both read X" and "followed
// by people you follow" signals. Those cannot live in this query: sqlc's
// analyser cannot resolve the same table aliased twice inside a subquery.
func (q *Queries) SuggestedUsers(ctx context.Context, arg SuggestedUsersParams) ([]SuggestedUsersRow, error) {
	rows, err := q.db.Query(ctx, suggestedUsers, arg.ViewerGenres, arg.ViewerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestedUsersRow{}
	for rows.Next() {
		var i SuggestedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
			&i.FollowersCount,
			&i.BooksReadCount,
			&i.SharedGenres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name = COALESCE($2, name),
    bio = COALESCE($3, bio),
    pronouns = COALESCE($4, pronouns),
    avatar_url = COALESCE($5, avatar_url),
    birthday = COALESCE($6, birthday),
    gender = COALESCE($7, gender),
    links = COALESCE($8, links),
    banner_url = COALESCE($9, banner_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period
`

type UpdateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      pgtype.Text `json:"name"`
	Bio       pgtype.Text `json:"bio"`
	Pronouns  []string    `json:"pronouns"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Birthday  pgtype.Date `json:"birthday"`
	Gender    pgtype.Text `json:"gender"`
	Links     []string    `json:"links"`
	BannerUrl pgtype.Text `json:"banner_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.Pronouns,
		arg.AvatarUrl,
		arg.Birthday,
		arg.Gender,
		arg.Links,
		arg.BannerUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const updateUserGenres = `-- name: UpdateUserGenres :one
UPDATE users SET favorite_genres = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period
`

type UpdateUserGenresParams struct {
	ID             uuid.UUID `json:"id"`
	FavoriteGenres []string  `json:"favorite_genres"`
}

func (q *Queries) UpdateUserGenres(ctx context.Context, arg UpdateUserGenresParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGenres, arg.ID, arg.FavoriteGenres)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const updateUserLastActive = `-- name: UpdateUserLastActive :exec
UPDATE users
SET last_active = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastActive, id)
	return err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users SET username = $2, onboarding_completed = true, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id, birthday, gender, links, total_pages_read, favorites_count, lists_count, thoughts_count, reading_goal_year, reading_goal_target, reading_goal_current, total_xp, level, current_streak, longest_streak, last_activity_date, show_on_leaderboard, referral_code, referred_by, referral_count, referral_rewards_claimed, onboarding_completed, banner_url, scan_uses_remaining, apple_user_id, scan_period
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
		&i.Birthday,
		&i.Gender,
		&i.Links,
		&i.TotalPagesRead,
		&i.FavoritesCount,
		&i.ListsCount,
		&i.ThoughtsCount,
		&i.ReadingGoalYear,
		&i.ReadingGoalTarget,
		&i.ReadingGoalCurrent,
		&i.TotalXp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
		&i.ShowOnLeaderboard,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.ReferralCount,
		&i.ReferralRewardsClaimed,
		&i.OnboardingCompleted,
		&i.BannerUrl,
		&i.ScanUsesRemaining,
		&i.AppleUserID,
		&i.ScanPeriod,
	)
	return i, err
}

const upsertAuthorRead = `-- name: UpsertAuthorRead :one
INSERT INTO user_authors_read (user_id, author_name)
VALUES ($1, $2)
ON CONFLICT (user_id, author_name) DO UPDATE SET author_name = EXCLUDED.author_name
RETURNING id, user_id, author_name, books_read, books_tbr, favorite_book_id, created_at
`

type UpsertAuthorReadParams struct {
	UserID     uuid.UUID `json:"user_id"`
	AuthorName string    `json:"author_name"`
}

func (q *Queries) UpsertAuthorRead(ctx context.Context, arg UpsertAuthorReadParams) (UserAuthorsRead, error) {
	row := q.db.QueryRow(ctx, upsertAuthorRead, arg.UserID, arg.AuthorName)
	var i UserAuthorsRead
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorName,
		&i.BooksRead,
		&i.BooksTbr,
		&i.FavoriteBookID,
		&i.CreatedAt,
	)
	return i, err
}

const userReadBookIDs = `-- name: UserReadBookIDs :many
SELECT book_id FROM bookshelf
WHERE user_id = $1 AND status = 'read'
LIMIT 500
`

// The viewer's finished books, for the "you both read X" signal. Capped: a
// heavy reader's whole shelf is not needed to find overlap worth naming.
func (q *Queries) UserReadBookIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, userReadBookIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var book_id uuid.UUID
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
