// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, name, favorite_genres
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	PasswordHash   pgtype.Text `json:"password_hash"`
	Name           pgtype.Text `json:"name"`
	FavoriteGenres []string    `json:"favorite_genres"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.FavoriteGenres,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, name, avatar_url, bio, pronouns, is_public, favorite_genres, settings, followers_count, following_count, books_read_count, created_at, updated_at, last_active, deleted_at, mongo_id FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Pronouns,
		&i.IsPublic,
		&i.FavoriteGenres,
		&i.Settings,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.BooksReadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActive,
		&i.DeletedAt,
		&i.MongoID,
	)
	return i, err
}

const updateUserLastActive = `-- name: UpdateUserLastActive :exec
UPDATE users
SET last_active = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastActive, id)
	return err
}
