// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wrapped.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const wrappedAbandoned = `-- name: WrappedAbandoned :one
SELECT
    b.title,
    b.authors,
    b.page_count,
    bs.current_page,
    bs.started_at,
    MAX(rl.logged_at)::TIMESTAMPTZ AS last_logged
FROM bookshelf bs
JOIN books b ON b.id = bs.book_id
LEFT JOIN reading_log rl
       ON rl.user_id = bs.user_id
      AND rl.book_id = bs.book_id
      AND rl.logged_at < $1
WHERE bs.user_id = $2
  AND bs.status = 'reading'
  AND COALESCE(bs.current_page, 0) > 0
  AND bs.started_at IS NOT NULL
  AND bs.started_at < $1
GROUP BY b.id, bs.current_page, bs.started_at
HAVING COALESCE(MAX(rl.logged_at), bs.started_at) < $3
ORDER BY (COALESCE(bs.current_page, 0)::FLOAT / NULLIF(b.page_count, 0)) ASC NULLS LAST
LIMIT 1
`

type WrappedAbandonedParams struct {
	MonthEnd    pgtype.Timestamptz `json:"month_end"`
	UserID      uuid.UUID          `json:"user_id"`
	StallBefore pgtype.Timestamptz `json:"stall_before"`
}

type WrappedAbandonedRow struct {
	Title       string             `json:"title"`
	Authors     []string           `json:"authors"`
	PageCount   pgtype.Int4        `json:"page_count"`
	CurrentPage pgtype.Int4        `json:"current_page"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	LastLogged  pgtype.Timestamptz `json:"last_logged"`
}

// Still marked "reading", started before the month ended, and untouched since
// stall_before. Ordered by how little of it was read — the most abandoned one
// makes the best chapter.
func (q *Queries) WrappedAbandoned(ctx context.Context, arg WrappedAbandonedParams) (WrappedAbandonedRow, error) {
	row := q.db.QueryRow(ctx, wrappedAbandoned, arg.MonthEnd, arg.UserID, arg.StallBefore)
	var i WrappedAbandonedRow
	err := row.Scan(
		&i.Title,
		&i.Authors,
		&i.PageCount,
		&i.CurrentPage,
		&i.StartedAt,
		&i.LastLogged,
	)
	return i, err
}

const wrappedBooksFinished = `-- name: WrappedBooksFinished :one
SELECT COUNT(*)::INT AS books
FROM bookshelf
WHERE user_id = $1
  AND status = 'read'
  AND finished_at >= $2
  AND finished_at <  $3
`

type WrappedBooksFinishedParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

func (q *Queries) WrappedBooksFinished(ctx context.Context, arg WrappedBooksFinishedParams) (int32, error) {
	row := q.db.QueryRow(ctx, wrappedBooksFinished, arg.UserID, arg.MonthStart, arg.MonthEnd)
	var books int32
	err := row.Scan(&books)
	return books, err
}

const wrappedDailyPages = `-- name: WrappedDailyPages :many
SELECT
    (logged_at AT TIME ZONE $1::TEXT)::DATE AS log_date,
    SUM(GREATEST(pages_delta, 0))::INT                AS pages
FROM reading_log
WHERE user_id = $2
  AND logged_at >= $3
  AND logged_at <  $4
GROUP BY 1
ORDER BY 1
`

type WrappedDailyPagesParams struct {
	Tz         string             `json:"tz"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedDailyPagesRow struct {
	LogDate pgtype.Date `json:"log_date"`
	Pages   int32       `json:"pages"`
}

// Only days with entries come back; the handler fills the rest of the month
// with zeros so the calendar grid is always month-length.
func (q *Queries) WrappedDailyPages(ctx context.Context, arg WrappedDailyPagesParams) ([]WrappedDailyPagesRow, error) {
	rows, err := q.db.Query(ctx, wrappedDailyPages,
		arg.Tz,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrappedDailyPagesRow{}
	for rows.Next() {
		var i WrappedDailyPagesRow
		if err := rows.Scan(&i.LogDate, &i.Pages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wrappedGenres = `-- name: WrappedGenres :many
WITH per_book AS (
    SELECT
        rl.book_id,
        b.categories,
        SUM(GREATEST(rl.pages_delta, 0))::INT AS pages
    FROM reading_log rl
    JOIN books b ON b.id = rl.book_id
    WHERE rl.user_id = $2
      AND rl.logged_at >= $3
      AND rl.logged_at <  $4
    GROUP BY rl.book_id, b.categories
    HAVING SUM(GREATEST(rl.pages_delta, 0)) > 0
)
SELECT
    c.category::TEXT   AS name,
    SUM(pb.pages)::INT AS pages
FROM per_book pb, unnest(pb.categories) AS c(category)
WHERE c.category IS NOT NULL AND c.category <> ''
GROUP BY c.category
ORDER BY pages DESC, name ASC
LIMIT $1
`

type WrappedGenresParams struct {
	RowLimit   int32              `json:"row_limit"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedGenresRow struct {
	Name  string `json:"name"`
	Pages int32  `json:"pages"`
}

// Categories weighted by pages read, not by book count: a 900-page epic should
// outweigh a novella. The handler turns these into percentages.
func (q *Queries) WrappedGenres(ctx context.Context, arg WrappedGenresParams) ([]WrappedGenresRow, error) {
	rows, err := q.db.Query(ctx, wrappedGenres,
		arg.RowLimit,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrappedGenresRow{}
	for rows.Next() {
		var i WrappedGenresRow
		if err := rows.Scan(&i.Name, &i.Pages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wrappedHourHistogram = `-- name: WrappedHourHistogram :many
SELECT
    EXTRACT(HOUR FROM (logged_at AT TIME ZONE $1::TEXT))::INT AS hour,
    SUM(GREATEST(pages_delta, 0))::INT                                  AS pages
FROM reading_log
WHERE user_id = $2
  AND logged_at >= $3
  AND logged_at <  $4
GROUP BY 1
ORDER BY 1
`

type WrappedHourHistogramParams struct {
	Tz         string             `json:"tz"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedHourHistogramRow struct {
	Hour  int32 `json:"hour"`
	Pages int32 `json:"pages"`
}

func (q *Queries) WrappedHourHistogram(ctx context.Context, arg WrappedHourHistogramParams) ([]WrappedHourHistogramRow, error) {
	rows, err := q.db.Query(ctx, wrappedHourHistogram,
		arg.Tz,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrappedHourHistogramRow{}
	for rows.Next() {
		var i WrappedHourHistogramRow
		if err := rows.Scan(&i.Hour, &i.Pages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wrappedRank = `-- name: WrappedRank :one
WITH totals AS (
    SELECT user_id, SUM(GREATEST(pages_delta, 0))::INT AS pages
    FROM reading_log
    WHERE logged_at >= $2
      AND logged_at <  $3
    GROUP BY user_id
    HAVING SUM(GREATEST(pages_delta, 0)) > 0
)
SELECT
    COALESCE((SELECT COUNT(*) FROM totals), 0)::INT AS readers,
    COALESCE((
        SELECT COUNT(*) FROM totals
        WHERE pages < (SELECT pages FROM totals WHERE user_id = $1)
    ), 0)::INT AS beaten
`

type WrappedRankParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedRankRow struct {
	Readers int32 `json:"readers"`
	Beaten  int32 `json:"beaten"`
}

// Where the reader landed against everyone who read anything that month.
func (q *Queries) WrappedRank(ctx context.Context, arg WrappedRankParams) (WrappedRankRow, error) {
	row := q.db.QueryRow(ctx, wrappedRank, arg.UserID, arg.MonthStart, arg.MonthEnd)
	var i WrappedRankRow
	err := row.Scan(&i.Readers, &i.Beaten)
	return i, err
}

const wrappedTopAuthors = `-- name: WrappedTopAuthors :many
WITH per_book AS (
    SELECT
        rl.book_id,
        b.authors,
        SUM(GREATEST(rl.pages_delta, 0))::INT AS pages
    FROM reading_log rl
    JOIN books b ON b.id = rl.book_id
    WHERE rl.user_id = $2
      AND rl.logged_at >= $3
      AND rl.logged_at <  $4
    GROUP BY rl.book_id, b.authors
    HAVING SUM(GREATEST(rl.pages_delta, 0)) > 0
)
SELECT
    a.author::TEXT                     AS name,
    COUNT(DISTINCT pb.book_id)::INT    AS books,
    SUM(pb.pages)::INT                 AS pages
FROM per_book pb, unnest(pb.authors) AS a(author)
WHERE a.author IS NOT NULL AND a.author <> ''
GROUP BY a.author
ORDER BY pages DESC, name ASC
LIMIT $1
`

type WrappedTopAuthorsParams struct {
	RowLimit   int32              `json:"row_limit"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedTopAuthorsRow struct {
	Name  string `json:"name"`
	Books int32  `json:"books"`
	Pages int32  `json:"pages"`
}

// Pages are attributed to every credited author of a book; a co-authored book
// counts once for each of them, which is how the reader thinks about it.
func (q *Queries) WrappedTopAuthors(ctx context.Context, arg WrappedTopAuthorsParams) ([]WrappedTopAuthorsRow, error) {
	rows, err := q.db.Query(ctx, wrappedTopAuthors,
		arg.RowLimit,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrappedTopAuthorsRow{}
	for rows.Next() {
		var i WrappedTopAuthorsRow
		if err := rows.Scan(&i.Name, &i.Books, &i.Pages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wrappedTopBooks = `-- name: WrappedTopBooks :many
SELECT
    b.id,
    b.title,
    b.authors,
    b.cover_url,
    b.page_count,
    bs.rating,
    SUM(GREATEST(rl.pages_delta, 0))::INT                                            AS pages,
    COUNT(DISTINCT (rl.logged_at AT TIME ZONE $1::TEXT)::DATE)::INT        AS days
FROM reading_log rl
JOIN books b ON b.id = rl.book_id
LEFT JOIN bookshelf bs ON bs.user_id = rl.user_id AND bs.book_id = rl.book_id
WHERE rl.user_id = $2
  AND rl.logged_at >= $3
  AND rl.logged_at <  $4
GROUP BY b.id, bs.rating
HAVING SUM(GREATEST(rl.pages_delta, 0)) > 0
ORDER BY pages DESC, b.title ASC
LIMIT $5
`

type WrappedTopBooksParams struct {
	Tz         string             `json:"tz"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
	RowLimit   int32              `json:"row_limit"`
}

type WrappedTopBooksRow struct {
	ID        uuid.UUID   `json:"id"`
	Title     string      `json:"title"`
	Authors   []string    `json:"authors"`
	CoverUrl  pgtype.Text `json:"cover_url"`
	PageCount pgtype.Int4 `json:"page_count"`
	Rating    pgtype.Int4 `json:"rating"`
	Pages     int32       `json:"pages"`
	Days      int32       `json:"days"`
}

func (q *Queries) WrappedTopBooks(ctx context.Context, arg WrappedTopBooksParams) ([]WrappedTopBooksRow, error) {
	rows, err := q.db.Query(ctx, wrappedTopBooks,
		arg.Tz,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WrappedTopBooksRow{}
	for rows.Next() {
		var i WrappedTopBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Authors,
			&i.CoverUrl,
			&i.PageCount,
			&i.Rating,
			&i.Pages,
			&i.Days,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wrappedTopRated = `-- name: WrappedTopRated :one
SELECT
    b.title,
    b.authors,
    b.cover_url,
    bs.rating,
    bs.review,
    bs.finished_at
FROM bookshelf bs
JOIN books b ON b.id = bs.book_id
WHERE bs.user_id = $1
  AND bs.status = 'read'
  AND bs.rating IS NOT NULL
  AND bs.finished_at >= $2
  AND bs.finished_at <  $3
ORDER BY bs.rating DESC, bs.finished_at DESC
LIMIT 1
`

type WrappedTopRatedParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedTopRatedRow struct {
	Title      string             `json:"title"`
	Authors    []string           `json:"authors"`
	CoverUrl   pgtype.Text        `json:"cover_url"`
	Rating     pgtype.Int4        `json:"rating"`
	Review     pgtype.Text        `json:"review"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

// The month's best book: highest rating finished inside the window, most
// recent finish breaking ties. Its review is the chapter's pull quote.
func (q *Queries) WrappedTopRated(ctx context.Context, arg WrappedTopRatedParams) (WrappedTopRatedRow, error) {
	row := q.db.QueryRow(ctx, wrappedTopRated, arg.UserID, arg.MonthStart, arg.MonthEnd)
	var i WrappedTopRatedRow
	err := row.Scan(
		&i.Title,
		&i.Authors,
		&i.CoverUrl,
		&i.Rating,
		&i.Review,
		&i.FinishedAt,
	)
	return i, err
}

const wrappedTotals = `-- name: WrappedTotals :one

WITH logs AS (
    SELECT
        (logged_at AT TIME ZONE $1::TEXT)::DATE AS d,
        GREATEST(pages_delta, 0) AS pages
    FROM reading_log
    WHERE user_id = $2
      AND logged_at >= $3
      AND logged_at <  $4
),
days AS (
    SELECT d, SUM(pages)::INT AS pages
    FROM logs
    GROUP BY d
)
SELECT
    COALESCE((SELECT SUM(pages) FROM logs), 0)::INT                  AS pages,
    COALESCE((SELECT COUNT(*)   FROM logs), 0)::INT                  AS sessions,
    COALESCE((SELECT COUNT(*)   FROM days WHERE pages > 0), 0)::INT  AS active_days,
    COALESCE((SELECT MAX(pages) FROM days), 0)::INT                  AS biggest_day_pages,
    (SELECT d FROM days ORDER BY pages DESC, d ASC LIMIT 1)          AS biggest_day
`

type WrappedTotalsParams struct {
	Tz         string             `json:"tz"`
	UserID     uuid.UUID          `json:"user_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type WrappedTotalsRow struct {
	Pages           int32       `json:"pages"`
	Sessions        int32       `json:"sessions"`
	ActiveDays      int32       `json:"active_days"`
	BiggestDayPages int32       `json:"biggest_day_pages"`
	BiggestDay      pgtype.Date `json:"biggest_day"`
}

// Monthly Wrapped aggregates.
//
// Every query is bounded by an explicit [month_start, month_end) window the
// handler computes in the reader's own timezone, and buckets days/hours in
// that same zone: a book read at 1am in Delhi belongs to the Delhi night, not
// to the previous UTC day.
//
// pages_delta can be negative (a reader correcting a page count downward), so
// every page total clamps with GREATEST(pages_delta, 0) — a correction is not
// reading.
func (q *Queries) WrappedTotals(ctx context.Context, arg WrappedTotalsParams) (WrappedTotalsRow, error) {
	row := q.db.QueryRow(ctx, wrappedTotals,
		arg.Tz,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
	)
	var i WrappedTotalsRow
	err := row.Scan(
		&i.Pages,
		&i.Sessions,
		&i.ActiveDays,
		&i.BiggestDayPages,
		&i.BiggestDay,
	)
	return i, err
}
